### ISSUE TITLE
null issues in config

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/gatsby-source-wordpress-experimental#1]
If I don't have a debug object in my config this throws `Cannot read property 'timeBuildSteps' of undefined`. Needs some optional chaining or config validation/defaults.

https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/06441416ee7917ac239eb338c21c69606454af13/src/utils/run-steps.js#L6

**Comment by TylerBarnes** [comment]
Thanks @moonmeister! I think the default plugin options probably need to be deep merged since I think I'm probably just object merging. I'll get this fixed asap, thanks for the report!

**Comment by TylerBarnes** [comment]
Just opened a PR to fix this, thanks again @moonmeister !
