### ISSUE TITLE
Inline Image Processing: Allow for Shared Options for Sharp Fluid Query

### ISSUE THREAD

**Issue by 0aveRyan** [gatsbyjs/gatsby-source-wordpress-experimental#100]
https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/#shared-options

It'd be great to be able to pass a single object to configure sharp to the `html` pluginOptions  with `toFormat` and `traceSVG` in particular.

**Comment by TylerBarnes** [comment]
I agree 100%, we'll definitely be adding this as an option after the first stable release. Thanks for suggesting this!

**Comment by TylerBarnes** [comment]
Closing this as a duplicate of #71 

Thanks again for the awesome suggestion :D
