### ISSUE TITLE
Is there a way to get the post specific css created by Elementor?

### ISSUE THREAD

**Issue by mgrubiak** [gatsbyjs/gatsby-source-wordpress-experimental#102]
Hallo :)

Is there actually a way to get back the css Elementor is creating for specific posts?

File src:
`https://domain/wp-content/uploads/elementor/css/post-{POSTID}.css`

File content:
`.elementor-5216 .elementor-element.elementor-element-03b5e81 .elementor-spacer-inner{height:20px;}.elementor-5216 .elementor-element.elementor-element-3156738{text-align:center;}.elementor-5216 .elementor-element.elementor-element-3156738 .elementor-repeater-item-8be1125{left:90.2%;top:11.5%;}.elementor-5216 .elementor-element.elementor-element-3156738 .elementor-repeater-item-3609d31{left:14.9%;top:39.7%;}.elementor-5216 .elementor-element.elementor-element-3156738 .elementor-repeater-item-f2509e7{left:90.2%;top:60.9%;}.elementor-5216 .elementor-element.elementor-element-3156738 .elementor-repeater-item-92e477e{left:51.2%;top:82.2%;}.ee-tooltip.ee-tooltip-3156738:after{content:"";}.ee-tooltip.ee-tooltip-3156738.to--top,
						 .ee-tooltip.ee-tooltip-3156738.to--bottom{margin-left:0px;}.ee-tooltip.ee-tooltip-3156738.to--left,
						 .ee-tooltip.ee-tooltip-3156738.to--right{margin-top:0px;}.ee-tooltip.ee-tooltip-3156738{width:200px;z-index:999;}.elementor-5216 .elementor-element.elementor-element-3156738 .ee-hotspots img{opacity:1;}.elementor-5216 .elementor-element.elementor-element-3156738 .ee-hotspot__wrapper{border-radius:100px;transform:scale(1);}.elementor-5216 .elementor-element.elementor-element-3156738 .ee-hotspot__wrapper:before{border-radius:100px;}.elementor-5216 .elementor-element.elementor-element-3156738 .ee-hotspot{opacity:1;}.elementor-5216 .elementor-element.elementor-element-3156738 .ee-hotspot:hover .ee-hotspot__wrapper{opacity:1;transform:scale(1);}.ee-tooltip.ee-tooltip-3156738.to--top,
							 .ee-tooltip.ee-tooltip-3156738.to--bottom{margin-left:0px;}.ee-tooltip.ee-tooltip-3156738.to--left,
							 .ee-tooltip.ee-tooltip-3156738.to--right{margin-top:0px;}.elementor-5216 .elementor-element.elementor-element-fb27377 .elementor-spacer-inner{height:20px;}.elementor-5216 .elementor-element.elementor-element-8a27132{text-align:center;}.elementor-5216 .elementor-element.elementor-element-8a27132 .elementor-repeater-item-992f835{left:38.1%;top:24.2%;}.elementor-5216 .elementor-element.elementor-element-8a27132 .elementor-repeater-item-8a30473{left:73.9%;top:70.5%;}.ee-tooltip.ee-tooltip-8a27132:after{content:"";}.ee-tooltip.ee-tooltip-8a27132.to--top,
						 .ee-tooltip.ee-tooltip-8a27132.to--bottom{margin-left:0px;}.ee-tooltip.ee-tooltip-8a27132.to--left,
						 .ee-tooltip.ee-tooltip-8a27132.to--right{margin-top:0px;}.ee-tooltip.ee-tooltip-8a27132{width:200px;z-index:999;}.elementor-5216 .elementor-element.elementor-element-8a27132 .ee-hotspots img{opacity:1;}.elementor-5216 .elementor-element.elementor-element-8a27132 .ee-hotspot__wrapper{border-radius:100px;transform:scale(1);}.elementor-5216 .elementor-element.elementor-element-8a27132 .ee-hotspot__wrapper:before{border-radius:100px;}.elementor-5216 .elementor-element.elementor-element-8a27132 .ee-hotspot{opacity:1;}.elementor-5216 .elementor-element.elementor-element-8a27132 .ee-hotspot:hover .ee-hotspot__wrapper{opacity:1;transform:scale(1);}.ee-tooltip.ee-tooltip-8a27132.to--top,
							 .ee-tooltip.ee-tooltip-8a27132.to--bottom{margin-left:0px;}.ee-tooltip.ee-tooltip-8a27132.to--left,
							 .ee-tooltip.ee-tooltip-8a27132.to--right{margin-top:0px;}.elementor-5216 .elementor-element.elementor-element-fabeb18{text-align:center;}.elementor-5216 .elementor-element.elementor-element-fabeb18 .elementor-repeater-item-552ae35{left:26.2%;top:17.5%;}.elementor-5216 .elementor-element.elementor-element-fabeb18 .elementor-repeater-item-407783d{left:57.3%;top:55.3%;}.ee-tooltip.ee-tooltip-fabeb18:after{content:"";}.ee-tooltip.ee-tooltip-fabeb18.to--top,
						 .ee-tooltip.ee-tooltip-fabeb18.to--bottom{margin-left:0px;}.ee-tooltip.ee-tooltip-fabeb18.to--left,
						 .ee-tooltip.ee-tooltip-fabeb18.to--right{margin-top:0px;}.ee-tooltip.ee-tooltip-fabeb18{width:200px;z-index:999;}.elementor-5216 .elementor-element.elementor-element-fabeb18 .ee-hotspots img{opacity:1;}.elementor-5216 .elementor-element.elementor-element-fabeb18 .ee-hotspot__wrapper{border-radius:100px;transform:scale(1);}.elementor-5216 .elementor-element.elementor-element-fabeb18 .ee-hotspot__wrapper:before{border-radius:100px;}.elementor-5216 .elementor-element.elementor-element-fabeb18 .ee-hotspot{opacity:1;}.elementor-5216 .elementor-element.elementor-element-fabeb18 .ee-hotspot:hover .ee-hotspot__wrapper{opacity:1;transform:scale(1);}.ee-tooltip.ee-tooltip-fabeb18.to--top,
							 .ee-tooltip.ee-tooltip-fabeb18.to--bottom{margin-left:0px;}.ee-tooltip.ee-tooltip-fabeb18.to--left,
							 .ee-tooltip.ee-tooltip-fabeb18.to--right{margin-top:0px;}.elementor-5216 .elementor-element.elementor-element-e99842d .elementor-spacer-inner{height:20px;}.elementor-5216 .elementor-element.elementor-element-a4d8d5c{text-align:center;}.elementor-5216 .elementor-element.elementor-element-a4d8d5c .elementor-repeater-item-c032717{left:22.8%;top:50%;}.elementor-5216 .elementor-element.elementor-element-a4d8d5c .elementor-repeater-item-8ccc97d{left:65.2%;top:59.9%;}.ee-tooltip.ee-tooltip-a4d8d5c:after{content:"";}.ee-tooltip.ee-tooltip-a4d8d5c.to--top,
						 .ee-tooltip.ee-tooltip-a4d8d5c.to--bottom{margin-left:0px;}.ee-tooltip.ee-tooltip-a4d8d5c.to--left,
						 .ee-tooltip.ee-tooltip-a4d8d5c.to--right{margin-top:0px;}.ee-tooltip.ee-tooltip-a4d8d5c{width:200px;z-index:999;}.elementor-5216 .elementor-element.elementor-element-a4d8d5c .ee-hotspots img{opacity:1;}.elementor-5216 .elementor-element.elementor-element-a4d8d5c .ee-hotspot__wrapper{border-radius:100px;transform:scale(1);}.elementor-5216 .elementor-element.elementor-element-a4d8d5c .ee-hotspot__wrapper:before{border-radius:100px;}.elementor-5216 .elementor-element.elementor-element-a4d8d5c .ee-hotspot{opacity:1;}.elementor-5216 .elementor-element.elementor-element-a4d8d5c .ee-hotspot:hover .ee-hotspot__wrapper{opacity:1;transform:scale(1);}.ee-tooltip.ee-tooltip-a4d8d5c.to--top,
							 .ee-tooltip.ee-tooltip-a4d8d5c.to--bottom{margin-left:0px;}.ee-tooltip.ee-tooltip-a4d8d5c.to--left,
							 .ee-tooltip.ee-tooltip-a4d8d5c.to--right{margin-top:0px;}.elementor-5216 .elementor-element.elementor-element-23a05d0 .elementor-spacer-inner{height:20px;}.ee-tooltip.ee-tooltip-6db990a.to--top,
							 .ee-tooltip.ee-tooltip-6db990a.to--bottom{margin-left:0px;}.ee-tooltip.ee-tooltip-6db990a.to--left,
							 .ee-tooltip.ee-tooltip-6db990a.to--right{margin-top:0px;}.elementor-5216 .elementor-element.elementor-element-cf61aaf{border-style:solid;border-width:8px 8px 8px 8px;border-color:#EEABAB;transition:background 0.3s, border 0.3s, border-radius 0.3s, box-shadow 0.3s;}.elementor-5216 .elementor-element.elementor-element-cf61aaf > .elementor-background-overlay{transition:background 0.3s, border-radius 0.3s, opacity 0.3s;}.elementor-5216 .elementor-element.elementor-element-11a8dee{text-align:center;}`

Or does anyone have an idea how I could get it?

**Comment by Kallirroi** [comment]
I think you can get that with this query: 
```
{
  posts {
    nodes {
      enqueuedStylesheets {
        nodes {
          id
          src
        }
      }
    }
  }
}
```

**Comment by mgrubiak** [comment]
> I think you can get that with this query:
> 
> ```
> {
>   posts {
>     nodes {
>       enqueuedStylesheets {
>         nodes {
>           id
>           src
>         }
>       }
>     }
>   }
> }
> ```

Unfortunately it is not set for me.
I checked under posts -> nodes and posts -> edges -> node but can't find anything saying "Stylesheet"

**Comment by TylerBarnes** [comment]
Hi @mgrubiak , I followed up in this issue about why this isn't currently available https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/110

Your issue was opened first but since I've already written a longer explanation in the other issue I'm going to close this one as a duplicate. If you click to follow that issue you'll get updates on when this will be available in this plugin.

Thanks for opening this issue and using this plugin!
