### ISSUE TITLE
the DELETE wp node action can fail if a node type is excluded

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/gatsby-source-wordpress-experimental#105]
This is because there is no saved type info for it and this action relies on that saved type info. It's actually not needed to check this type info so bypassing that will fix this potential bug.

**Comment by rodrigo-arias** [comment]
Hi @TylerBarnes 

I am using https://github.com/GatsbyWPGutenberg/gatsby-wordpress-gutenberg and I get this error only in the build process. I could not identify what it is, but I just want to know if you refer to this error in this issue.

![image](https://user-images.githubusercontent.com/11416255/89587449-04d36900-d818-11ea-9f56-55a13f50ef89.png)

Thank you

**Comment by TylerBarnes** [comment]
Hi @rodrigo-arias , I believe you're having a different issue than what this one is describing. This one happens during delta updates in gatsby-node.js and doesn't make it to the browser. It's hard to say what your issue could be without additional info or a repro 🤔

**Comment by rodrigo-arias** [comment]
Thanks for your reply. It looks like a `gatsby-source-wordpress-experimental` issue with static query. I have reported it here https://github.com/GatsbyWPGutenberg/gatsby-wordpress-gutenberg/issues/47, of course you are welcome if you have a chance to try it, I'm not sure how to identify it. Thanks again
