### ISSUE TITLE
Sorting by menuPosition query is longer than expected

### ISSUE THREAD

**Issue by emaildano** [gatsbyjs/gatsby-source-wordpress-experimental#106]
This is probably a simple answer but I'm curious if sorting by field `contentType___node___menuPosition` is a query that normally takes a long time?

Here's the query I run:

```
{
  allWpPost(sort: {order: ASC, fields: contentType___node___menuPosition}) {
    edges {
      node {
        id
        title
      }
    }
  }
}

```

If I remove the sort by menu position filter the results are instant but with the sort filter added it takes ~30s. While I'm running that query this also appears in the terminal window.

```
warn  gatsby-source-wordpress  cG9zdF90eXBlOnBvc3Q= contentType was updated, but no data
warn  gatsby-source-wordpress  cG9zdF90eXBlOnBvc3Q= contentType was updated, but no data
warn  gatsby-source-wordpress  cG9zdF90eXBlOnBvc3Q= contentType was updated, but no data
...
```

The query does return normal but it takes an unusually long time, that's all.

**Comment by TylerBarnes** [comment]
That's really odd 🤔 when I run it it resolves immediately. Are you able to share the /graphql endpoint of the site that has this issue? That'll help me understand what's going on.

Thanks!

**Comment by emaildano** [comment]
I think so. I'm working on another issue now, once that's resolved I'm back on site development. I'll test again and if it's the same I'll send it your way. Thanks!

**Comment by TylerBarnes** [comment]
Hey @emaildano did you get a chance to take a peek again?

**Comment by emaildano** [comment]
@TylerBarnes I just ran this query on the same site I had an issue with and it returned without delay. I'm going to say this is resolved. If I do run into this issue again, I'll send over my log files for review.
