### ISSUE TITLE
Where are my ACF fields?

### ISSUE THREAD

**Issue by mikedloss** [gatsbyjs/gatsby-source-wordpress-experimental#112]
I'm relatively new to Wordpress and development surrounding it. I have ACF and the 2 Wordpress plugins installed on my backend, I have gatsby-config set up to look at my Wordpress instances' graphql endpoint. I am able to query successfully to get data from it. But I don't see any of my ACF data in GraphiQL. I've searched by field name, looked through many fields, but just can't find any of my ACF data.

Where does it live? Do I need to do anything to get my ACF data to show up?

**Comment by stefanmomm** [comment]
Did you install the [WPGraphQL for Advanced Custom Fields](https://www.wpgraphql.com/acf/) plugin?

**Comment by mikedloss** [comment]
@stefanmomm I actually didn't know that was a plugin, so I just installed / activated it, and I see it now as a field in my node. Thank you!
