### ISSUE TITLE
GraphQL query for filtering menuItems on wpMenu not working

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [gatsbyjs/gatsby-source-wordpress-experimental#113]
I am trying to query all the top level menu items. Within WPGraphiQL this works, but in the Gatsby GraphiQL it does not work. Below the sample queries I used.

WPGraphiQL plugin query:
```
query menus {
  menus(where: {location: MAIN_MENU}) {
    nodes {
      menuItems(where: {parentDatabaseId: 0}) {
        nodes {
          url
          label
          parentDatabaseId
        }
      }
    }
  }
}
```

Which indeed returns only top level menu items.

Gatsby GraphiQL query:
```
query menus {
  wpMenu(locations: {eq: MAIN_MENU}, menuItems: {nodes: {elemMatch: {parentDatabaseId: {eq: 0}}}}) {
    menuItems {
      nodes {
        label
        path
        parentDatabaseId
      }
    }
  }
}
```

Which returns all items including sub items.

**Comment by TylerBarnes** [comment]
Hi @pepijn-vanvlaanderen , can you share a reproduction repo with a GraphQL api I can use to debug? That'd be super helpful :) thanks!

**Comment by teetl6** [comment]
@pepijn-vanvlaanderen Did you find the solution for that problem? I have tried everything to get data for menu, but everything works in WPGraphql but not working in NextJS any more. What would be the proper query? I've read a lot of samples but none of them are working.

**Comment by TylerBarnes** [comment]
Hi, just had another look at this - the reason is that we haven't yet implemented filters on sub-fields that are node connections. You can achieve what you're looking to do like this:

```graphql
query menus {
  allWpMenuItem(filter: {locations: {eq: GATSBY_PRIMARY_MENU}, parentDatabaseId: {eq: 0}}) {
      nodes {
        label
        path
        parentDatabaseId
        childItems {
          nodes {
            id
          }
        }
      }
    }
}

```
