### ISSUE TITLE
As anyone been able to get post by ID?

### ISSUE THREAD

**Issue by DesignerKnowsFrontEnd** [gatsbyjs/gatsby-source-wordpress-experimental#115]
I'm having issues with querying the post template to find the individual post I've tried by filtering by ID and and using the old way getting the post ID but now of those methods seem to work.

Also tried looking for more documentation but seems it hasn't been updated yet.

tried:

query post {
  wpPost(id: {eq: "$ID"}) {
    uri
    title
    date
    id
  }
}

And 

  query post($id: ID!) {
    wpPost(id: $id) {
      uri
      title
      date
      id
    }
  }

but still having issues, as anyone else got a solution or know's where am going wrong??

**Comment by TylerBarnes** [comment]
Hi @DesignerKnowsFrontEnd ,
you're really close! The correct syntax is a mix of the two.

```graphql
query post($id: ID!) {
  wpPost(id: { eq: $id }) {
    uri
    title
    date
    id
  }
}
```

Then you need to pass in `id` to pageContext when you create pages.

**Comment by DesignerKnowsFrontEnd** [comment]
Agh ok,

Does that work when testing it in the graphiql ui? as that may have been the reason why i think it wasn't working.

Thanks anyways.

**Comment by TylerBarnes** [comment]
It does :) You have to make sure to add some JSON to the "query variables" section in the bottom left.
So in this case you would add something like:

```JSON
{
  "id": "jkljh17df7s"
}
```

**Comment by DesignerKnowsFrontEnd** [comment]
Hey Tyler ,

Thanks but im still having issues with it as I have this error now

D:\Work\Gatsby_Lellos_github\src\templates\post.js
  6:13  error  Variable "$id" of type "ID!" used in position expecting type "String"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


File: src\templates\post.js

failed Re-building development bundle - 0.262s.

here is my query: 

} export const query = graphql`
 query post($id: ID!) {
  wpPost(id: { eq: $id }) {
    uri
    title
    date
    id
  }
}

`;

He So I want my posts to dynamically change by ID and on the old WordPress source plugin I had that working. Do I have to change anything form my Gatsby-node.js file?

Here what that looks like. 

const path = require(`path`);
const { slash } = require(`gatsby-core-utils`);

// Implement the Gatsby API “createPages”. This is
// called after the Gatsby bootstrap is finished so you have
// access to any information necessary to programmatically
// create pages.
// Will create pages for WordPress pages (route : /{slug})
// Will create pages for WordPress posts (route : /post/{slug})
exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions;

  // The “graphql” function allows us to run arbitrary
  // queries against the local Gatsby GraphQL schema. Think of
  // it like the site has a built-in database constructed
  // from the fetched data that you can run queries against.
  const result = await graphql(`
    {
      allWpPost {
        nodes {
          id
          uri
        }
      }
      allWpPage {
        nodes {
          id
          uri
        }
      }
    }
  `);

  // Check for any errors
  if (result.errors) {
    throw new Error(result.errors);
  }

  // Access query results via object destructuring
  const pages = result.data.allWpPage.nodes;

  const pageTemplate = path.resolve(`./src/templates/page.js`);
  // We want to create a detailed page for each post node.
  // The path field stems from the original WordPress link
  // and we use it for the slug to preserve url structure.
  // The Post ID is prefixed with 'POST_'
  pages.forEach((page) => {
    actions.createPage({
      path: `${page.uri}`,
      component: require.resolve(pageTemplate),
      context: {
        id: page.id,
      },
    });
  });

  // Access query results via object destructuring
  const posts = result.data.allWpPost.nodes;

  const postTemplate = path.resolve(`./src/templates/post.js`);
  // We want to create a detailed page for each post node.
  // The path field stems from the original WordPress link
  // and we use it for the slug to preserve url structure.
  // The Post ID is prefixed with 'POST_'
  posts.forEach((post) => {
    actions.createPage({
      path: `our-news${post.uri}`,
      component: require.resolve(postTemplate),
      context: {
        id: post.id,
      },
    });
  });
};

const path = require(`path`);
const { slash } = require(`gatsby-core-utils`);

// Implement the Gatsby API “createPages”. This is
// called after the Gatsby bootstrap is finished so you have
// access to any information necessary to programmatically
// create pages.
// Will create pages for WordPress pages (route : /{slug})
// Will create pages for WordPress posts (route : /post/{slug})
exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions;

  // The “graphql” function allows us to run arbitrary
  // queries against the local Gatsby GraphQL schema. Think of
  // it like the site has a built-in database constructed
  // from the fetched data that you can run queries against.
  const result = await graphql(`
    {
      allWpPost {
        nodes {
          id
          uri
        }
      }
      allWpPage {
        nodes {
          id
          uri
        }
      }
    }
  `);

  // Check for any errors
  if (result.errors) {
    throw new Error(result.errors);
  }

  // Access query results via object destructuring
  const pages = result.data.allWpPage.nodes;

  const pageTemplate = path.resolve(`./src/templates/page.js`);
  // We want to create a detailed page for each post node.
  // The path field stems from the original WordPress link
  // and we use it for the slug to preserve url structure.
  // The Post ID is prefixed with 'POST_'
  pages.forEach((page) => {
    actions.createPage({
      path: `${page.uri}`,
      component: require.resolve(pageTemplate),
      context: {
        id: page.id,
      },
    });
  });

  // Access query results via object destructuring
  const posts = result.data.allWpPost.nodes;

  const postTemplate = path.resolve(`./src/templates/post.js`);
  // We want to create a detailed page for each post node.
  // The path field stems from the original WordPress link
  // and we use it for the slug to preserve url structure.
  // The Post ID is prefixed with 'POST_'
  posts.forEach((post) => {
    actions.createPage({
      path: `our-news${post.uri}`,
      component: require.resolve(postTemplate),
      context: {
        id: post.id,
      },
    });
  });
};



I would really appreciate your insight for this.

**Comment by TylerBarnes** [comment]
Hey again, the problem here is at the top of the error message:
`6:13 error Variable "$id" of type "ID!" used in position expecting type "String" graphql/template-strings`

What you want to do is type the $id variable as a String
```graphql
query post($id: String!) {
  wpPost(id: { eq: $id }) {
    uri
    title
    date
    id
  }
}
```

**Comment by DesignerKnowsFrontEnd** [comment]
ok that defo worked like a treat. thanks for all your help man. do you when there be any updated docs or more info working with the source plugin etc??

**Comment by TylerBarnes** [comment]
I'm off today and tomorrow but @jasonbahl and I are planning to do a bunch of work on docs for this project & WPGraphQL on monday/tuesday

**Comment by TylerBarnes** [comment]
Were there any other parts of the docs that got you hung up?
