### ISSUE TITLE
Feature request: "Not all media is being fetch from the WordPress server", add option to source unreferenced media items

### ISSUE THREAD

**Issue by SilencerWeb** [gatsbyjs/gatsby-source-wordpress-experimental#117]
We have 44 media items in our WordPress server but only 35 are being fetched to frontend.

The strange thing that some of the missing images were fetched before but stopped after a few more uploads to Media Library in WordPress. My guess is that `gatsby-source-wordpress-experimental` is somehow trying to analyze which images are being used and which are not so it could fetch only the ones that are being used but its algorithm fails for some images.

Here is plugin configuration, nothing special as you can see:
```js
{
  resolve: `gatsby-source-wordpress-experimental`,
  options: {
    url: process.env.WP_GRAPHQL_URL,
    auth: {
      htaccess: {
        username: process.env.WP_HTACESS_USERNAME,
        password: process.env.WP_HTACESS_PASSWORD,
      },
    },
  },
},
```

A query we ran to fetch items:
```graphql
{
  allWpMediaItem {
    totalCount
  }
}
```

Response:
```json
{
  "data": {
    "allWpMediaItem": {
      "totalCount": 35
    }
  },
  "extensions": {}
}
```

Versions:
- gatsby — 2.24.42
- gatsby-source-wordpress-experimental — 1.3.3
- WP Gatsby — 0.4.16
- WP GraphiQL — 1.0.1
- WP GraphQL — 0.12.0

Feel free to ask any additional information if required!

**Comment by SilencerWeb** [comment]
As turned out, it is not a bug but a feature.

Would be awesome to have an option to turn off this behavior 🙂

Would be even more awesome to have an ability to specify URLs to images that should be fetched anyway in order to prevent downloading all other unneeded images

**Comment by TylerBarnes** [comment]
Thanks for the request @SilencerWeb ! This is a totally valid and needed option and we'll be able to add this once v4 is released.

**Comment by TylerBarnes** [comment]
@SilencerWeb this is definitely a valid and needed feature but I'm curious what your specific use-case is. Can you elaborate a bit?

**Comment by SilencerWeb** [comment]
Hey @TylerBarnes!

We have a website with blog posts and we needed to show avatars of the persons who created these posts. We tried to use WordPress plugins for setting avatars to users. But the images were not processed, we could access them inside `avatar` but there was only a `sourceUrl`. So we decided to use this `sourceUrl` to get the needed item in `wpMediaItem` but we couldn't because they were not there since they are not connected to any node.

In the end, we decided to use ACF for this:

![image](https://user-images.githubusercontent.com/20713191/93736188-f4752300-fbf8-11ea-846a-4cec8805d279.png)

**Comment by TylerBarnes** [comment]
@SilencerWeb the reason for that is that the source plugin only processes MediaItems and avatar's are external images. Follow https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/67 for avatar processing :)

**Comment by shawngrona** [comment]
@SilencerWeb i describe the approach i'll use here https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/67#issuecomment-714616788

**Comment by smthomas** [comment]
Thank you for opening this issue. We recently moved this plugin over to the gatsbyjs monorepo and are trying to clean out this issue queue. We documented this feature to look at for a future roadmap item and are going to close this issue out. If you want to add additional visibility to this feature, you can request it at https://portal.gatsbyjs.com/
