### ISSUE TITLE
Cannot read property 'pages' of undefined - ERROR

### ISSUE THREAD

**Issue by oliverfeher** [gatsbyjs/gatsby-source-wordpress-experimental#118]
Hey, I was wondering if anybody has gotten this error when running `gatsby develop` ?

```
ERROR 
Cannot read property 'pages' of undefined
  TypeError: Cannot read property 'pages' of undefined
  - fetch-nodes-paginated.js:80 paginatedWpNodeFetch
    [ma-fe]/[gatsby-source-wordpress-experimental]/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js:80:12
  - runMicrotasks
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
  - fetch-nodes.js:61 fetchWPGQLContentNodes
    [ma-fe]/[gatsby-source-wordpress-experimental]/steps/source-nodes/fetch-nodes/fetch-nodes.js:61:24
  - fetch-nodes.js:159 
    [ma-fe]/[gatsby-source-wordpress-experimental]/steps/source-nodes/fetch-nodes/fetch-nodes.js:159:32
  - async Promise.all
  - fetch-nodes.js:152 fetchWPGQLContentNodesByContentType
    [ma-fe]/[gatsby-source-wordpress-experimental]/steps/source-nodes/fetch-nodes/fetch-nodes.js:152:5
  - fetch-nodes.js:198 fetchAndCreateAllNodes
    [ma-fe]/[gatsby-source-wordpress-experimental]/steps/source-nodes/fetch-nodes/fetch-nodes.js:198:35
  - index.js:44 sourceNodes
    [ma-fe]/[gatsby-source-wordpress-experimental]/steps/source-nodes/index.js:44:5
  - run-steps.js:23 runSteps
    [ma-fe]/[gatsby-source-wordpress-experimental]/utils/run-steps.js:23:7
 ERROR 
 gatsby-source-wordpress 
        Encountered a critical error when running the sourceNodes.sourceNodes build step.
```

This is my current `gatsby-config` with enabled `debug options`:

```
{
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: `https://dev-mattressadvisor.pantheonsite.io/graphql`,
        debug: {
          graphql: {
            showQueryVarsOnErrors: true,
            writeQueriesToDisk: true,
          }
        },
        type: {
          Comment: {
            limit: process.env.NODE_ENV === `development` ? 50 : 5000,
          },
          Post: {
            limit: process.env.NODE_ENV === `development` ? 500 : 5000,
          }
        },
      },
    },
```

**Comment by oliverfeher** [comment]
I also fried up a fresh project with `gatsby new wordpress-gatsby https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental` and replaced the default URL to mine like this:

{
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url:
          process.env.WPGRAPHQL_URL ||
          `https://dev-mattressadvisor.pantheonsite.io/graphql`,
        verbose: true,
        develop: {
          hardCacheMediaFiles: true,
        },
        debug: {
          graphql: {
            writeQueriesToDisk: true,
          },
        },
        type: {
          Post: {
            limit:
              process.env.NODE_ENV === `development`
                ? // Lets just pull 50 posts in development to make it easy on ourselves.
                  50
                : // and we don't actually need more than 5000 in production for this particular site
                  5000,
          },
        },
      },
    },

Encountered the same error, however it was switching between these:
`Cannot read property 'posts' of undefined`
`Cannot read property 'comments' of undefined`
`Cannot read property 'pages' of undefined`

Got this one everytime:
`Encountered a critical error when running the sourceNodes.sourceNodes build step.`

**Comment by TylerBarnes** [comment]
Hi @oliverfeher !
Thanks for your patience on this. I just had a look and it seems to be the same error we talked about a few weeks back. The page with an database id of 608 has a filter on the post content which is causing WPGraphQL to return an empty string.

You can make this query via Graphiql (directly to yoursite.com/graphql) to see this problem

```graphql
{
  page(id: 608 idType: DATABASE_ID) {
    content
  }
}
```

If you query for content it causes the whole request to return an empty string instead of a GraphQL response. The same seems to happen for a post (not sure which post). It would likely be the same filter causing the problem in both places.

Upgrade to `gatsby-source-wordpress-experimental@1.3.6` for a better error message.

I'm currently brainstorming on how these problematic nodes could be automatically identified but I don't have a concrete answer for that yet.

**Comment by TylerBarnes** [comment]
For now you can get your build running with this config:

```js
{
    resolve: `gatsby-source-wordpress-experimental`,
    options: {
        url: `https://dev-mattressadvisor.pantheonsite.io/graphql`,
        debug: {
            graphql: {
                showQueryVarsOnErrors: true,
                writeQueriesToDisk: true,
            }
        },
        type: {
            Comment: {
                limit: process.env.NODE_ENV === `development` ? 50 : 5000,
            },
            Post: {
                limit: process.env.NODE_ENV === `development` ? 500 : 5000,
                excludeFieldNames: [`content`],
            },
            Page: {
                excludeFieldNames: [`content`],
            },
            NodeWithContentEditor: {
                exclude: true,
            },
        },
    },
},
```
