### ISSUE TITLE
How to understand which images are being processed and which are not?

### ISSUE THREAD

**Issue by SilencerWeb** [gatsbyjs/gatsby-source-wordpress-experimental#120]
We use plugin [Lazy Blocks](https://wordpress.org/plugins/lazy-blocks) to create custom blocks that in the future will be used for creating content for pages. We have an image in one of our blocks but it isn't being converted into Gatsby Image. It is just an `img` with a link to the image (that is hosted on WordPress, not somewhere else), e.g. `<img src="https://wp.domain.com/wp-content/uploads/2020/08/background-image-scaled.jpg" alt="">`

**Comment by TylerBarnes** [comment]
Hey @SilencerWeb sounds like this is a documentation issue but also might be a bug too. Can you share a reproduction or send me a GraphQL API url that I can use to reproduce?

Thanks!

**Comment by SilencerWeb** [comment]
Hi @TylerBarnes!

Honestly, I don't remember what was the problem. But as I remember, in the end, everything started working okay so let's close it for now
