### ISSUE TITLE
Enum types not showing in GraphQL

### ISSUE THREAD

**Issue by nunof07** [gatsbyjs/gatsby-source-wordpress-experimental#121]
One of the settings from Yoast SEO that is registered by [wp-graphql-yoast-seo](https://github.com/ashhitch/wp-graphql-yoast-seo) as an enum is not showing up in Gatsby's GraphQL despite having a value.

The following works when queried in WP GraphiQL or in a GraphQL IDE connected to the WordPress site:

```graphql
{
  seo {
    social {
      twitter {
        cardType
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/13945913/90113427-4187ee80-dd49-11ea-9f27-29d62d23f853.png)

However the field doesn't show up in Gatsby's GraphQL.

```graphql
query MyQuery {
  wp {
    seo {
      social {
        twitter {
          cardType
        }
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/13945913/90113412-38971d00-dd49-11ea-9aba-3ff862f0a2c5.png)

Other fields from Yoast SEO appear properly.

The setting can be found in Yoast SEO's Social settings:

![image](https://user-images.githubusercontent.com/13945913/90113541-69775200-dd49-11ea-8850-7704ccc083ed.png)

See related issue: https://github.com/ashhitch/wp-graphql-yoast-seo/issues/58 and comment: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/111#issuecomment-672687447

**Comment by TylerBarnes** [comment]
This is fixed in `gatsby-source-wordpress-experimental@1.3.8`. Thanks for the report!
