### ISSUE TITLE
Excerpt no longer populated

### ISSUE THREAD

**Issue by robmarshall** [gatsbyjs/gatsby-source-wordpress-experimental#124]
I am not sure what has caused it, but since updating two of my sites the excerpt field within posts object passed back from graphql is empty. 

I am running the most recent WordPress: 5.4,  gatsby-source-wordpress-experimental: 1.3.4 and graph-source-ql:2.7.1

WordPress plugins are: wp Gatsby: 0.4.16, wp graphql: 0.4.16

The an example repo: https://github.com/robmarshall/tns-gatsby

I have had to use content as a fix.

**Comment by deadband** [comment]
I am experiencing this same issue after updating WordPress to version 5.5, resulting in excerpts coming back empty in graphiql. However, when I downgraded to 5.4.2 and even 5.4.1, excerpts were then successfully queried within graphiql. Strangely, they still show up undefined within my project, but I believe that is something within the code and not related.

**Comment by TylerBarnes** [comment]
Hey this is a WP core bug. Check out this WPGQL issue comment explaining things https://github.com/wp-graphql/wp-graphql/issues/1430#issuecomment-675548552. Closing as upstream.
