### ISSUE TITLE
The comments in `building-a-new-site-wordpress-and-gatsby.md` don't work in JSX

### ISSUE THREAD

**Issue by petercr** [gatsbyjs/gatsby-source-wordpress-experimental#126]
Hello 👋  **really cool project** you have going here. 

There were some problems with the comments in the JSX sections in:
> `docs/tutorials/building-a-new-site-wordpress-and-gatsby.md`

I went ahead and made a PR with the fixes for it. #125 

Basically, the comments were regular JS comments `// comment `  and not JSX comments `{/* comment */}`. 
But they occurred while inside of a `render`.
Don't worry we all do it every once in a while 😅

**Comment by TylerBarnes** [comment]
Merged the PR, thanks again! Really appreciate your help
