### ISSUE TITLE
Missing children on Pages

### ISSUE THREAD

**Issue by ashhitch** [gatsbyjs/gatsby-source-wordpress-experimental#127]
Hey,
When ruing a query for child pages nothing gets returned in Gatsby. 

When I do the following query direct in wpGraphQl:

```
query MyQuery {
  page(id: "cG9zdDoxOTA0", idType: ID) {
    title
     uri
    children {
      nodes {
        ... on Page {
          title
          uri
        }
      }
    }
  }
}
```

I get all of the sub/ child pages returned in the the array.

However when I make the equivalent query in gatsby:
```
 query GET_PAGE($id: String!) {
 wpPage(id: { eq: $id }) {
            title
            uri
            children {
                ... on WpPage {
                   title
                   uri
                }
            }
}
```
Then I only get the top-level page data, and the children array is always empty.

Let me know if an endpoint would be helpful.

**Comment by jasonbahl** [comment]
@ashhitch Thanks for opening and providing details. An endpoint and what versions of all involved plugins in use on the Gatsby and WP side would definitely be helpful so we can reproduce. 🙏

**Comment by ashhitch** [comment]
@jasonbahl @TylerBarnes  
These are the relevant plugins:
gatsby-source-wordpress-experimental: 1.3.6
Wp Gatsby 0.4.16
WpGraphql 0.10.3

The endpoint is private but can slack you the link.

**Comment by carlbradbury79** [comment]
Hey

Getting the same issue with not only the children on pages, but parents too.

**Comment by integrate-your-mind** [comment]
Hi I am also receiving the error "TypeError: Cannot read property 'pages' of undefined" when loading from the Gatsby template.

I went through these debugging steps with no success, I even tried lowering the query to 1 page and it still failed.

Really strange, I am going to try reverting back to the non-experimental plugin for now.

**Comment by TylerBarnes** [comment]
Hey everyone, `children` and `parent` are used within Gatsby differently than in WPGraphQL and so are treated as reserved field names. Those are Gatsby node parent and children. For any field name treated as reserved, I've prefixed the field name with `wp` automatically. So you're looking for `wpChildren` and `wpParent` instead. Let me know if that solves the issue for you. I'm planning on revisiting this to see if there's a way to keep the field names the same but I'm not totally sure as of this moment and need to do some checking on the performance implications here.

**Comment by ashhitch** [comment]
@TylerBarnes thanks for clearing this up wpChildren was what i needed
