### ISSUE TITLE
WP Menu pulls in full URL for menu items in production

### ISSUE THREAD

**Issue by comrx** [gatsbyjs/gatsby-source-wordpress-experimental#13]
Hi! Awesome work on this plugin!

I'm running into an issue where when I try querying the allWpMenu and it returns a full absolute url (ex. `https://sitename.com/page-1`) instead of a relative one (ex. `/page-1`). I was wondering if there was any string replacement function that could run during build time, like `gatsby-source-wordpress` has:

```
// Search and Replace Urls across WordPress content.
        searchAndReplaceContentUrls: {
          sourceUrl: "https://source-url.com",
          replacementUrl: "https://replacement-url.com",
        }
```

This only seems to happen when I use WP on our staging server, and not when I'm running it locally.

I've added in a little `.replace()` function to help, but it doesn't seem like the cleanest solution.

Thanks!

**Comment by TylerBarnes** [comment]
@comrx that makes me think your staging site was deployed with some wrong links. There's a find/replace built in (if you're on the latest version) which uses the WP base url from settings to do the finding. Are you on the latest?
I've seen this happen before and it was from a migration that didn't have http vs https right in the links.

**Comment by TylerBarnes** [comment]
I guess I could probably protect against that by searching for http and https 🤔

**Comment by comrx** [comment]
@TylerBarnes,

That's it! My `site_url` was set to http on the WP staging site 😅 It works flawlessly now.

Thank you!
