### ISSUE TITLE
Gatsby-image feature fails inside WYSIWYG/post

### ISSUE THREAD

**Issue by garryburch** [gatsbyjs/gatsby-source-wordpress-experimental#130]
When using offsite storage locations such as AWS the gatsby-image feature fails inside ACF/WYSIWYG

It does bring back the image and scrset yet as WP would hand them off - not ran through the gatsby-image-source like it does on our other sites that use local storage.

System:
    OS: Linux 5.4 KDE neon 5.19
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.22.0/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.23.6 => 2.24.47
    gatsby-cli: ^2.12.47 => 2.12.87
    gatsby-image: ^2.4.7 => 2.4.16
    gatsby-plugin-antd: ^2.2.0 => 2.2.0
    gatsby-plugin-canonical-urls: ^2.3.4 => 2.3.10
    gatsby-plugin-force-trailing-slashes: ^1.0.4 => 1.0.4
    gatsby-plugin-google-analytics: ^2.3.4 => 2.3.13
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.4.12 => 2.4.23
    gatsby-plugin-netlify: ^2.3.5 => 2.3.13
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.10
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1
    gatsby-plugin-sharp: ^2.6.12 => 2.6.27
    gatsby-plugin-sitemap: ^2.4.5 => 2.4.11
    gatsby-plugin-styled-components: ^3.3.4 => 3.3.10
    gatsby-source-filesystem: ^2.3.12 => 2.3.24
    gatsby-source-ghost: ^3.5.1 => 3.5.1
    gatsby-source-lever: ^2.3.5 => 2.3.11
    gatsby-source-wordpress-experimental: ^1.2.2 => 1.3.6
    gatsby-transformer-sharp: ^2.5.5 => 2.5.13
  npmGlobalPackages:
    gatsby-cli: 2.12.87

**Comment by pepijn-vanvlaanderen** [comment]
+1 also using offsite media storage and would like to see gatsby to handle the images. 

Also remarkable is that when I had all assets stateless in google cloud storage and not present in the CMS (thus leading to 404s) the images would be loaded by Gatsby somehow, I guess through the fetched MediaItems.

**Comment by TylerBarnes** [comment]
Hey @garryburch , this is a good request and we need more options around how gatsby-image and CDN's are used by this plugin. For now we're working on getting the basic core features stable, then additional features like this will be prioritized.
Thanks for raising this!

**Comment by TylerBarnes** [comment]
I've moved this to our feature request portal https://portal.gatsbyjs.com/gatsby-cloud/p/gatsby-source-wordpress-allow-non-wp-hosted-images-in-html thanks again for suggesting this! If you still feel like this would be an important feature please visit that url and upvote it. Thanks!
