### ISSUE TITLE
Request for clarification: how to refresh local schema when schema changes on server?

### ISSUE THREAD

**Issue by benknight** [gatsbyjs/gatsby-source-wordpress-experimental#138]
Let's say I add a new field to my WordPress GraphQL schema, for example using the ACF plugin to add a new field.

Based on my observations, it appears necessary to exit development mode, run `npm run clean` to clear the local cache, and restart in dev mode from scratch. Is that correct?

**Comment by peteluffman** [comment]
Would also love to know this, i've been having to do the same. It becomes a right pain when you start having a reasonable amount of images that need to be rebuilt due to the cache being cleared.

**Comment by SilencerWeb** [comment]
That's true, it is indeed not really convenient to restart the server every time the field was added/deleted somewhere. By the way, as I know, cleaning cache is not required in such case

Also, I have to restart the server almost every time I change the branch :(

**Comment by TylerBarnes** [comment]
As of `gatsby-source-wordpress-experimental@v3.0.3` the schema updates automatically in development. Let me know if you run into any issues with it!
