### ISSUE TITLE
Can't query allWpSimpleProduct in gatsby-node

### ISSUE THREAD

**Issue by asader** [gatsbyjs/gatsby-source-wordpress-experimental#14]
Can't query allWpSimpleProduct in gatsby-node, but it's available in http://localhost:8000/___graphql. All what i can use is allWpProduct.

**Comment by TylerBarnes** [comment]
Hi @asader , we currently haven't tested wp-graphql-woocommerce with this plugin. I'm working on better documentation right now which outlines which WPGraphQL extensions are currently supported to make this clearer.
In any case if you're able to provide a minimal reproduction of the problem I'll be able to take a look.

Thanks!

**Comment by TylerBarnes** [comment]
Hi @asader , as mentioned we haven't tested Woo with this plugin yet so it's unsupported for now. Please open a new issue or reopen this issue (if you're able to) once you can share a minimal reproduction repo.

Thanks again!
