### ISSUE TITLE
Document "WooCommerce request failed with status code 500", server is overwhelmed by requests

### ISSUE THREAD

**Issue by ErnestTeluk** [gatsbyjs/gatsby-source-wordpress-experimental#143]
hello, i have a problem with launching the project, when i hit `gatsby develop` i have an error 
` ERROR 
gatsby-source-wordpress  Request failed with status code 500
error occured while fetching nodes of the "PaColorName" type.`

but my query on wordpress works [
![image](https://user-images.githubusercontent.com/49727996/91851408-63e19d80-ec5f-11ea-94f7-cad82b1dc878.png)
](url)

**Comment by TylerBarnes** [comment]
Hi @ErnestTeluk , the wp-graphql-woocommerce schema isn't fully supported yet. However, this appears to be a problem with your server being overwhelmed by all the GraphQL requests that are being made. Try following the steps here https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/debugging-and-troubleshooting.md#node-sourcing-timeouts to see if it resolves your issue. In the future this will be auto-detected by this plugin but for now manual configuration is required.

**Comment by ErnestTeluk** [comment]
hi @TylerBarnes . I found the source of the problem which was ovh (hosting provider) which banned the address for too many inquiries. I solve the problem hosting wordpress on docker
