### ISSUE TITLE
Fetched content is different from source content

### ISSUE THREAD

**Issue by MKlblangenois** [gatsbyjs/gatsby-source-wordpress-experimental#144]
# Expected Behavior

Getting the same data in WordPress GraphiQL and Gatsby

# Current Behavior

The content field is different from WordPress and Gatsby (and seem to be mixed)

- Excepted result : https://ghostbin.co/paste/ty9xo (https://ibb.co/f0bLXjb)
- Result in Gatsby : https://ghostbin.co/paste/yx7eg (https://ibb.co/MSCHjHS) 

As you can see, only content is different, only in __graphql and not in WPGraphiQL

## Steps to Reproduce

Here's a basic configuration with gatsby-source-experimental@1.3.8

https://codesandbox.io/s/gatsby-source-issue-duplicate-content-b1usu?file=/gatsby-config.js

Real content : https://studyfr.mediakod.ninja/wp-json/wp/v2/universites

NB : It's only appeared on CPT (University, the only one I've), and seem to always use the same schema of content 

# Version

Mac OS 10.5.3
Node v13.7.0
NPM v6.14.1

- "gatsby": "^2.24.50",
- "gatsby-image": "^2.4.16",
- "gatsby-plugin-manifest": "^2.4.24",
- "gatsby-plugin-offline": "^3.2.24",
- "gatsby-plugin-react-helmet": "^3.3.10",
- "gatsby-plugin-sharp": "^2.6.28",
- "gatsby-source-filesystem": "^2.3.25",
- "gatsby-source-wordpress-experimental": "^1.3.8",
- "gatsby-transformer-sharp": "^2.5.13",
- "prop-types": "^15.7.2",
- "react": "^16.12.0",
- "react-dom": "^16.12.0",
- "react-helmet": "^6.1.0"

**Comment by TylerBarnes** [comment]
This is a very strange bug. Can you share you GraphQL api url with me so I can use it to reproduce the problem? My email is tyler@gatsbyjs.com

**Comment by TylerBarnes** [comment]
Ah, no need to share it via email, I see you pasted a link to a REST route and I can access your GraphQL api from that URL. Thanks!

**Comment by TylerBarnes** [comment]
Hi @MKlblangenois I just had a look at this and this appears to not be a bug with this plugin but with your GraphQL api.
When querying for that university as a single node (the query you're executing) vs as a list of nodes (the query this plugin is executing), your API returns different content. It's likely that you're either using a plugin that interferes with WPGraphQL pagination or you have a custom filter added to your site.

I'd encourage you to open an issue in the WPGraphQL repo or ask in the WPGraphQL Slack for help on this issue.
I would guess maybe this site is using WPML which causes this problem (not 100% sure).

To verify what I just mentioned, you can follow the steps here https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/debugging-and-troubleshooting.md#missing-data-in-gatsby.

You'll see that you get differing results for the universite with id "cG9zdDo0NjU=" in WPGraphiql outside of Gatsby with

```graphql
{
  universites(first:100) {
    nodes {
      title
      content
    }
  }
}
```

vs

```graphql
{
  universite(id: "cG9zdDo0NjU=") {
      title
      content
    }
}

```

**Comment by TylerBarnes** [comment]
cc @jasonbahl
