### ISSUE TITLE
blocksJSON are messing with useGatsbyImage

### ISSUE THREAD

**Issue by petrmrkvicka** [gatsbyjs/gatsby-source-wordpress-experimental#149]
Hi all,

I am using Gutenberg as the main editor and I have lots of different innerBlocks with different attributes and it is getting too overwhelming with direct querying or fragments. I found a WP plugin [WP GraphQL Gutenberg](https://github.com/pristas-peter/wp-graphql-gutenberg) that enables me to expose Gutenberg blocks and also expose them as a stringified JSON, which is super useful for me.

However, when I am sourcing data through your plugin and have the useGatsbyImage API set to true, it returns me an error, because it also goes through the url parser (error right below).

```
url passed to create-remote-file-node is either missing or not a proper web uri: %5C%22https:%5C/%5C/...
```

I tried adding .replace with regex for backslash and double-quotes, which works, but breaks the stringified JSON response (no escaping of double quotes now).
Falsing useGatsbyImage lets me build the site, but then I cannot query the media within the blocks.
Excluding blocksJSON field name lets me build the site, but I would have to write all the fragments.

### How to reproduce
Use WP site with Gutenberg, use WP GraphQL Gutenberg plugin together with other necessary WP GraphQL plugins, use gatsby-source-wordpress-experimental in your Gatsby project with enabled useGatsbyImage, you should get an error.

### What is expected
There can be more options:
1. This plugin would skip URLs it doesn't understand (e.g. these from blocksJSON with backslashes) not return an error.
2. This plugin would clean these URLs first and would return the gatsby-image block, but would not break the stringified JSON if that's possible
3. This plugin would skip the URLs from <img> element and would look for blocks attributes.url or something similar

I am using latest versions of all plugins and Gatsby.

**Comment by jacobarriola** [comment]
Same issue is happening to me, although I'm not running the WP GraphQL Gutenberg. For now, I have to set `html.useGatsbyImage` to `false` for my build to work.

```
url passed to create-remote-file-node is either missing or not a proper web uri: %5C%22https:%5C/%5C/XXXXXX.com%5C/wp-content%5C/uploads%5C/2019%5C/11%5C/super-soft-tee-Size-chart-web-1024x350.png%5C%22
```

**Comment by rodrigo-arias** [comment]
Exactly the scenario described by @petrmrkvicka happens to me. Going back to version `1.3.1` fixed it temporarily.

**Comment by rodrigo-arias** [comment]
Hi @TylerBarnes have you had a chance to take a look? Thanks

**Comment by TylerBarnes** [comment]
Hi everyone, I've been away on vacation the last 2 weeks. I'm just sorting through all my notifications and prioritizing things now. I'll keep you posted on this issue.

**Comment by TylerBarnes** [comment]
So before I headed out for vacation I had started on writing some resolver data integrity integration tests for wp-graphql-gutenberg in Gatsby. Picked that up again yesterday evening and ran into this bug pretty quick! So I have a fix coming probably later today, just need to finish these tests and make sure nothing else is affected due to my fix.

**Comment by TylerBarnes** [comment]
A fix is published in `gatsby-source-wordpress-experimental@1.3.9`!

**Comment by rodrigo-arias** [comment]
Tested and it works, thanks!
