### ISSUE TITLE
Stop all medias to be downloading ?

### ISSUE THREAD

**Issue by JimCaignard** [gatsbyjs/gatsby-source-wordpress-experimental#150]
Hi all, 

i'm using this plugin with a large media website and so i use a CDN for all images and i'would like to 
stop downloading all the media at every build as i'm not using them at all.. 

I find the option to disable gatsby image but not to stop the downloading.. 

Ideas ?

**Comment by TylerBarnes** [comment]
Hi @JimCaignard ,
We've been talking about adding this as an option along with some additional helpers to still use the Gatsby Img React component, but nothing has materialized yet.

What you can try in the meantime to stop the downloading from happening is to override the type option on MediaItem nodes that downloads the files.

Try this
```js
{
  resolve: `gatsby-plugin-wordpress-experimental`,
  options: {
    type: {
      MediaItem: { beforeChangeNode: () => {} }
    }
  }
}
```

I'm not entirely sure if there will be any side effects to doing this, but we will definitely be adding a more official API for this after we ship the stable release of this plugin. Thanks for this feature request!

**Comment by brandensilva** [comment]
I tried the above suggestions @TylerBarnes but it doesn't seem to make a difference in my case. Is there no way to disable this so I can proceed forward with getting a build working?

**Comment by JimCaignard** [comment]
Thanks @TylerBarnes for your work and the solution you gave me ! 
It was working fine till the version 1.4.1 but now it's not working at all.. 

Any ideas or other solution to make it works again ?

**Comment by TylerBarnes** [comment]
@JimCaignard on the latest version try this config:

```
{
  resolve: `gatsby-source-wordpress-experimental`,
  options: {
    html: {
      createStaticFiles: false,
      useGatsbyImage: false,
    }
    type: {
      MediaItem: { beforeChangeNode: () => {} }
    }
  }
}
```

**Comment by JimCaignard** [comment]
@TylerBarnes it's not working :
<img width="566" alt="Capture d’écran 2020-10-09 à 12 57 49" src="https://user-images.githubusercontent.com/5680997/95575465-0a734800-0a2f-11eb-9dc6-8f541a10ac7d.png">

**Comment by TylerBarnes** [comment]
@JimCaignard if you can provide a reproduction or /graphql endpoint URL I can take a look. Thanks

**Comment by znwhite** [comment]
@TylerBarnes I am having similar issue, not sure if it's a duplicate but I've included more info: #228

**Comment by MitchEff** [comment]
I would absolutely love this. I've been trying to get it running for hours and it always fails when downloading media files. All my media is on a separate CDN too - I can't fathom why Gatsby would need to download it all.

Nothing suggested above it stopping it from doing so. It REALLY wants those images. 

For now I'm giving up and going back to trusty ol' `gatsby-source-graphql`

**Comment by TylerBarnes** [comment]
Hey everyone, I just had another look at this and you can achieve it with the following plugin options. I tested it on your endpoint @MitchEff and it works great.

```js
    {
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        // the only required plugin option for WordPress is the GraphQL url.
        url: process.env.WPGRAPHQL_URL,
        html: {
          createStaticFiles: false,
          useGatsbyImage: false,
        },
        type: {
          MediaItem: { lazyNodes: true },
        },
      },
    },
```

If you query for `MediaItem.localFile` it will fetch images, so if you don't want it to fetch images don't query for that field. Cheers :D

**Comment by TylerBarnes** [comment]
Actually, re-opening this so we can make sure we document it in our upcoming documentation push!
