### ISSUE TITLE
imageMaxWidth not passing to image wrapper

### ISSUE THREAD

**Issue by robmarshall** [gatsbyjs/gatsby-source-wordpress-experimental#151]
I am setting the following options in my config:

` html: {
        imageMaxWidth: 700,
},`

However, the wrapper div that surrounds the image is having its width set as the WordPress image size, not the config size. Meaning the image breaks out of the div. I am having to pass an !important css style to stop this.

See this article for example: https://thoughtsandstuff.com/deploy-gatsby-aws-with-ci-without-amplify
Repo: https://github.com/robmarshall/tns-gatsby/blob/master/gatsby-config.js

**Comment by TylerBarnes** [comment]
A fix for this is published in `gatsby-source-wordpress-experimental@2.1.4`. Thanks for opening this issue @robmarshall  and apologies for the lengthy delay in getting it fixed! So many competing priorities with this plugin these days 😱

**Comment by robmarshall** [comment]
@TylerBarnes Nice one! Thanks.
