### ISSUE TITLE
ACF: Gallery, only returns one image

### ISSUE THREAD

**Issue by magicspon** [gatsbyjs/gatsby-source-wordpress-experimental#156]
Heyo,

I've created an ACF gallery field, added a few images.  The field is available to graphql. However, only one image is being returned.  

Using the latest version of all the things.

When I use the grahql explorer in wordpress I can see all my images being returned.  Note I only have one page at the moment, so using the pages query for testing.

wp query
```graphql
query MyQuery {
  pages {
    nodes {
      HeroGrid {
        images {
          mediaItemUrl
        }
      }
    }
  }
}
```
returns 4 mediaItemUrls

gatsby query
```graphql
query MyQuery {
  allWpPage {
    nodes {
      HeroGrid {
        images {
          mediaItemUrl
        }
      }
    }
  }
}
```

returns just one node.

```json
{
  "data": {
    "allWpPage": {
      "nodes": [
        {
          "HeroGrid": {
            "images": [
              {
                "mediaItemUrl": "http://mysite.test/app/uploads/2020/09/demo___image3.jpg"
              }
            ]
          }
        }
      ]
    }
  },
  "extensions": {}
}
```

Any ideas...

**Comment by TylerBarnes** [comment]
Hi @magicspon, sorry for the late reply, I was out on vacation for a couple weeks. This certainly sounds like a bug. Can you share your GraphQL API url with me so I can take a look? My email is tyler@gatsbyjs.com

Thanks!

**Comment by magicspon** [comment]
Heyo.

I'm moved onto uses a repeater field.  When I get time I've recreate the issue.

ta

**Comment by TylerBarnes** [comment]
No worries @magicspon , I'll try to reproduce using the Gallery field. Thanks!

**Comment by TylerBarnes** [comment]
Hi @magicspon , this appears to be working now. Another bug fix must've fixed this since the issue was opened. If you use a gallery field again in the future and are still able to reproduce this, please re-open this issue or open a new issue. 

Thanks!

<img width="1244" alt="Screen Shot 2020-10-01 at 5 25 15 PM" src="https://user-images.githubusercontent.com/14190743/94875980-36794280-040b-11eb-9a26-5358f8cf6310.png">

**Comment by magicspon** [comment]
I can confirm it is now working as expected.
Thanks
