### ISSUE TITLE
Images not using Webp within content blocks

### ISSUE THREAD

**Issue by robmarshall** [gatsbyjs/gatsby-source-wordpress-experimental#157]
When this plugin gets content from a WordPress WYSIWYG and converts all images into Gatsby Images, it seems gatsby-image-sharp is not passed the webp value (I may be incorrect here - not fully sure on the package). This means articles are not using all that Gatsby Image has to offer. A significant SEO/page speed issue.

Is there any way I can set this? Nothing was included in the settings page for this.

Thanks,
Rob

**Comment by TylerBarnes** [comment]
Yesss this is very needed. Thanks for the feature request. I'm closing it for now as we're tracking the request over in #100

Thanks!
