### ISSUE TITLE
Gatsby Image

### ISSUE THREAD

**Issue by tjs1990-hub** [gatsbyjs/gatsby-source-wordpress-experimental#160]
localFile not returning anything and displaying as null, does anyone have a fix for this?

<img width="1425" alt="Screenshot 2020-09-17 at 19 59 51" src="https://user-images.githubusercontent.com/55842369/93515373-63fcc100-f920-11ea-8eb8-c8026b772651.png">

I also got this error message in my terminal. 

warning You can't use childImageSharp together with .jpg. — use publicURL instead. The childImageSharp portion of the query in this file will return null:
undefined

**Comment by TylerBarnes** [comment]
That's odd! Can you provide a reproduction of this so I can take a look? If your API URL is sensitive info you can email it to me at tyler@gatsbyjs.com

Thanks!

**Comment by tjs1990-hub** [comment]
Hi Tyler, thanks for coming back to me!! 

The steps to reproduce are as follows. 

Wordpress latest version (5.4)

I'm using this theme to remove the front end 

https://github.com/tomphill/wp-gatsby-js-theme-starter

The URL is https://beauty.fencingleeds.co/graphql

I am using the latest version of WPgraphql and WPgatsby

I cloned the starter from https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/getting-started.md

I did delete the templates and utils as i wanted to start again. 

I then added gatsby-image, React-bootstrap, react-render-html and removed the UI plugin you used. 

I also deleted your gatsby-node.js file. 

Hope you can help as i am a big fan of this plugin, it makes my life so much easier lol. 

Thanks again Tyler and if you need anything else you can email me at. 

thomassouth9@gmail.com

**Comment by tjs1990-hub** [comment]
Hi i have managed to get the images to show by adding 

`allFile {
            edges {
              node {
                relativePath
                name
                childImageSharp {
                  fluid(maxWidth: 1200) {
                    aspectRatio
                    src
                    srcSet
                    sizes
                    base64
                  }
                }
              }
            }
          }
         }
`

and the using useEffect to put them into state and then targeting the array. 

It's a long work around but it works. 

Will be good to hear your thoughts in how i can combat the issues with acf fields

**Comment by TylerBarnes** [comment]
Hi @tjs1990-hub , thanks for the additional information, that's really helpful!

**Comment by tjs1990-hub** [comment]
No worries @TylerBarnes if you need anything else just give me a shout, do you have a rough estimate and when the plugin will be finished yet by any chance. I have quite a few projects coming up :).

**Comment by TylerBarnes** [comment]
@tjs1990-hub I'm working towards the first stable release as fast as possible. It's hard to say exactly when it will be released as stable v4. Gatsby is working on putting additional resources into WP over the next quarter which should help

**Comment by TylerBarnes** [comment]
I went through and tagged all the issues here as to which need to be fixed before we can call things stable. You can check that out here if you're interested! https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues?q=is%3Aopen+is%3Aissue+label%3A%22address+before+stable+release%22

**Comment by tjs1990-hub** [comment]
Hey Tyler,

i really appreciate you coming back to me on this, it looks like there's
lots of work to be done. I don't envy you working with all these bugs lol.

I look forward to using this plugin.

Do you think it would be safe to use gatsby-source-wordpress or should i
take the leap to learn gatsby-source-graphql it's only for a small project.

All the best

Tom

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by TylerBarnes** [comment]
Lots of folks are using this plugin in production :) Including the Bluehost and Apollo blogs! I definitely recommend using it. There are some bugs but this plugin still offers more features and in many cases is more stable than alternatives.

**Comment by tjs1990-hub** [comment]
Cool i will keep pursuing the build and see how it goes, if i find
anything else i will let you know.

Thanks again Tyler, great speaking with you.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by TylerBarnes** [comment]
@tjs1990-hub it appears this has been fixed. Please update to latest and check if it's working for you :)

When I point my test site at your api url I see the following:

<img width="1274" alt="Screen Shot 2020-10-01 at 5 16 23 PM" src="https://user-images.githubusercontent.com/14190743/94875548-ed74be80-0409-11eb-977b-515c66ab812f.png">

Make sure you're on the latest versions of `gatsby`, `gatsby-plugin-sharp`, `gatsby-transformer-sharp`, and `gatsby-source-wordpress-experimental`.

Closing this issue for now but feel free to re-open or comment if I overlooked something and it's still not working.

**Comment by tjs1990-hub** [comment]
Hi Tyler, 

this was some good news to wake up to this morning, i can start my projects now! 

Take care and all the best.

Tom
