### ISSUE TITLE
Pantheon Demo Site no longer exists. 

### ISSUE THREAD

**Issue by rickgregory** [gatsbyjs/gatsby-source-wordpress-experimental#161]
I know that we're supposed to edit the config file to point to our own sites, but I installed this starter new and did

`gatsby develop` 

against it as a sanity check and it errors out as the site (https://dev-gatsby-source-wordpress-v4.pantheonsite.io/graphql) no longer exists.

**Comment by TylerBarnes** [comment]
Closing in favour of https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/212
