### ISSUE TITLE
Styling my Gatsby Wordpress site

### ISSUE THREAD

**Issue by MussadiqKhan** [gatsbyjs/gatsby-source-wordpress-experimental#163]
Hello @TylerBarnes ,

I normally build websites using Gatsby and headless cms like Netlify or contentful. With these cms's I have the freedom to design pages the way I want. I recently started working on Gatsby wordpress using the source-wordpress-experimental. I faced numerous issues. Now I was looking at styling my website and got stuck. I was able to fetch each and every field using graphql from other cms and style them the way I want.

However, with gatsby I do not see the option for customisation. All I see is content option in Graphql. Wordpress backend has page setup using Avada builder. Any help would be appreciated. You can take a look at about page:

My repo: https://github.com/MussadiqKhan/sl-gatsby

**Comment by TylerBarnes** [comment]
Hi @MussadiqKhan , this plugin should work the same as those other plugins. Where were you having issues with styling?

**Comment by MussadiqKhan** [comment]
If you look at the about page. I don't seem to get title, image, sub heading, description via graphql. I only see content field and it fetches the entire page with some messed up styling from wordpress. Backend has Avada builder which was used to setup the page @TylerBarnes

**Comment by TylerBarnes** [comment]
Ahh, I see what you mean. There's nothing that will enqueue WordPress styles automatically. You'll need to add those styles yourself. As far as missing fields, where are those fields coming from? Do you mean meta tags in the head? Or are those Avada fields somewhere?

**Comment by MussadiqKhan** [comment]
Okay @TylerBarnes , let me explain with an image. This is the backend. I have my about page setup using Avada Builder. As you can see there's an image, description, and then I also have Avada slider.

My question is how can I access these particular items in my front end to style them. Let say I want my image and description in one row on front end? How can I do that?

Or do I need to make my all pages using ACF instead of any builder like Elemntor, Avada etc.


![image](https://user-images.githubusercontent.com/34172073/93805454-36d24a80-fc61-11ea-97de-e82254d350af.png)

**Comment by TylerBarnes** [comment]
I'm not super familiar with Avada. Does it store those fields separately from the post content? If they're stored separately there will need to be an Avada for WPGraphQL extension created. If they're part of the html in post content, they should come across in the content field and then you can use dangerouslySetInnerHtml or something like react-html-parser to display them.

**Comment by TylerBarnes** [comment]
Using page builder plugins is something we will be focusing on at some point, but currently we're working on fully supporting any WPGraphQL enabled plugins (like ACF). However, it is something that's possible to get working currently if the page builder stores everything in post content

**Comment by MussadiqKhan** [comment]
Okay, so at this point you recommend me to focus on building pages using ACF to link with my Gatsby frontend?

**Comment by TylerBarnes** [comment]
It will certainly be a more stable path for now, but page builders could also work right now too provided the use the post content field and any required styles are manually enqueued in Gatsby. It's up to you :) 
ACF flexible content is a good way to go right now if you want something that definitely works, but it of course wont have all the pre-styled components ready to go that Avada has.

**Comment by TylerBarnes** [comment]
Thanks again for opening this issue, I'm closing it as it seems to be resolved. Thanks @MussadiqKhan !
