### ISSUE TITLE
WPGraphQL for ACF Causes Error on Gatsby Develop

### ISSUE THREAD

**Issue by hashinteractive** [gatsbyjs/gatsby-source-wordpress-experimental#169]
When I install the WPGraphQL for ACF extension and follow the steps to add a ACF field group and the GraphQL Field Name for the ACF Group and then run `gatsby develop` I'm getting an error on build:

```
success onPreExtractQueries - 0.001s

ERROR 

Missing onError handler for invocation 'extracting-queries', error was 'Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
```

The field group is showing up in GraphiQL explorer and am able to query it from outside of my WordPress installation such as:
![image](https://user-images.githubusercontent.com/12477388/93957557-2500ae00-fd1a-11ea-9bc1-255c5e55fc6e.png)

But no luck within Gatsby.

Any ideas?

**Comment by TylerBarnes** [comment]
Hi @hashinteractive , it's hard to tell what could be happening from the description.
Can you share a reproduction repo with a live /graphql URL endpoint that I can use to reproduce?
If you can't share the repo, the URL + the output of `gatsby info` would work as well.

Thanks!

**Comment by hashinteractive** [comment]
Hey @TylerBarnes,

Thanks for taking a look into this.

Here is the Wordpress install with WPGraphQL and WPGatsby installed along with WPGraphQL ACF plugin extension.
http://smartconnect.hashclients.com/graphql

I have a few ACF field groups setup that have a "location" set to custom post types. For example, I have a custom post type called `service` with a ACF Field group called `detailsTab` and you can see that they are accessible by running:
```
query{
  services {
    nodes {
      detailsTab {
        fieldGroupName
      }
    }
  }
}
```

However, in a Gatsby project with `gatsby-source-wordpress-experimental` I'm running into the following error while building (in `gatsby develop` or `gatsby-build`) and not able to run the gatbsy project:

```
success onPreExtractQueries - 0.002s

ERROR 

Missing onError handler for invocation 'extracting-queries', error was 'Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
```

Here is the Gatsby project repo I'm using:
https://gitlab.com/tthenne/smartconnect.git

Note you will need `.env.development` file:
```
WP_GRAPHQL_URL="http://smartconnect.hashclients.com/graphql"
```
Here's the output of `gatsby info` on the project as well:

```
{
  name: 'gatsby-starter-default',
  description: 'Gatsby default starter',
  'dist-tags': {
    next: '1.0.0',
    latest: '1.0.0'
  },
  versions: [
    '1.0.0'
  ],
  maintainers: [
    {
      name: 'davekrstin',
      email: 'dave@davekrstin.com'
    }
  ],
  time: {
    modified: '2017-11-16T18:32:55.888Z',
    created: '2017-11-16T18:32:55.888Z',
    '1.0.0': '2017-11-16T18:32:55.888Z'
  },
  keywords: [
    'gatsby'
  ],
  author: {
    name: 'Kyle Mathews',
    email: 'mathews.kyle@gmail.com'
  },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '1.0.0',
  dependencies: {
    gatsby: '^1.9.99',
    'gatsby-link': '^1.6.24',
    'gatsby-plugin-react-helmet': '^1.0.8'
  },
  main: 'n/a',
  scripts: {
    build: 'gatsby build',
    develop: 'gatsby develop',
    start: 'concurrently "gatsby develop" "json-server --watch ../playground/src/components/StatefulShell/configs/remote-config.json"',
    format: 'prettier --trailing-comma es5 --no-semi --single-quote --write "src/**/*.js"',
    test: 'echo "Error: no test specified" && exit 1'
  },
  devDependencies: {
    concurrently: '^3.5.0',
    prettier: '^1.7.4'
  },
  dist: {
    integrity: 'sha512-nn5DNZ5dbwcDe2TmTQb1JRoLOe9hB8LhGOvLq5LU6UgApsn3MQMwhT7cACrxd+yD2V+pk0oTu9w6uL66olnSmg==',
    shasum: '7d4a555f5a824bcfc876554b82ea839e190d2295',
    tarball: 'https://registry.npmjs.org/gatsby-starter-default/-/gatsby-starter-default-1.0.0.tgz'
  },
  directories: {}
}
```

Any ideas on the error?

**Comment by TylerBarnes** [comment]
Thanks for the repro! Looks like the /graphql endpoint is down. Is that the right URL?

**Comment by hashinteractive** [comment]
Hey Tyler,
Sorry my dev instance got rebooted for some reason and the server wasn't restarted. Should be good to go now.

I can confirm that's the correct url/endpoint.

Thanks,

**Comment by hashinteractive** [comment]
Hey guys, any resolution on this? Were you able to reproduce on the test environment using a fresh gatsby project with `gatbsy-source-wordpress-experimental`

**Comment by TylerBarnes** [comment]
@hashinteractive , I haven't had time to look yet but I'll take a look today. Thanks!

**Comment by hashinteractive** [comment]
Hey @TylerBarnes, just checking in to confirm you are getting the error as well? I'm sure you're busy. Any updates would be greatly appreciated 🙏

**Comment by TylerBarnes** [comment]
A fix is published in `gatsby-source-wordpress-experimental@1.7.1`. The cause was that your schema somehow has a field registered which has no name. This plugin now silently ignores fields like that. Thanks for raising this issue!
