### ISSUE TITLE
Cannot terminate build on Gatsby Cloud

### ISSUE THREAD

**Issue by philip-akerfeldt** [gatsbyjs/gatsby-source-wordpress-experimental#170]
Hi!

I have encountered an issue that I don't know how to resolve. I am trying to get my site up and running on Gatsby Cloud but one build seems to be going on forever. The build has been going on for almost 40 minutes and there has been no errors yet. I would really like to force the build to terminate so that I can try to find the issue. Right now i'm stuck in some kind of deadlock I guess. 

<img width="1128" alt="gc-error" src="https://user-images.githubusercontent.com/5981206/94055087-c0f2ee00-fddc-11ea-9414-4b080572be50.png">

Any ideas of how I can proceed?

**Comment by TylerBarnes** [comment]
Hi @philip-akerfeldt , thanks for opening this issue.
The best way to receive support about Gatsby Cloud is via the Cloud dashboard. You can open a support request by clicking on Help -> Customer support in the top right of the screen.

<img width="445" alt="Screen Shot 2020-09-23 at 12 43 49 PM" src="https://user-images.githubusercontent.com/14190743/94061788-b152b580-fd9a-11ea-9d64-54ea1669526d.png">
