### ISSUE TITLE
Migrating to v4, a plugin (Ultimate FAQ) output is not there anymore!

### ISSUE THREAD

**Issue by amirmeimari** [gatsbyjs/gatsby-source-wordpress-experimental#172]
Hey 👋
I'm currently using v3 and wanna migrate to v4, I created a test project to set `URL` to my production site.
I'm using [`Ultimate FAQ`](https://wordpress.org/plugins/ultimate-faqs/) plugin and I have the output in v3 in my graphql schema (image below). but in v4 there is no `allWordpressWpUfaq` property available!
what should I do to fix this problem? I installed an extra plugin for graphql ACF to be able to use ACF in v4, should I do the same for this faq plugin as well?!
 
![image](https://user-images.githubusercontent.com/34706947/94120488-07882d00-fe5d-11ea-949d-15cb29d43f48.png)
(I had this query on v3, but not in v4 anymore! tried to search the word `faq` but no result shown!)

**Comment by TylerBarnes** [comment]
Hi @amirmeimari , thanks for using this plugin and for opening this issue!
For the Faq post type to show up you'll need to enable it to show in WPGraphQL. 
Check here https://docs.wpgraphql.com/getting-started/custom-post-types/#filter-existing-post-types for info on how to achieve that.

You could even create a `Ultimate FAQ for WPGraphQL` WP plugin which adds this post type to WPGraphQL.
