### ISSUE TITLE
PublicURL is not available in GraphQL

### ISSUE THREAD

**Issue by MKlblangenois** [gatsbyjs/gatsby-source-wordpress-experimental#173]
Using version 3 of gatsby-source-wordpress, I had access to the `publicURL` field, but it is no longer available on` experimental`.

Moreover, when I want to display an SVG type image, I necessarily do not have access to `childImageSharp`, and I get the following error which tells me to use` publicURL`:

`You can't use childImageSharp together with school-white.svg — use publicURL instead. The
childImageSharp portion of the query in this file will return null:`

SVG files are fine in my .cache folder, but I have no way to display it via public url. 

![result of wpMediaItem of SVG](https://i.ibb.co/3FJmrDn/Capture-d-e-cran-2020-09-24-a-14-48-33.png)

**Comment by TylerBarnes** [comment]
Hi @MKlblangenois thanks for using this plugin and opening this issue!
Are you able to share a /graphql URL I can use to reproduce this? When I check on my test schema it has `MediaItem.localFile.publicURL` available and is resolving data properly.

<img width="1052" alt="Screen Shot 2020-09-24 at 12 12 06 PM" src="https://user-images.githubusercontent.com/14190743/94189174-44552380-fe5f-11ea-8e8f-9cf2b5bf59eb.png">

**Comment by MKlblangenois** [comment]
Hi @TylerBarnes ! 

Ok, I just updated `gatsby-transformer-sharp` and `gatsby-plugin-sharp` and I can see again `publicURL` now !

Thanks for your answer and sorry for the time 😅
