### ISSUE TITLE
Can Gatsby access wp_options table data when using graphql with gastby source wordpress? 

### ISSUE THREAD

**Issue by ssoney200** [gatsbyjs/gatsby-source-wordpress-experimental#177]
Hi All,

I have a fairly complicated issue that I need some advice on so please bear with me. 

I have a site on wordpress using the plugin 'mega menu max'.  Using this plugin you can create dropdown mega menus 
menus using a variety of options such as adding additional sub menus, or adding images with text and content etc. 

<img width="1150" alt="Screenshot 2020-09-25 at 13 05 41" src="https://user-images.githubusercontent.com/7794363/94265081-d298da80-ff2f-11ea-9d0c-55562a7f0d1a.png">

The only options we currently use is the Navigation Menu option or Image options. This is what the menu looks like.

<img width="1181" alt="Screenshot 2020-09-25 at 11 52 04" src="https://user-images.githubusercontent.com/7794363/94258913-8b0d5100-ff25-11ea-9bea-6ccf57f92693.png">

Whilst using the Navigation Menu option I can retrieve this data easily in Gatbsy via the graphql menu items, so that's all really great. However, I'm facing an issue where if the user chooses to add an image and text with link (like item 'Why Hospitality' in the screenshot above), I'm having to hard code this on the Gatsby side, which obviously isn't ideal in the long term. 

After doing some research on the WP side, this image data is stored by mega menu max in the wp_options table. It stores all the widget_media_image data in one row like screenshot below (the part I've highlighted in screenshot is for this particular 'Why Hospitality' Image, Text and Link. 

<img width="1404" alt="Screenshot 2020-09-25 at 12 07 08" src="https://user-images.githubusercontent.com/7794363/94260199-a4af9800-ff27-11ea-98ea-c20db0e92aaf.png">

The full data example is copied below to show examples of how I would need to loop through indexes to retrieve this information, but the good news (I can see) is that reference for each item like : _i:2;a:16_ or _i:3;a:16_ etc never change when they update, so if I can retrieve that code and use it in my navigation component that would be awesome, i just need to figure the best route to do so...  Can you even access wp_options via graphql or would it be easier to manage via the REST API?  Any advice from Gatsby pro's  on where to even begin would be greatly received. 

`a:14:{i:2;a:16:{s:24:"mega_menu_is_grid_widget";s:4:"true";s:4:"size";s:4:"full";s:5:"width";i:235;s:6:"height";i:172;s:7:"caption";s:0:"";s:3:"alt";s:0:"";s:9:"link_type";s:6:"custom";s:8:"link_url";s:92:"https://gy635czgvgogs1a3tdly-admin.glion.edu/about-us/your-future-in-hospitality-and-beyond/";s:13:"image_classes";s:0:"";s:12:"link_classes";s:0:"";s:8:"link_rel";s:0:"";s:17:"link_target_blank";b:0;s:11:"image_title";s:0:"";s:13:"attachment_id";i:4741;s:3:"url";s:112:"https://gy635czgvgogs1a3tdly-admin.glion.edu/wp-content/uploads/2020/08/Navigation_block_what_is_hospitality.jpg";s:5:"title";s:18:"Why hospitality???";}i:3;a:16:{s:24:"mega_menu_is_grid_widget";s:4:"true";s:4:"size";s:4:"full";s:5:"width";i:235;s:6:"height";i:172;s:7:"caption";s:0:"";s:3:"alt";s:0:"";s:9:"link_type";s:6:"custom";s:8:"link_url";s:53:"https://gy635czgvgogs1a3tdly-admin.glion.edu/careers/";s:13:"image_classes";s:0:"";s:12:"link_classes";s:0:"";s:8:"link_rel";s:0:"";s:17:"link_target_blank";b:0;s:11:"image_title";s:0:"";s:13:"attachment_id";i:4733;s:3:"url";s:115:"https://gy635czgvgogs1a3tdly-admin.glion.edu/wp-content/uploads/2020/08/Navigation_block_accelerate_your_career.jpg";s:5:"title";s:22:"Accelerate your career";}i:4;a:16:{s:24:"mega_menu_is_grid_widget";s:4:"true";s:4:"size";s:4:"full";s:5:"width";i:235;s:6:"height";i:173;s:7:"caption";s:0:"";s:3:"alt";s:0:"";s:9:"link_type";s:6:"custom";s:8:"link_url";s:60:"https://gy635czgvgogs1a3tdly-admin.glion.edu/apply-to-glion/";s:13:"image_classes";s:0:"";s:12:"link_classes";s:0:"";s:8:"link_rel";s:0:"";s:17:"link_target_blank";b:0;s:11:"image_title";s:0:"";s:13:"attachment_id";i:51;s:3:"url";s:97:"https://gy635czgvgogs1a3tdly-admin.glion.edu/wp-content/uploads/2020/05/20190923_GLION_4530-1.jpg";s:5:"title";s:9:"APPLY NOW";}i:5;a:16:{s:24:"mega_menu_is_grid_widget";s:4:"true";s:4:"size";s:4:"full";s:5:"width";i:235;s:6:"height";i:172;s:7:"caption";s:0:"";s:3:"alt";s:0:"";s:9:"link_type";s:6:"custom";s:8:"link_url";s:67:"https://gy635czgvgogs1a3tdly-admin.glion.edu/locations/switzerland/";s:13:"image_classes";s:0:"";s:12:"link_classes";s:0:"";s:8:"link_rel";s:0:"";s:17:"link_target_blank";b:0;s:11:"image_title";s:0:"";s:13:"attachment_id";i:3840;s:3:"url";s:87:"https://gy635czgvgogs1a3tdly-admin.glion.edu/wp-content/uploads/2020/07/switzerland.jpg";s:5:"title";s:11:"Switzerland";}i:6;a:16:{s:24:"mega_menu_is_grid_widget";s:4:"true";s:4:"size";s:4:"full";s:5:"width";i:235;s:6:"height";i:172;s:7:"caption";s:0:"";s:3:"alt";s:0:"";s:9:"link_type";s:6:"custom";s:8:"link_url";s:62:"https://gy635czgvgogs1a3tdly-admin.glion.edu/locations/london/";s:13:"image_classes";s:0:"";s:12:"link_classes";s:0:"";s:8:"link_rel";s:0:"";s:17:"link_target_blank";b:0;s:11:"image_title";s:0:"";s:13:"attachment_id";i:3839;s:3:"url";s:82:"https://gy635czgvgogs1a3tdly-admin.glion.edu/wp-content/uploads/2020/07/london.jpg";s:5:"title";s:6:"London";}i:7;a:16:{s:24:"mega_menu_is_grid_widget";s:4:"true";s:4:"size";s:4:"full";s:5:"width";i:235;s:6:"height";i:172;s:7:"caption";s:0:"";s:3:"alt";s:0:"";s:9:"link_type";s:6:"custom";s:8:"link_url";s:64:"https://gy635czgvgogs1a3tdly-admin.glion.edu/campus-taster-days/";s:13:"image_classes";s:0:"";s:12:"link_classes";s:0:"";s:8:"link_rel";s:0:"";s:17:"link_target_blank";b:0;s:11:"image_title";s:0:"";s:13:"attachment_id";i:4739;s:3:"url";s:107:"https://gy635czgvgogs1a3tdly-admin.glion.edu/wp-content/uploads/2020/08/Navigation_block_visit_a_campus.jpg";s:5:"title";s:17:"Campus Taster Day";}`

**Comment by TylerBarnes** [comment]
Hi @ssoney200 , Gatsby can access any data which is added to the WPGraphQL schema. Please refer to the WPGraphQL docs to learn more https://www.wpgraphql.com/docs/introduction
