### ISSUE TITLE
Gatsby doesn't run when auth option is set

### ISSUE THREAD

**Issue by SuperCiacho** [gatsbyjs/gatsby-source-wordpress-experimental#180]
Using version 1.4.4.
After adding `auth` option, `gatsby develop` exits with error 
**TypeError: Parameter `auth` is deprecated. Use `username` / `password` instead.**

![obraz](https://user-images.githubusercontent.com/5670702/94348953-2ba86180-0049-11eb-88ef-18434ccb6f49.png)

![obraz](https://user-images.githubusercontent.com/5670702/94349019-8c379e80-0049-11eb-8c7e-7f75190dde42.png)

**Comment by SuperCiacho** [comment]
After delete and reinstall `node_modules` gatsby app started without errors.

I'm closing the ticket.

**Comment by hazuremon** [comment]
I am seeing the same problem after upgrading to 1.4.4 and 1.4.5 where media download failed when running "gatsby build"

Error I am seeing:
`info pushing https://www.example.com/image.jpg to the end of the request queue.
info Previously retried 4 times already.`
And
`failed to process https://www.example.com/image.jpg
TypeError: Parameter `auth` is deprecated. Use `username` / `password` instead.`

Set GATSBY_CONCURRENT_DOWNLOAD to 30 but still to no success.

Downgraded back to 1.4.1 seems to solve the problem for me, as media download successfully without error.

**Comment by rodrigo-arias** [comment]
Same error here using WP Engine and password protect. Version 1.4.2 seems to work for me

**Comment by hazuremon** [comment]
Problem remains with the latest release of gatsby-source-wordpress-experimental (v1.5.3).

@TylerBarnes Should this be label as bug, as site build failed when htaccess authentication is set? WordPress site without authentication are build successfully.

**Comment by TylerBarnes** [comment]
@hazuremon absolutely. I'll get this fixed and add htaccess auth to the test instance so this wont regress again. I'll follow up soon. Thanks for your patience!

**Comment by TylerBarnes** [comment]
Turns out this was a dupe of https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/53
A fix is published in `gatsby-source-wordpress-experimental@1.6.2`. Thanks for your patience here!
