### ISSUE TITLE
Failed to download media file.

### ISSUE THREAD

**Issue by kawamataryo** [gatsbyjs/gatsby-source-wordpress-experimental#181]
Hi. Thank you for very useful Library.

Error will occur when `gatsby develop` commands.
related isuue https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/53.

## Environment to reproduce
Repo: https://github.com/kawamataryo/practice-gatsby-source-wordpress-experimental
Wordpress URL: https://makoto-acu.com
Wordpress: v5.51
gatsby-source-wordpress-experimental: 1.4.4
WP Gatsby: 0.4.17
WP GraphQL: 0.12.3

### log

```
success open and validate gatsby-configs - 0.037s
success load plugins - 0.780s
success onPreInit - 0.033s
success initialize cache - 0.014s
success copy gatsby files - 0.041s
success onPreBootstrap - 0.021s
success  gatsby-source-wordpress  ingest WPGraphQL schema - 0.857s
success createSchemaCustomization - 1.668s
success  gatsby-source-wordpress  Category - 0.372s - fetched 4
success  gatsby-source-wordpress  Comment - 0.155s - fetched 0
success  gatsby-source-wordpress  ContentType - 0.239s - fetched 3
success  gatsby-source-wordpress  MenuItem - 0.403s - fetched 24
success  gatsby-source-wordpress  Menu - 0.248s - fetched 3
success  gatsby-source-wordpress  Page - 0.360s - fetched 8
success  gatsby-source-wordpress  PostFormat - 0.163s - fetched 0
success  gatsby-source-wordpress  Post - 1.631s - fetched 70
success  gatsby-source-wordpress  Tag - 0.207s - fetched 0
success  gatsby-source-wordpress  Taxonomy - 0.248s - fetched 3
success  gatsby-source-wordpress  UserRole - 0.124s - fetched 0
success  gatsby-source-wordpress  User - 0.347s - fetched 2
info pushing /wp-content/uploads/2017/03/5642fae96ade14100be5-1.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing /wp-content/uploads/2017/02/466bd28e5ab06680a011.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing /wp-content/uploads/2017/03/5642fae96ade14100be5-1.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing /wp-content/uploads/2017/02/466bd28e5ab06680a011.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing /wp-content/uploads/2017/03/5642fae96ade14100be5-1.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing /wp-content/uploads/2017/02/466bd28e5ab06680a011.jpg to the end of the request queue.
info Previously retried 4 times already.
info

already re-queued /wp-content/uploads/2017/03/5642fae96ade14100be5-1.jpg 5 times :( sorry.
Try lowering process.env.GATSBY_CONCURRENT_DOWNLOAD.
It's currently set to 1



 ERROR 

url passed to create-remote-file-node is either missing or not a proper web uri: /wp-content/uploads/2017/03/5642fae96ade14100be5-1.jpg

not finished source and transform nodes - 300.573s
not finished  gatsby-source-wordpress  fetching nodes - 300.547s - 119 total
not finished  gatsby-source-wordpress  creating nodes - 295.972s
not finished  gatsby-source-wordpress  MediaItem - 295.973s - fetched 2

```

I set `GATSBY_CONCURRENT_DOWNLOAD=1`. but I get this error.
Is there a solution?

Thanks.

**Comment by gustavpursche** [comment]
I'm having the same problem after updating from `1.4.0` to `1.4.4`. @kawamataryo downgrading to 1.4.0 helps in my case.

**Comment by kawamataryo** [comment]
@gustavpursche 

Thank you for your comment.

 I tried downgrading to `1.4.0`.

```bash
$ yarn remove gatsby-source-wordpress-experimental
$ yarn add gatsby-source-wordpress-experimental@1.4.0
```

But, I got same error :_(

**Comment by JimCaignard** [comment]
Same here but after downgrading to 1.4.1 in the package.json (don't forget to do a yarn after that) it worked !

**Comment by TylerBarnes** [comment]
Hey, everyone, this regression was introduced when fixing a bug related to JSON fields which have image tags in embedded html. I've added a bunch of inline html gatsby image integration tests, but haven't yet added one for relative image paths like "/wp-content/uploads/2017/03/5642fae96ade14100be5-1.jpg". I'll get this fixed asap and add a test for this to prevent future regressions. Thanks for reporting this!

**Comment by TylerBarnes** [comment]
This is fixed in `gatsby-source-wordpress-experimental@1.4.5`. Please feel free to re-open or comment here if this didn't solve your issue. I tested this on the provided repo/gql api and it worked great. This bug also uncovered a couple other semi-related bugs which always nice :)

**Comment by kawamataryo** [comment]
@TylerBarnes 

wow!! great!! It worked.  I’m grateful to you :)

**Comment by TylerBarnes** [comment]
Hi @gustavpursche and @enx1998 it appears you're encountering a separate issue. The original issue was related to media items that had paths stored as source urls (like `/wp-content/uploads/2020/09/jmm-1.png`). 

Can you open a new issue with a reproduction I can use to debug?
