### ISSUE TITLE
Question: "What are the requirements for a MediaItem to be downloaded and processed by Gatsby?"

### ISSUE THREAD

**Issue by simonzsolt89** [gatsbyjs/gatsby-source-wordpress-experimental#183]
First of all, thank you so much for this source plugin and wp-graphql in general! :pray:

**My current understanding:**

1. needs to be attached to a post type
2. needs to be queried in the project 

**Questions:**

1. Would it be enough to just query the media-item?
2. Are options-page acf Image fields supported in the current version? (with the wp-graphql-acf options page reqs. met)

**Current situation:**

Images that are queried from an options page - image acf field are returning null in my project.

**Is the following code-snippet still relevant for gatsby-image processing?**
```
exports.createResolvers = async ({
  actions,
  cache,
  createNodeId,
  createResolvers,
  store,
  reporter,
}) => {
  const { createNode } = actions;

  await createResolvers({
    WpMediaItem: {
      imageFile: {
        type: `File`,
        async resolve(source) {
          return await createRemoteFileNode({
            url: source.sourceUrl,
            store,
            cache,
            createNode,
            createNodeId,
            reporter,
          });
        },
      },
    },
  });
};
```
Thank you for your time!

**Comment by TylerBarnes** [comment]
Great questions @simonzsolt89 !

Any images in ACF fields should automatically be sourced and work in your project. Can you share a reproduction where it's not working for you? That might be a bug. 🤔 I think all my ACF tests are running on posts rather than options, so the tests may need to be updated as well actually.

As to that snippet, it's no longer needed :)

**Comment by simonzsolt89** [comment]
Hello again, thank you for you response and I apologise for mine being late.

Good news is that I have narrowed down the cause of the issue :slightly_smiling_face:

While using wp-graphql-polylang, ACF image fields in Options pages can only be queried on the default language. MediaItems in options pages that are set to !default-langauge are not recognised by gatsby-source-wordpress-experimental.

Version numbers for packages used:

gatsby: 2.24.72
gatsby-source-wordpress-experimental: 1.7.1

wp-gatsby: 0.4.17
wp-graphql: 0.13.3
wp-graphql-polylang: 0.5.0
polylang: 2.8.2
ACF Options for Polylang: 1.1.7
wp-graphql-acf: 0.3.5
acf-pro: 5.9.1

Thanks again for all of your hard work! 🙏

**Comment by TylerBarnes** [comment]
This has been documented here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/features/media-item-processing.md

Thanks everyone :)
