### ISSUE TITLE
Strip the path when comparing URLs

### ISSUE THREAD

**Issue by magicspon** [gatsbyjs/gatsby-source-wordpress-experimental#185]
RE: Incremental build failure.

Roots/Bedrock theme requires a question mark in the URL.

This is throwing the following error:

gatsby-source-wordpress  Received preview data from a different remote URL than the one specified in plugin options. Remote URL: https://myfancywebsite.com/wp/graphql  
Plugin options URL: https://myfancywebsite.com/wp/?graphql

**Comment by TylerBarnes** [comment]
Thanks for raising this 👍 I'll get this fixed later today :)

**Comment by TylerBarnes** [comment]
Fixed in `gatsby-source-wordpress-experimental@1.4.6`. Thanks again!
