### ISSUE TITLE
Feature request: Non-null fields behaviour on local build

### ISSUE THREAD

**Issue by erick-go** [gatsbyjs/gatsby-source-wordpress-experimental#192]
Consider the following situation:
600 posts on live site
ACF post object fields pointing to related posts

20 posts on development site
ACF post object fields pointing to non existing posts

gatsby build produces `ERROR #85925 Cannot return null for non-nullable field WpPost.uri` 

It would be convenient if the fields would become nullable in this situation.

**Comment by TylerBarnes** [comment]
This is fixed in `gatsby-source-wordpress-experimental@3.1.1`
