### ISSUE TITLE
Getting the static front page

### ISSUE THREAD

**Issue by stephencottontail** [gatsbyjs/gatsby-source-wordpress-experimental#194]
I have my WordPress site set to use a static page as the front page (Dashboard > Appearance > Customize > Homepage Settings) but in GraphQL, `isFrontPage` returns false for that page. Am I misunderstanding what that field is used for, and if so, how can I get the ID of the page set to be the static front page other than hardcoding it in my JS?

**Comment by TylerBarnes** [comment]
Hi @stephencottontail , were you able to verify wether or not you can properly query for this data outside of Gatsby? (Using something like GraphiQL or GraphQL Playground).
It sounds like there may be a bug somewhere, either in your WP site or in WPGraphQL.

**Comment by stephencottontail** [comment]
I checked In GraphiQL (at `localhost/___graphql`) and it appeared correctly there. Once I checked it in GraphiQL, it then worked in Gatsby. I don’t think that’s actually what fixed it but honestly I don’t remember everything I might have tried between those two events. It was probably user error anyway, so I guess it’s fixed?

**Comment by stephencottontail** [comment]
Hmm, maybe it isn’t entirely fixed. I was able to get Gatsby to recognize my static front page, but I just decided to change it to a different page in the WordPress backend and both GraphiQL and Gatsby itself are still returning the previous front page. Even ending `gatsby develop` and starting it again still returns the previously-set front page content.

**Comment by TylerBarnes** [comment]
Hi @stephencottontail I think the issue you're running into here is that WP options aren't currently synched when saving them.  You need to update them and then save a post for them to update properly. Follow https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/209 for updates on this missing functionality. Thanks!
