### ISSUE TITLE
Preview does not work (404) on pages which have a parent page

### ISSUE THREAD

**Issue by smetzdev** [gatsbyjs/gatsby-source-wordpress-experimental#222]
Hey,

as the title says, i cannot preview any pages, except top-level pages.
This happens when i click on the preview link inside the WordPress Editor.  
Any clue what i can do here? 

WP GraphQL Version: 0.12.3
gatsby-source-wordpress-experimental Version: 1.5.4

Thanks in advance👍

**EDIT:** Just updated gatsby-source-wordpress-experimental to v 1.7.6, still facing this issue

**Comment by TylerBarnes** [comment]
This is fixed in the latest release which includes a full rewrite of how Preview works. Give it a try with `gatsby-source-wordpres@3.0.1` 😄

**Comment by smetzdev** [comment]
Ah cool, you folks are on fire right now :D

**Comment by TylerBarnes** [comment]
Thank you!! :D btw, definitely go all the way to `gatsby-source-wordpress-experimental@3.0.3` when you try it out as there were a few bugs in the initial release that I took care of today.
