### ISSUE TITLE
Build fails incorrectly with 'pushing Media Item query #1 to the end of the request queue'

### ISSUE THREAD

**Issue by stupearce** [gatsbyjs/gatsby-source-wordpress-experimental#223]
There is a timing issue in that if 'fetchMediaItemsById'  (steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js)
is called a 2nd time before the first batch completes the call to pushPromiseOntoRetryQueue overwrites keys from the first batch as the key is only an index. Then the first instance item never resolves and they all timeout.

The solution i believe is to use the reayId as the key
      retryKey: `Media Item query #${relayIds[index]}`,

Also I noted whilst debugging that 'connection timeout' and 'Stall timeout' are not configurable as they are in gatsby-source-filesystem. It would be good to allow the same, on unless concurrency is set to 1 we are still occasionally getting issues from Digital Ocean spaces storage.

This is stopping our whole customer site building presently. I have hacked a fix in which works but out main build comes from gatsby cloud and i could do with a fix asap.? i can put in a pR

**Comment by TylerBarnes** [comment]
A fix is published in `gatsby-source-wordpress-experimental@1.7.6`. Thanks for raising this issue and for your patience!
