### ISSUE TITLE
Gatsby Preview: Template returns null

### ISSUE THREAD

**Issue by magicspon** [gatsbyjs/gatsby-source-wordpress-experimental#226]
Heyo,

During preview the template field returns as null.

```bash
22:50:33 PM: success building schema - 6.264s
22:50:33 PM: warning page: /my-fancy-page/, doesn't have a template reference
22:50:34 PM: info { "uri": "/my-fancy-page/", "id": "cG9zdDo0NDUxMQ==", "template": null, "form": { "formId": 6 } }
```

During build/dev it works as expected.
![image](https://user-images.githubusercontent.com/3268717/95794303-74197d80-0cdf-11eb-869e-b3bd6d9e0607.png)

any ideas how to resolve this. I'm using Templates a lot! 

cheers

**Comment by TylerBarnes** [comment]
Hi @magicspon do you know if this returns null in WPGraphQL? cc @jasonbahl

**Comment by magicspon** [comment]
The query looks in wp graphql, no idea if it works during preview, how would I test it?

**Comment by TylerBarnes** [comment]
You can add "asPreview: true" to the filter arguments on the node field. So like `wpPage(id: "cG9zdDo0NDUxMQ==" asPreview: true)`

**Comment by magicspon** [comment]
Hmm, that doesn't seem to work
![image](https://user-images.githubusercontent.com/3268717/95926249-bad8a780-0db3-11eb-98fa-c2a7d4d273b3.png)

tried in wp as well... asPreview doesn't seem to exist

**Comment by TylerBarnes** [comment]
Ah 🤦 sorry about, I misspoke. You want to make that query to the WPGraphQL api, not to Gatsby.
So you want to do `page(id: "cG9zdDo0NDUxMQ==" asPreview: true)` instead. You can use wp-graphiql (included in the latest version of WPGraphQL)

**Comment by magicspon** [comment]
![image](https://user-images.githubusercontent.com/3268717/95926571-8a453d80-0db4-11eb-8769-238b19087a22.png)


![image](https://user-images.githubusercontent.com/3268717/95926590-9204e200-0db4-11eb-9af0-4cea3a961311.png)

**Comment by TylerBarnes** [comment]
Ah, so this is a WPGraphQL bug. @jasonbahl I think we need this for 1.0

**Comment by jasonbahl** [comment]
Ah. Good call. Agreed. Need to
Fix this on WPGraphQL.

**Comment by TylerBarnes** [comment]
Looks like this was fixed upstream in WPGraphQL. I'm closing this but if you're still running into this problem, please re-open or comment here. Thanks for bringing this to our attention @magicspon !
