### ISSUE TITLE
Querying url on generalSettings crashes WP multisite

### ISSUE THREAD

**Issue by HumidBrains** [gatsbyjs/gatsby-source-wordpress-experimental#23]
I'm working on a WP multisite and want to migrate from gatsby-source-graphql.
However, I get this error on dev build. 

```
 gatsby-source-wordpress  GraphQL query: {
       schemaMd5
       # also get the wpUrl to save on # of requests
       # @todo maybe there's a better place for this
      generalSettings {
            url
         }
      }

```
The core problem lies with WPGraphQL which doesn't generate any url node on generalSettings for WP multisite. See https://github.com/wp-graphql/wp-graphql/issues/1334
The build breaks since this plugin seems to query the url on generalSettings when looking for changes in diff-schemas.js.

As mentioned, this is primarily a WPGraphQL bug, but it would be great with a fix that allows for the query to fail. This in order not to be blocked from using this plugin until there is a fix from WPGraphQL.

**Comment by tinder-kyleboss** [comment]
Ahh I am running into this issue as well.

**Comment by TylerBarnes** [comment]
Heads up @HumidBrains @tinder-kyleboss Jason and I were talking about this and this will be fixed in the next release of WPGraphQL (should be this week)

**Comment by TylerBarnes** [comment]
Hey everyone, please update to the latest version of WPGraphQL (`0.10.2`) and `gatsby-source-wordpress-experimental@0.8.1` for a fix.
