### ISSUE TITLE
Fetching Images at Build Time Causes an Error (Duplicate of #53)

### ISSUE THREAD

**Issue by uzomao** [gatsbyjs/gatsby-source-wordpress-experimental#236]
See issue #53 

I am facing the exact same problem but the fix published in `gatsby-source-wordpress-experimental@1.6.2` does not seem to be working in my case.

I am now using version `1.7.5`

My WPGraphQL API endpoint is http://theelectionnetwork.com/graphql

Here's a snippet of the error I am receiving:

```
already re-queued https://theelectionnetwork.com/wp-content/uploads/2017/11/IMG-20171119-WA0010.jpg 5 times :( sorry.
Try lowering process.env.GATSBY_CONCURRENT_DOWNLOAD.
It's currently set to 10
```

As you can see I have set the value of GATSBY_CONCURRENT_DOWNLOAD to as low as 10.

I don't quite understand the htaccess fix created by @shosasaki0 in PR #198 so not entirely sure how this problem affects my project. But as it has published in 1.6.2 this should not be an issue any longer. Any help will be appreciated.

**Comment by TylerBarnes** [comment]
Hi @uzomao , that issue is unrelated as your /graphql endpoint isn't behind htaccess auth. Can you paste the full error output here? The similar error you copied is just part of the error. 

Thanks!

**Comment by uzomao** [comment]
Hello @TylerBarnes, thanks for your reply to this. Here's the full build log including the error output:

```
Uzomas-MacBook-Air:gatefield-ten uzoma$ npm run build

> gatsby-starter-default@0.1.0 build /Users/uzoma/Projects/gatefield-ten
> env-cmd -f .env gatsby build

success open and validate gatsby-configs - 0.118s
success load plugins - 3.073s

 ERROR 

(node:15500) ExperimentalWarning: The dns.promises API is experimental

success onPreInit - 0.228s
success delete html and css files from previous builds - 0.119s
success initialize cache - 0.259s
success copy gatsby files - 0.231s
success onPreBootstrap - 0.032s
⠀
info  gatsby-source-wordpress 

        This is either your first build or the cache was cleared.
        Please wait while your WordPress data is synced to your Gatsby cache.

        Maybe now's a good time to get up and stretch? :D

success  gatsby-source-wordpress  ingest WPGraphQL schema - 8.024s
success createSchemaCustomization - 21.751s
success  gatsby-source-wordpress  fetch root fields - 2.742s
success  gatsby-source-wordpress  Category - 10.051s - fetched 25
success  gatsby-source-wordpress  Comment - 3.123s - fetched 0
success  gatsby-source-wordpress  ContentType - 2.866s - fetched 3
success  gatsby-source-wordpress  MenuItem - 2.462s - fetched 12
success  gatsby-source-wordpress  Menu - 2.459s - fetched 1
success  gatsby-source-wordpress  Page - 6.278s - fetched 22
success  gatsby-source-wordpress  PostFormat - 2.249s - fetched 3
success  gatsby-source-wordpress  Post - 89.886s - fetched 500
success  gatsby-source-wordpress  Tag - 62.546s - fetched 733
success  gatsby-source-wordpress  Taxonomy - 4.098s - fetched 3
success  gatsby-source-wordpress  UserRole - 2.330s - fetched 0
success  gatsby-source-wordpress  User - 6.132s - fetched 21

 ERROR 

(node:15500) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time

info pushing https://theelectionnetwork.com/wp-content/uploads/2017/11/IMG-20171119-WA0010.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://theelectionnetwork.com/wp-content/uploads/2017/11/IMG-20171119-WA0010.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://theelectionnetwork.com/wp-content/uploads/2017/11/IMG-20171119-WA0010.jpg to the end of the request queue.
info Previously retried 4 times already.
info

already re-queued https://theelectionnetwork.com/wp-content/uploads/2017/11/IMG-20171119-WA0010.jpg 5 times :( sorry.
Try lowering process.env.GATSBY_CONCURRENT_DOWNLOAD.
It's currently set to 10



 ERROR 

failed to process https://theelectionnetwork.com/wp-content/uploads/2017/11/IMG-20171119-WA0010.jpg
TimeoutError: Timeout awaiting 'request' for 30000ms

not finished source and transform nodes - 1062.147s
not finished  gatsby-source-wordpress  fetching nodes - 1061.824s - 1324 total
not finished  gatsby-source-wordpress  creating nodes - 867.144s
not finished  gatsby-source-wordpress  MediaItem - 867.148s - fetched 1
not finished Downloading remote files - 30.103s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@0.1.0 build: `env-cmd -f .env gatsby build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-default@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/uzoma/.npm/_logs/2020-10-16T00_03_31_335Z-debug.log
```

**Comment by TylerBarnes** [comment]
Hi again @uzomao , I had a look and this is indeed related to your server being overwhelmed by image requests. I lowered GATSBY_CONCURRENT_DOWNLOAD to 1 and it sourced everything fine :) 

Long term we're hoping to add a smart downloader that can auto adjust these settings, but for now it needs to be manually set #66

**Comment by uzomao** [comment]
Interesting, I actually tried setting GATSBY_CONCURRENT_DOWNLOAD to 1 earlier today but that didn't seem to solve anything. I'm trying it again though to see if it works

**Comment by TylerBarnes** [comment]
Since your server seems to have trouble serving up so much at once you might want to either lower the amount of posts that are fetched in development (down to 100 from 500) and enable hard caching for data.

https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/plugin-options.md#develophardcachedata-boolean

**Comment by TylerBarnes** [comment]
BTW you can do this:

```js
        type: {
          Post: {
            limit: process.env.NODE_ENV === `development` ? 50 : null,
          },
        },
```

That fetches 50 posts in development and all posts when you run a production build

**Comment by uzomao** [comment]
Post limits are currently set to 50 (just to test) and hard caching has always been enabled, still the problem persists. Note that this is when I try to create a production build, all is fine in development (with my server set up locally). The hack I am thinking of attempting now is importing my production db into that local server and creating a production build from that.

**Comment by TylerBarnes** [comment]
@uzomao , there are 2 hard caches, one for media files and one for data (but the data hard cache only works in development).

We definitely need more work put into ensuring the plugin works for any server type. Right now some slower servers can have a hard time serving things up. I can highly recommend WPEngine for this if that can work for you project. If it's a personal site, you can definitely run it local and push the build up somewhere.

For our first stable release we're working on data validity/stability. In a later release we'll be working on making things more practical for all users.

cc @jacksellwood

**Comment by uzomao** [comment]
Yup, I have `hardCacheMediaFiles` set to `true` in the plugin options.

Thanks for the rec, I actually have the site setup locally on Local by Flywheel so am trying to create the production build from that.

Problem now is that the build is failing because of a 404 error while fetching certain images...

**Comment by TylerBarnes** [comment]
For sure :) I mean there's also a `hardCacheData` option. 404'ing images is a big pain for folks right now. It's something we definitely need to put a lot more thought into

**Comment by uzomao** [comment]
Ah I see what you mean about `hardCacheData`

I also hear you on 404's being an issue, I'm going to mess around with it for a bit and see what I might find :)

**Comment by TylerBarnes** [comment]
Cool, let me know how it goes! Hopefully you can get it building soon, it's always annoying when things don't work.
