### ISSUE TITLE
did it. Merge and try this

### ISSUE THREAD

**Issue by Krishjain2911** [gatsbyjs/gatsby-source-wordpress-experimental#238]
{
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: 'http://my-site.com/graphql',
      }

}

**Comment by TylerBarnes** [comment]
This looks like an accident 😜 if you need help and have a specific issue, please open a new issue with a descriptive title, content, and a reproduction of your problem. Thanks!
