### ISSUE TITLE
Missing  wpml_current_locale parametr key

### ISSUE THREAD

**Issue by Rinzlerte** [gatsbyjs/gatsby-source-wordpress-experimental#242]
Actually when i use older version of gatsby-source-wordpress for grabing data in graphql shemas queries explorer is easy to find and use wpml_current_locale key, but when i using  gatsby-source-wordpress-experimental for same site -wpml_current_locale key  its missing.  Did i miss something?

**Comment by Oliweer** [comment]
The older gatsby-source-wordpress used the rest api which WPML supports, the newer one is running graphql and there is no official support. You could switch to polylang instead and use https://github.com/valu-digital/wp-graphql-polylang

**Comment by Rinzlerte** [comment]
> The older gatsby-source-wordpress used the rest api which WPML supports, the newer one is running graphql and there is no official support. You could switch to polylang instead and use https://github.com/valu-digital/wp-graphql-polylang

thy

**Comment by TylerBarnes** [comment]
This is unfortunately true! The good news is Polylang works very well with this plugin.
Hopefully we get a WPGraphQL WPML extension that works well soon.
