### ISSUE TITLE
release v1.7.8 breaks with lerna

### ISSUE THREAD

**Issue by pehaa** [gatsbyjs/gatsby-source-wordpress-experimental#243]
Hey,

After upgrading, I got the:

 ERROR #10226  CONFIG

Couldn't find the "gatsby-source-wordpress-experimental" plugin declared in "/Users/paulinahetman/Web/gatsby-wp-themes-new/packages/gatsby-theme-blog-data/gatsby-config.js".

I tried to manually add
` "main": "dist/index.js",`
 to the `package.json`, and it seems to fix this issue.

**Comment by TylerBarnes** [comment]
Hey Paulina! Thanks for bringing this to my attention and apologies for the delayed response. This is fixed as of `v1.7.9`. Thanks again :)
