### ISSUE TITLE
wp-graphql@0.14.0 && isSticky

### ISSUE THREAD

**Issue by yepstepz** [gatsbyjs/gatsby-source-wordpress-experimental#249]
Hi!
Found  that issue with isSticky label was fixed in wp-qraphql@0.14.0, installed it to my wp, but when I run `npm run develop` it says 
`Install a version between 0.10.3 and 0.14.0.`

I have `"gatsby-source-wordpress-experimental": "^1.7.9",`

do `gatsby-source-wordpress-experimental` needs some workaround? Or maybe it's too early to move into newer version of wp-graphql?

Thanks!

**Comment by TylerBarnes** [comment]
Hi @yepstepz , you need to upgrade your version of `gatsby-source-wordpress-experimental` actually :) try `2.0.1`
