### ISSUE TITLE
upload image from gatsby to wordpress 

### ISSUE THREAD

**Issue by iryanrachman** [gatsbyjs/gatsby-source-wordpress-experimental#25]
upload image from gatsby to wordpress  and connect it to some acf like bio

**Comment by TylerBarnes** [comment]
Hi @iryanrachman I'm not 100% sure what you're asking here :p but it sounds like you're looking for a feature where Gatsby uploads images to WPGraphQL during the build process?
That sounds like it could be useful in some cases, but doesn't need to be part of this source plugin as you should be able to write code for that in your `gatsby-node.js` file. If I'm misunderstanding, please open a new issue with a clearer and more in depth description of what you're looking for.

Thanks!
