### ISSUE TITLE
Previews on custom post types, which haven't been published, do not work

### ISSUE THREAD

**Issue by MobyDigg** [gatsbyjs/gatsby-source-wordpress-experimental#267]
I have several custom post types on my site. When I create a new post, with a custom post type, and hit the **preview** button, before I publish the post, then the preview does not work. It shows the Gatsby 404 page and says: There's not a page yet at /project/6876 ("project" being my custom post type). Once the custom post type post has been published the preview works as wished.

On regular posts / pages, it works as expected. Even with unpublished posts or drafts. 

**Setup**

- WordPress backend connected to GatsbyCloud
- Custom Post Type UI 1.8.1 for the creation of the custom post types
- WPGatsby v. 0.5.4
- WPGraphQL v. 0.14.0
- WPGraphQL for Advanced Custom Fields v. 0.3.5
- WP GraphQL Polylang v. 0.5.0
- gatsby-source-wordpress-experimental v. ^2.0.1

Is there an easy way to fix this?

Thanks!

**Comment by TylerBarnes** [comment]
This is fixed in the latest release which includes a full rewrite of how Preview works. Give it a try with `gatsby-source-wordpres@3.0.1`

**Comment by yepstepz** [comment]
Thanks for this feature! Is it necessary to use gatsby cloud? Can i try it with my own server or even a local server? readme says i need to set up gatsby cloud

**Comment by TylerBarnes** [comment]
You are able to self host actually! See https://www.gatsbyjs.com/docs/running-a-gatsby-preview-server/ for more info
