### ISSUE TITLE
Documentation: Which specs does my server need, to fully take advantage of unrestricted concurrent requests / the gswe plugin?

### ISSUE THREAD

**Issue by MobyDigg** [gatsbyjs/gatsby-source-wordpress-experimental#271]
I was wondering if you could provide a list of needed server specs to fully take advantage of Gatsby's concurrent requests. Is it the database requests, which are the bottleneck and make the usage / throttling of GATSBY_CONCURRENT_DOWNLOAD necessary? Could you give a recommendation for 2-3 hosting-providers, which work flawlessly with gatsby-source-wordpress-experimental and without request restrictions? This would help a lot. Thanks. 

PS: Maybe it would be nice to describe the necessary server specs a bit in the docs?

**Comment by TylerBarnes** [comment]
Hi @MobyDigg , ideally this plugin should work on any server (it doesn't currently). So one day the answer will be "any". However, right now we're not in that world and the answer is much more blurry. It depends entirely on how complex your data is, how many images you use, and a variety of other factors. I know folks have been having good success on WPEngine so I would recommend them for now. I'm going to mark this as a documentation issue as we'll be doing a documentation push very soon.

**Comment by MobyDigg** [comment]
> Hi @MobyDigg , ideally this plugin should work on any server (it doesn't currently). So one day the answer will be "any". However, right now we're not in that world and the answer is much more blurry. It depends entirely on how complex your data is, how many images you use, and a variety of other factors. I know folks have been having good success on WPEngine so I would recommend them for now. I'm going to mark this as a documentation issue as we'll be doing a documentation push very soon.

Hi @TylerBarnes, thanks. I tested a lot in the past months and can confirm: WPEngine works brilliantly with this setup. Our websites work with a lot of media files and several custom post types, which generate quite a few queries. For this reason, I had to use GATSBY_CONCURRENT_DOWNLOAD=2, which didn't work well with preview. I appreciate the effort to get it going on any server, but for now just knowing where to go helps a lot.

**Comment by TylerBarnes** [comment]
This is documented here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/hosting.md

As mentioned we will be looking at making this plugin work for absolutely any server in the future but we're not there quite yet.
