### ISSUE TITLE
inline links with query params are not rewritten

### ISSUE THREAD

**Issue by rburgst** [gatsbyjs/gatsby-source-wordpress-experimental#273]
In case I have an html field that contains links with a `?` these URLs are not properly being rewritten: 

```
"myField": "<p>There is a non-rewritten <a href="http://wordpressurl/page?page=0">Link</a>..."
```

This would be fixed by https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/pull/262

**Comment by TylerBarnes** [comment]
Thanks for identifying this and opening that PR with a fix! I have this on my todolist to test, merge, and ship. Thanks again :D

**Comment by TylerBarnes** [comment]
This is published in `gatsby-source-wordpress-experimental@3.1.2`. Thanks @rburgst !
