### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fabianwohlfart** [gatsbyjs/gatsby-source-wordpress-experimental#277]
Hey!
Is there roadmap towards when you hope to get this out of beta into stable?
Keep up the good work!
F

**Comment by TylerBarnes** [comment]
Hi @fabianwohlfart there is no roadmap posted explicitly but I'm tracking work towards shipping the stable release with this tag https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues?q=is%3Aissue+is%3Aopen+label%3A%22address+before+stable+release%22+sort%3Acreated-asc

☝️ that + an overhaul on Docs is what needs to be finished before we can launch a stable release.
