### ISSUE TITLE
gatsby-source-wordpress  Unrecoverable error occured while fetching media item #21583 in step:  "Fetching referenced MediaItem nodes by id"

### ISSUE THREAD

**Issue by MussadiqKhan** [gatsbyjs/gatsby-source-wordpress-experimental#288]
Hello @TylerBarnes ,

I am working on a project and I am continuously getting this error. Can you please take a look at it?

> gatsby-source-wordpress  Unrecoverable error occured while fetching media item #21583 in step:

> "Fetching referenced MediaItem nodes by id"

Repo: https://github.com/MussadiqKhan/good-light

p.s. I am using WP-Graphql version 0.15.5. Using the latest v1.0 threw an error saying that Gatsby-source-wordpress should be updated to latest version. However. I was using the latest version. I double checked from npm and github.

**Comment by TylerBarnes** [comment]
Hi @MussadiqKhan , is there any other output in your terminal?

**Comment by TylerBarnes** [comment]
btw there's a new release (just published) which adds support for WPGraphQL 1.0.0. But that should be unrelated to this

**Comment by MussadiqKhan** [comment]
@TylerBarnes here's the complete output:

Media item link: https://verygoodlight.com/2020/10/13/alleyoop-review/alleyoop_multimood_gif_web_500x2x/
Edit link: https://verygoodlight.com/wp-admin/upload.php?item=21583
File url: https://media.verygoodlight.com/wp-content/uploads/2020/10/alleyoop_multimood_gif_web_500x%402x.gif      

Failing the build to prevent deploying a broken site.
error There was an error
not finished source and transform nodes - 314.078s
not finished  gatsby-source-wordpress  fetching nodes - 313.933s - 2595 total
not finished  gatsby-source-wordpress  creating nodes - 185.995s
not finished  gatsby-source-wordpress  MediaItem - 185.996s - fetched 96
not finished Downloading remote files - 164.681s
not finished Generating image thumbnails - 164.651s

**Comment by MussadiqKhan** [comment]
@TylerBarnes Did you take a look?

**Comment by MussadiqKhan** [comment]
@TylerBarnes I am waiting for an update. I am stuck here and time is running out.

**Comment by TylerBarnes** [comment]
@MussadiqKhan I'm having a look now

**Comment by TylerBarnes** [comment]
@MussadiqKhan it appears your server is returning 403 responses after some time. You likely have a firewall or security plugin which is causing this. The problem here was that the underlying `got` library is throwing custom errors that weren't being properly caught and were swallowed along the way so no error was output. 

If you upgrade to `gatsby-source-wordpress-experimental@3.0.1` you should see the 403 errors being logged after some time.
