### ISSUE TITLE
Feature Request: Send custom headers to the graphql endpoint

### ISSUE THREAD

**Issue by jonlow** [gatsbyjs/gatsby-source-wordpress-experimental#29]
I'd love to be able to add custom headers to the config that get passed to the graphql endpoint:

eg

```
headers: {
  myheader: "hey there"
}

```

**Comment by TylerBarnes** [comment]
Thanks for this feature request @jonlow , I agree that this would be good to have. I'll add this in soon. Thanks again!

**Comment by TylerBarnes** [comment]
I was thinking about this a bit more and I'm not sure if this is a good idea actually 🤔 It's dangerous to add authentication headers as if someone adds them and they get added to a Preview instance (either self-hosted or on Gatsby Cloud), all private data will be publicly available on that Preview instances GraphQL endpoint. What's your use-case @jonlow ? Maybe there's another good use-case here and I could just strip auth headers from being passed through 🤔

**Comment by TylerBarnes** [comment]
Hi @jonlow , I'm going to close this for now as I can't think of a good use-case (not that there isn't one though). Please re-open or comment here when you have time.

Thanks again!
