### ISSUE TITLE
Unable to update after new versions of WP GraphQL / WP Gatsby are released

### ISSUE THREAD

**Issue by MobyDigg** [gatsbyjs/gatsby-source-wordpress-experimental#290]
I first updated WP GraphQL / WP Gatsby to a new version and then changed the version of gatsby-source-wordpress-experimental in my repo, which I then pushed to Gatsby Cloud. I had incremental builds on (with the respective `gatsby-plugin-netlify-cache` plugin and `GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages;` for the build command).

**Problem:**

```
gatsby-source-wordpress  Your remote version of WPGraphQL is not within the accepted range (>=0.14.0 <0.16.0).

If the version of WPGraphQL in your WordPress instance is higher than 0.16.0
it may mean you need to upgrade your version of gatsby-source-wordpress.

If the version of WPGraphQL in your WordPress instance is lower than 0.14.0
it means you need to upgrade your version of WPGraphQL.

You can find a matching WPGraphQL version at https://github.com/wp-graphql/wp-graphql/releases

Your remote version of WPGatsby is not within the accepted range (>=0.5.4 <0.6.0)

If the version of WPGatsby in your WordPress instance is higher than 0.6.0
it may mean you need to upgrade your version of gatsby-source-wordpress.

If the version of WPGatsby in your WordPress instance is lower than 0.5.4
it means you need to upgrade your version of WPGatsby.

Download a matching version at https://github.com/gatsbyjs/wp-gatsby/releases
or update via https://eham.wpengine.com/wp-admin/plugins.php

For more details see https://gatsby.dev/issue-how-to
```

…although I updated my package.json to gatsby-source-wordpress@^3.0.0. Even after I hit "Clean cache and rebuild" on Gatsby Cloud, it wouldn't update gatsby-source-wordpress-experimental. When I exclude `GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true` from my build command, I am able to rebuild. Later I could reimplement the incremental builds again.

**Expected behavior:**

- gatsby-source-wordpress-experimental should check the package.json first, to see if an update of the package is necessary, before it throws the error.

**Comment by TylerBarnes** [comment]
Hi @MobyDigg, your remote plugin versions will need to be in range for your currently installed version of the source plugin at build time. For security reasons, we can't determine what the exact remote versions of WPGatsby and WPGraphQL are, so we provide that generic error explaining how to determine what you need to do next. In all cases, you'll need to take manual steps to resolve this error.
As a side note, Netlify doesn't have incremental builds, they call their cache plugin and that experimental API incremental builds for marketing reasons but you'll need to use Gatsby Cloud for incremental builds. If you're running into a bug with that experimental API, we wont be able to support that.
