### ISSUE TITLE
Error: gatsby-source-wordpress | self signed certificate

### ISSUE THREAD

**Issue by dschibbb** [gatsbyjs/gatsby-source-wordpress-experimental#292]
Hello,

i use gatsby-wordpress in a docker environment, locally i use traefik to create my SSL certificates. 
The problem is the following error: 

```
gatsby develop

error  gatsby-source-wordpress  self signed certificate

GraphQL request to https://dw-wordpress.localhost/graphql failed.

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests
  - WPGraphQL and WPGatsby are installed in your WordPress backend
not finished createSchemaCustomization - 0.135s
```

When I call up the URL in my browser it works. Apparently gatsby has a problem with self created certificates?!
The plugins were also installed and activated.

Any idea?

**Comment by TylerBarnes** [comment]
I believe this is actually node rejecting it. You should be able to set `process.env.NODE_TLS_REJECT_UNAUTHORIZED` to 0 to get around it. But is there even a reason to use https on localhost? It's probably easier to just use http for your local dev sites.
