### ISSUE TITLE
"warning gatsby-source-wordpress Unable to find a single Node query for PaymentGateway" after plugins upgrade 

### ISSUE THREAD

**Issue by emilianoglucero** [gatsbyjs/gatsby-source-wordpress-experimental#297]
Hello

I'm getting this error since I have upgraded WPgraphQL, WPGatsby and gatsby-woordpress-experimental plugin to the latest versions today. 
The 'paymentGateways' node is not available in my schema.

```
warning  gatsby-source-wordpress  Unable to find a single Node query for PaymentGateway
        This type will not be available in Gatsby.
```

I'm using Woocommerce + Wordpress.
Any clue?
Thanks in advance.

**Comment by TylerBarnes** [comment]
Hi there, this warning has always been around for WooCommerce because that type doesn't have a single node root field. Odd that you weren't seeing it before because this has always been the case. 🤔

**Comment by emilianoglucero** [comment]
Thanks for your reply!
You're right. 
The problem was a multicurrency plugin I had used.
