### ISSUE TITLE
wpMediaItem.localFile.url returns the raw remote URL instead of the locally downloaded file

### ISSUE THREAD

**Issue by chrispytoes** [gatsbyjs/gatsby-source-wordpress-experimental#298]
I am trying to get my media files downloaded to reference them locally. Most of the media files are PDFs. I can see that all my media files are being downloaded because I can see them in the `.cache` folder, but when I query any media files in GraphQL, the URLs point to the remote WordPress site instead of the Gatsby site.

Here's my plugin config:
```
{
	resolve: `gatsby-source-wordpress-experimental`,
	options: {
		url: `https://wp.example.com/graphql`,
		html: {
			createStaticFiles: true
		}
	},
}
```

When I use this query:
```
query MyQuery {
  wpMediaItem {
    localFile {
      url
      relativePath
    }
    sourceUrl
    mediaItemUrl
  }
}
```

This is the result:
```
{
  "data": {
    "wpMediaItem": {
      "localFile": {
        "url": "https://wp.example.com/wp-content/uploads/2020/11/ex-brd-032613-min.pdf",
        "relativePath": ".cache/caches/gatsby-source-wordpress-experimental/bb4e3f5bedefbb1d8e2bfeb679151c43/ex-brd-032613-min.pdf"
      },
      "sourceUrl": null,
      "mediaItemUrl": "https://wp.example.com/wp-content/uploads/2020/11/ex-brd-032613-min.pdf"
    }
  },
  "extensions": {}
}
```

As you can see, the relative path does come back with the locally cached file, but the URLs point at the WordPress site instead of `localhost:8000`. Is there more I need to do to get my media files served by Gatsby?

**Comment by TylerBarnes** [comment]
You're looking for `WpMediaItem.localFile.publicURL`! That should do it :D

**Comment by chrispytoes** [comment]
@TylerBarnes Thanks, now that brings up another issue: I don't have a `publicURL` field.

**Comment by TylerBarnes** [comment]
I think I mis-spoke. I remember that field but now I don't see it either. I do see this though:

```graphql
{
  wpMediaItem {
    localFile {
      childImageSharp {
        original {
          src
        }
      }
    }
  }
}
```

```json
{
  "data": {
    "wpMediaItem": {
      "localFile": {
        "childImageSharp": {
          "original": {
            "src": "/static/image-alignment-580x300-1-539c0066996ddbcc605b6947b35b041e.jpg"
          }
        }
      }
    }
  },
  "extensions": {}
}
```

**Comment by chrispytoes** [comment]
@TylerBarnes Yeah, that's my problem. These are PDFs, not images. The `childImageSharp` field is null on PDF files.

**Comment by TylerBarnes** [comment]
Ah, I missed that part! Do you have a /graphql endpoint I can look at?

**Comment by chrispytoes** [comment]
@TylerBarnes [https://k3vet.webfoot-designs.com/graphql](https://k3vet.webfoot-designs.com/graphql)

**Comment by TylerBarnes** [comment]
Ahh, you'll need to add `gatsby-source-filesystem` which will add the publicURL field.

```
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `assets`,
        path: `${__dirname}/content/assets`,
      },
    },
```

It looks like you need to point it at some files for it to setup that plugin properly, so you'll want to point it at a single dummy image for now if you don't have any image files in your Gatsby site repo. I think it doesn't make sense for that plugin to require a path be passed to it since we need it here just for the publicURL field 🤔 So I'm going to think on that a bit and see what I can come up with. For now that will work though 👍

**Comment by chrispytoes** [comment]
@TylerBarnes Thank you! That works. I was aware of the `gatsby-source-filesystem` plugin but it doesn't seem to be documented anywhere that it was required for this functionality even if you're not using it.

I wouldn't be surprised if others had this same problem. Thanks for your help.

**Comment by TylerBarnes** [comment]
I wasn't able to find that either, I'll re-open this and mark it as documentation to make sure we add a note about this.

**Comment by TylerBarnes** [comment]
This was documented here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/features/media-item-processing.md#referencing-static-file-public-urls
