### ISSUE TITLE
Since upgrading to 3.0.0, incremental builds leave most content 404ing

### ISSUE THREAD

**Issue by jdselig** [gatsbyjs/gatsby-source-wordpress-experimental#299]
Hey guys, 

Yesterday we upgraded to 3.0.0, but now we're seeing a strange issue where once a WP content change triggers and incremental build, nearly all URLs on our site lead to 404s. Nothing is obviously wrong in the logs, but this seems to happen with any incremental build. A full redeploy fixes the issue though. Has anyone else seen anything similar? Any and all advice is appreciated—we were planning to launch tomorrow 😅

Thank you!

**Comment by TylerBarnes** [comment]
Hi @jdselig sorry about that! Update to `gatsby-source-wordpress-experimental@3.0.2` for a fix!

**Comment by TylerBarnes** [comment]
Closing but please feel free to re-open or comment here if it didn't solve your issue.
