### ISSUE TITLE
Request failed with status code 530 

### ISSUE THREAD

**Issue by samuelhawley1992** [gatsbyjs/gatsby-source-wordpress-experimental#303]
When using 'https://live-gatbsyjswp.pantheonsite.io/graphql' as the URL in gatsby-config.js (as per the quick start in gatsby-source-wordpress-experimental), I get notified with a request failed with status code 530 error.

My logs:
![image](https://user-images.githubusercontent.com/18509440/99673355-9efdab00-2aaf-11eb-897c-c62ff23b48ef.png)

My gatsby-config.js file
![image](https://user-images.githubusercontent.com/18509440/99673568-e7b56400-2aaf-11eb-8dec-96909497f8cb.png)

Is this due to a server error? Or am I doing something wrong here?

**Comment by TylerBarnes** [comment]
Hi @samuelhawley1992 , I've updated the url there to a working demo site. FYI the tutorials and docs are not the greatest currently and are out of date in some places. We're currently working on finishing up a few critical bugs and then moving on to a huge documentation push.
