### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined 

### ISSUE THREAD

**Issue by znwhite** [gatsbyjs/gatsby-source-wordpress-experimental#305]
This is coming from line 739 of [this](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/plugin/src/steps/source-nodes/create-nodes/process-node.js) file:

```
        if (!relativeUrl || !mediaItemNode || !fileNode) {
          return null
        }

        const mediaItemMatchGroup = mediaItemUrlsAndMatches.find(
          ({
            matchGroup: {
              subMatches: [_delimiter, _hostname, path],
            },
          }) => mediaItemNode.mediaItemUrl.includes(path)
        )?.matchGroup

        if (!mediaItemMatchGroup) {
          return null
        }
```

For now I'm just going to return `null` for `mediaItemMatchGroup` instead of letting this function continue, because it's not allowing my site to build even though I haven't changed anything. But if this could be refactored to contain a null check on the `mediaItemNode.mediaItemUrl` that would probably help avoid this problem in the future. Not sure what the best practice here would be.

**Comment by znwhite** [comment]
Nevermind, this issue is persisting. Some help would be appreciated

**Comment by TylerBarnes** [comment]
Hi @znwhite if you can share a reproduction /graphql url and Gatsby site repo I can take a look.
Thanks!

**Comment by znwhite** [comment]
@TylerBarnes ok thank you, just sent you an email.

**Comment by TylerBarnes** [comment]
This is fixed in `gatsby-source-wordpress-experimenta@5.0.1`. Thanks for the reproduction @znwhite , that was super helpful!

**Comment by znwhite** [comment]
@TylerBarnes No problem, thanks for jumping on the fix
