### ISSUE TITLE
ACF not registered on gatsby-source-wordpress-experimental

### ISSUE THREAD

**Issue by muhrusdi** [gatsbyjs/gatsby-source-wordpress-experimental#309]
Hy, i have found some issue, i created a menu called Featured Product using the CPT UI plugin, then I created some fields using ACF with the field group name is featuredProductField, the problem is featuredProductField is not registered in the gatsbyjs schema

featuredProductField registerd in the wpgraphql schema
![wpgraphql](https://user-images.githubusercontent.com/9457288/99948223-17b47e00-2db4-11eb-984a-35f484613ed6.PNG)

featuredProductField not registerd in the gatsby schema
![gatsby-wpgraphql](https://user-images.githubusercontent.com/9457288/99948265-2b5fe480-2db4-11eb-9171-fbc94cbf8be7.PNG)

package:
- gatsby-source-wordpress-experimental@v4
- wpgraphql v1
- WPGraphQL Custom Post Type UI
- WPGraphQL for Advanced Custom Fields

**Comment by TylerBarnes** [comment]
Hi @muhrusdi , in order to debug this we'll need a reproduction /graphql url and a Gatsby site repo. Thanks!

**Comment by muhrusdi** [comment]
can you debug this for me. Thanks
graph url: https://qamasystore.mhmr.digital/graphql

**Comment by zamson** [comment]
@muhrusdi have you tried running gatsby clean?

**Comment by muhrusdi** [comment]
fixed in gatsby-source-wordpress-experimental v5.0.2 & WPGraphQL v1.0.2

**Comment by TylerBarnes** [comment]
Woo :D Glad to hear it, thanks for letting us know @muhrusdi !
