### ISSUE TITLE
Bump supported remote plugin versions to support WPGraphQL v0.10.1

### ISSUE THREAD

**Issue by HumidBrains** [gatsbyjs/gatsby-source-wordpress-experimental#31]
When using WPGraphQL v0.10.1 with gatsby-source-wordpress-experimental 0.7.14 a build error gets thrown saying "our remote version of WPGraphQL is not within the accepted range".

**Comment by muhzulzidan** [comment]
try to update wpgraphql ?  and the wordpress

**Comment by adel0559** [comment]
The issue seems to be that there has been a major update to WPGraphQL and this project (along with https://github.com/gatsbyjs/wp-gatsby I guess) are not compatible with the new version. It's not entirely clear which versions are actually supposed to be compatible with each other, does anyone know?

**Comment by HumidBrains** [comment]
> The issue seems to be that there has been a major update to WPGraphQL and this project (along with https://github.com/gatsbyjs/wp-gatsby I guess) are not compatible with the new version. It's not entirely clear which versions are actually supposed to be compatible with each other, does anyone know?

Not aware of how all possible versions work together, but to my knowledge and experience with WP Multisite, the working combos look like this...

**WORKING COMBINATIONS**

**Normal WordPress site:**
WPGraphQL < v0.10.0 works with gatsby-source-wordpress-experimental < v0.8.0
WPGraphQL > v0.10.0 works with gatsby-source-wordpress-experimental > v0.8.0

**WordPress Multisite:**
WPGraphQL < v0.10.0 works only with gatsby-source-graphql. 
The reason is that in previous version of WPGraphQL, the url wasn't avaulable on generalSettings for multisites (see https://github.com/wp-graphql/wp-graphql/issues/1334, but was required by gatsby-source-wordpress-experimental (see #23 ). That mismatch is fixed with combining the latest versions.

The only combo feasible for using gatsby-source-wordpress-experimental with WP Multisite is...
WPGraphQL > v0.10.1 together with gatsby-source-wordpress-experimental > v0.8.0

Hope this helps :)

**Comment by TylerBarnes** [comment]
Hey everyone! The latest release supports WPGraphQL 0.10.* `gatsby-source-wordpress-experimental@0.8.1`.

I think the error messaging is a bit confusing if the remote WP plugins are a newer version than what's supported so we'll have to look at that. Opened a new issue to track that here https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/35
