### ISSUE TITLE
Add support for REFETCH_ALL action type

### ISSUE THREAD

**Issue by jasonbahl** [gatsbyjs/gatsby-source-wordpress-experimental#315]
WordPress should be able to send a webhook to notify the source to REFETCH_ALL. This could be triggered by a button in the WP Admin or by various actions such as database migrations or major plugin updates, etc. 

Also see: https://github.com/gatsbyjs/wp-gatsby/issues/58

**Comment by smthomas** [comment]
Thank you for opening this issue. We recently moved this plugin over to the gatsbyjs monorepo and are trying to clean out this issue queue. We documented this feature to look at for a future roadmap item and are going to close this issue out. If you want to add additional visibility to this feature, you can request it at https://portal.gatsbyjs.com/
