### ISSUE TITLE
Wordpress updates cause the GraphQL schema to loose inferred types of remote nodes

### ISSUE THREAD

**Issue by stupearce** [gatsbyjs/gatsby-source-wordpress-experimental#318]
V3.1.3.
To emulate:
Running Gatsby develop (as used by preview) when build completes, any remote nodes (our bookingGraph node in this case) are present on the graph and can be seen in the playground alongside the WP types.
However go to Wordpress Admin Press and update a page then a build is triggered and this results in the remote node (our bookingGraph Node) disappearing and the build fails with Cannot query field "bookingGraph" on type "Query" as this is required in our pageQuery.
Once this happens it will never recover.

**I can prevent this by removing the following from 'steps/source-nodes/update-nodes/wp-actions/update.js':**
```
  // await (0, _customizeSchema.customizeSchema)({
  //   parentSpan: null,
  //   deferNodeMutation: true,
  //   refresh: false,
  //   ...args
  // });
```

page query:

```js
export const pageQuery = graphql`
  query($id: String!, $propId: Int! ) { 
    wpProperty(id: { eq: $id }) {
      id
      content
     ....other stuff
    }
    bookingGraph {
      getProperty(id: $propId) {
        ...propertyFragments
      }
    }
...... other stuff
}
```

gatsby.config.js excerpt:
```js
    {
      resolve: "gatsby-source-graphql",
      options: {
        typeName: "BookingGraph",
        fieldName: "bookingGraph",
        url: `${process.env.GATSBY_GRAPH_ADDR}/graphql`,
      },
    },
```
----

**Comment by TylerBarnes** [comment]
Hi @stupearce , can you share a screenshot or copy paste the error you're seeing when this happens?

Thanks!

**Comment by TylerBarnes** [comment]
Ahh, that's also the config for `gatsby-source-graphql` not `gatsby-source-wordpress-experimental`. Are you running both plugins and if so can you copy the config for this plugin?

**Comment by stupearce** [comment]
{
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: `${process.env.GATSBY_CMS_ADDR}/wp/graphql`,
        debug: {
          graphql: {
            writeQueriesToDisk: true,
          },
        },
        develop:{
          hardCacheMediaFiles: true,
        },
        type: {
          MediaItem: {
            //default is false
            lazyNodes: false,
          },
          Property: {
            limit:
              process.env.NODE_ENV === `development`
                ? // Lets just pull 50 posts in development to make it easy on ourselves (aka. faster).
                20
                : // and we don't actually need more than 5000 in production for this particular site
                200,
          },
        },
        schema: {
          timeout: 90000,
          perPage: 10,
        },
      },
    },

**Comment by TylerBarnes** [comment]
A fix is published in `gatsby-source-wordpress-experimental@3.3.0`! Thanks for opening this issue @stupearce
