### ISSUE TITLE
Build error on WP Multisite

### ISSUE THREAD

**Issue by HumidBrains** [gatsbyjs/gatsby-source-wordpress-experimental#32]
**Using:**
WPGraphQL v0.10.1
WPGatsby 0.4.1
gatsby-source-wordpress-experimental 0.7.14
WordPress Multisite + Woo 5.4.2
PHP 7.3.18
gatsby 2.23.12

Before migrating from gatsby-source-graphql I decided to start from scratch with this guide https://bit.ly/2BTyVv1
I got to the first build when I run into this...

**ERROR**
Interface field WpHierarchicalContentNode.wpParent expected but WpMediaItem does not provide it.
Type WpHierarchicalContentNodeToContentNodeConnectionEdge must define one or more fields.
Interface field WpHierarchicalContentNode.wpParent expected but WpPage does not provide it.
Type WpNodeWithRevisionsToContentNodeConnectionEdge must define one or more fields.

  Error: Interface field WpHierarchicalContentNode.wpParent expected but WpMediaItem does not provide it.
  Type WpHierarchicalContentNodeToContentNodeConnectionEdge must define one or more fields.
  Interface field WpHierarchicalContentNode.wpParent expected but WpPage does not provide it.
  Type WpNodeWithRevisionsToContentNodeConnectionEdge must define one or more fields.

@TylerBarnes is this an error you might have a cure for? :)

**Comment by AdrianLuk** [comment]
I experienced this too. Because wpgraphql 0.10.1 has many breaking changes and new features compared to 0.9.1, this plugin has not been updated accordingly. 
I personally downgrades wpgraphql to 0.9.1 to fix this issue until this plugin gets updated.

**Comment by TylerBarnes** [comment]
Hey there! I just put out a new release with support for v0.10.0~ in `gatsby-source-wordpress-experimental@0.8.0`.
