### ISSUE TITLE
Post preview failed when no changes are made.

### ISSUE THREAD

**Issue by hazuremon** [gatsbyjs/gatsby-source-wordpress-experimental#320]
Thanks @TylerBarnes on rewriting the WP post preview, it's now functional in most situations but notice it still failed on certain situation.

1. Generating a preview on draft post with no content changes will return with error in WordPress
2. Preview after "Save Draft" will display Gatsby cloud error message in WordPress
3. Generating a second preview on draft post right after a successful preview will return with error in WP.

Gatsby error message in WP:  "The Gatsby Preview webhook was not successfully called."
Post status: Draft post
Note: Suspect above three situations have similar condition where it return a preview, if there are no content changes to a previous preview built.

On latest version of gatsby-source-wordpress-experimental: 3.2.0 and WP-Gatsby: 0.6.6

**Comment by TylerBarnes** [comment]
Thanks @hazuremon , that's really helpful! Can you share your Gatsby Cloud dashboard URL with me so I can take a look at your logs? It will be private to anyone who tries to visit the link but I have magic Gatsby powers so I can get in 😆

**Comment by hazuremon** [comment]
https://www.gatsbyjs.com/dashboard/bdd12c57-3dec-416e-80f8-a407b740e012/sites/8fb53603-2435-4182-b550-257ee3e524bc/deploys

**Comment by hazuremon** [comment]
Thanks Tyler!

To provide a bit more information, these preview will build successfully in Gatsby Cloud, but WordPress will display Gatsby error message before the preview has finished building.

**Comment by hazuremon** [comment]
I have updated the issue, as it was a bit unclear after reading it again.

**Comment by TylerBarnes** [comment]
@hazuremon I've identified the problem and we'll be releasing a fix tomorrow. See https://github.com/gatsbyjs/wp-gatsby/pull/64 for more info :)

**Comment by TylerBarnes** [comment]
https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/pull/323 improves the draft preview experience as well and should be released tomorrow.

**Comment by TylerBarnes** [comment]
A fix for this is published in `gatsby-source-wordpress-experimental@3.3.1`. Please let me know if you see any similar issues, or if your problem wasn't fixed and we can re-open this.

**Comment by TylerBarnes** [comment]
Actually, I guess the fix for this is in WPGatsby v0.6.7 :) but both new versions have improvements to new draft previews.

**Comment by hazuremon** [comment]
Thank Tyler, thanks for fixing it quickly. It fixes all the conditions above, thank you!

**Comment by TylerBarnes** [comment]
Woo :D that's great to hear! Let me know if you run into any other problems. I feel like preview is getting really solid so if you find anything else I want to squash it right away haha
