### ISSUE TITLE
PNG with transparency don't display correctly

### ISSUE THREAD

**Issue by pehaa** [gatsbyjs/gatsby-source-wordpress-experimental#33]
Hi,
It seems that the way that gatsby images are managed does not work well with pngs with transparency.
As far as I understand how it works, the "data/image" image is displayed underneath the final image. But in the case of images with transparency the blurred parts are still visible. I attach a screenshot and a link to the [demo](https://inspiring-sammet-8d936c.netlify.app/) - (very bottom of the page).
<img width="514" alt="Screenshot 2020-07-02 08 36 17" src="https://user-images.githubusercontent.com/774920/86324648-2b155000-bc3f-11ea-8d2f-faf0d343fdc1.png">
In the screenshot below I hide the "data/image" with `display: none` so that you can see how it should be displayed.
<img width="1083" alt="Screenshot 2020-07-02 08 40 15" src="https://user-images.githubusercontent.com/774920/86324992-ad057900-bc3f-11ea-8466-881f7ae1530a.png">

**Comment by TylerBarnes** [comment]
Thanks for this bug report. Is this image in inline html or in a custom field? Can you share a reproduction repo that I can use to debug?

Thanks!

**Comment by pehaa** [comment]
It's a Gutenberg image element, the wp demo url is https://wp-pehaa.xyz/ginger-kitchen/

**Comment by TylerBarnes** [comment]
I believe this is fixed in `gatsby-source-wordpress-experimental@0.8.6`. Can you try it and let me know?

Thanks!

**Comment by pehaa** [comment]
It works ! checked with gatsby-source-wordpress-experimental@0.8.6 and pngs display correctly. Thank you for your great work!
