### ISSUE TITLE
SVG images don't display, svg extension targets png files

### ISSUE THREAD

**Issue by pehaa** [gatsbyjs/gatsby-source-wordpress-experimental#34]
On my WordPress site, I use svg images (I add support for svg with the Safe SVG WordPress plugin)
The SVGs don't display on Gatsby website.
You can see the [demo here](https://inspiring-sammet-8d936c.netlify.app/) - header part
I checked the generated svg files in the static folders and they are in fact pngs with .svg extension.
You can [see the screencast here](https://wptemplates.pehaa.com/assets/svg-png.mp4)

**Comment by muhzulzidan** [comment]
https://inspiring-sammet-8d936c.netlify.app/static/f8559130b5924b4dcde9a020d59ba443/016df/ginger-white.svg

when I open the SVG in a new tab, it says no styles.. so it can't be opened..

**Comment by pehaa** [comment]
yes exactly, you can't check it on-line, I guess. I checked it in my local build static files (have you seen the screencast?)

**Comment by muhzulzidan** [comment]
so, it is not tranformed to svg correctly ? can we see the comparison of svg in the real file (wp) and the one that is send to gatsby (local) ?

**Comment by TylerBarnes** [comment]
Yeah it looks like that svg is being run through Sharp & gatsby-image. Can you share a reproduction repo so I can use it to debug?

Thanks!

**Comment by pehaa** [comment]
It's https://wp-pehaa.xyz/ginger-kitchen/

**Comment by TylerBarnes** [comment]
Can you try out `gatsby-source-wordpress-experimental@0.8.5` and let me know if it fixes the issue?

Thanks!

**Comment by pehaa** [comment]
Hi, checked with `gatsby-source-wordpress-experimental@0.8.5` and it works! Thanks !!!!
