### ISSUE TITLE
Refresh endpoint stop working during local development

### ISSUE THREAD

**Issue by Lornz-** [gatsbyjs/gatsby-source-wordpress-experimental#341]
Hi there! First, thanks a lot for all the hard work you put through for making Web Development more exciting than ever 🙏 Gatsby + Wordpress = 🚀🤯

Lately, I upgraded the current from version **3.1.3** to **4.0.0** and also _WP Gatsby_ from **0.6.8** to the latest in order to make them work together in one of my projects I work on. Surprisingly, I've noticed the endpoint stopped refreshing after any content changes in Wordpress during local development even with `ENABLE_GATSBY_REFRESH_ENDPOINT=true` set in my `.env.development` file. 

**What I did?**
Make remote changes on an existing post and update content.
Create a fresh new post and publish.

**What I expect?**
It supposed to trigger a new build whenever remote data changes.

**What I got?**
No re-build triggered. No error logs. 

**What I tried?**
Downgrade until a version that works for me based on my setup. Same problem occurred.
It did actually work though when I manually triggered the endpoint by doing `curl -X POST http://localhost:8000/__refresh` in terminal. 🤔

gatsby-config:
```
require('dotenv').config({
  path: `.env.${process.env.NODE_ENV}`,
});


module.exports = {
   plugins: [
     {
        resolve: `gatsby-source-wordpress-experimental`,
        options: {      
           url: process.env.WPGRAPHQL_URL,
           html: {
              useGatsbyImage: true,
           },
        },
     },

    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
   `gatsby-plugin-react-helmet`,
  ],
}
```

I couldn't find any similar issues so I don't really know if It's a bug or something I messed up in some way but still, I miss that interesting feature 😅 Any thoughts would be greatly appreciated.

**Comment by TylerBarnes** [comment]
Hi @Lornz- I think you're referring to the content updates that happen which happen outside of the refresh endpoint and are now disabled when the refresh endpoint is enabled. The refresh endpoint is just for previews and production content updates. In development you should run `gatsby develop` with the refresh endpoint disabled and you'll see content update automatically.

**Comment by Lornz-** [comment]
@TylerBarnes Yup that's exactly it! I removed it and it works like a charm now. Thanks for the clear explanation ✨ Have a good one!

**Comment by TylerBarnes** [comment]
Yay, glad to hear it's working now :D you have a good one too!
