### ISSUE TITLE
Remote Version Not Within Accepted Range

### ISSUE THREAD

**Issue by ibjorn** [gatsbyjs/gatsby-source-wordpress-experimental#342]
Earlier I updated WPGatsby to 0.7.2. Afterwards I started getting build errors and proceeded to follow the suggestions and updated my gatsby-source-wordpress-experimental to 3.3.1.

Unfortunately I'm unable to get past this build error. 

I've deleted my node_modules folder and package-lock,json and done a fresh install. I also completely removed WPGatsby and reinstalled, as well as upgraded everything that was willing and able to upgrade.

However, this little guy just won't go away:

```
error  gatsby-source-wordpress  Your remote version of WPGatsby is not within the accepted range (>=0.6.0 <0.7.0)

If the version of WPGatsby in your WordPress instance is higher than 0.7.0
it may mean you need to upgrade your version of gatsby-source-wordpress.

If the version of WPGatsby in your WordPress instance is lower than 0.6.0
it means you need to upgrade your version of WPGatsby.

Download a matching version at https://github.com/gatsbyjs/wp-gatsby/releases
or update via https://api.blackalsatian.co.za/wp-admin/plugins.php

not finished createSchemaCustomization - 1.821s
not finished  gatsby-source-wordpress  ensuring plugin requiremenst are met - 1.822s 
```

My package,json:

```json
 "dependencies": {
    "@emotion/react": "^11.1.1",
    "@theme-ui/components": "^0.3.4",
    "@theme-ui/tailwind": "^0.3.4",
    "gatsby": "^2.28.0",
    "gatsby-image": "^2.7.0",
    "gatsby-plugin-manifest": "^2.8.0",
    "gatsby-plugin-offline": "^3.6.0",
    "gatsby-plugin-react-helmet": "^3.6.0",
    "gatsby-plugin-sharp": "^2.10.0",
    "gatsby-plugin-theme-ui": "^0.3.4",
    "gatsby-source-filesystem": "^2.7.0",
    "gatsby-source-wordpress-experimental": "^3.3.1",
    "gatsby-theme-style-guide": "^0.3.4",
    "gatsby-transformer-sharp": "^2.8.0",
    "html-react-parser": "^0.14.2",
    "lodash": "^4.17.20",
    "normalize.css": "^8.0.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^5.2.1",
    "theme-ui": "^0.3.4",
    "typeface-montserrat": "1.1.13"
  },
  "devDependencies": {
    "dumper.js": "^1.3.1",
    "prettier": "2.1.2"
  },
```

Besides WP Gatsby 0.7.2, on WP side I also have the following installed:

```
WP GraphiQL 1.0.1
WP GraphQL 1.0
WP GraphQL Gutenberg 0.3.5	
WPGraphql Yoast Seo 4.1.0
```

Am I missing something? Should I perhaps downgrade my WPGatsby plugin? Hopefully it's something as simple as the conditional checking the version numbers wanting some attention?

**Comment by TylerBarnes** [comment]
Hi @ibjorn I think you might've upgraded right in the middle of our release process in the few minutes between when the latest release for everything published. There's a newer version of the source plugin which will make this message go away :) It should be 4.0.0

**Comment by ibjorn** [comment]
I'm not even surprised.  I suspected something like that, but then I was like, "Nah, what are the chances?"

Thanks man!

**Comment by TylerBarnes** [comment]
I know right 😆 it's hard to believe when that kind of thing happens. The last chance for it was a few minute span probably over a month ago :p let me know if you're still having trouble after upgrading though 👍

**Comment by ibjorn** [comment]
It's 2020, nothing surprises me anymore! 😆

I came right thanks. Still trying to wrap my head around how to deal with blocks on a page. I can't find much insight in the best way to go about iterating through blocks on a page.

Thanks for all the amazing work on this! I can see a lot of improvements since I last fiddled with WP/Gatsby about 6 or so months ago.

**Comment by KeviinCosmos** [comment]
I also got this issue, on a fresh install today with the newest plugins installed. WP gatsby and WP graphql
![Code_2021-01-10_01-47-50](https://user-images.githubusercontent.com/35226855/104111724-e51fff80-52e5-11eb-92c2-819ed47186f4.png)

Using this repo: https://github.com/henrikwirth/gatsby-starter-wordpress-twenty-twenty

**Comment by MarvelMoe** [comment]
Hey guys, I know there was a recent update to the WPGatsby plugin but not sure why Im having the same issue -Your remote version of WPGatsby is not within the accepted range (>=0.6.0 <0.7.0)
I did  npm install gatsby-source-wordpress@latest and the lock file says its "version": "4.0.1"
The WP plugin is Version 1.0.1 
What am I missing here?

**Comment by TylerBarnes** [comment]
@MarvelMoe did you update the plugin name in gatsby-config.js from gatsby-source-wordpress-experimental to gatsby-source-wordpress? v4.0.1 supports [>=0.9.0 <2.0.0](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/supported-remote-plugin-versions.ts#L9)

**Comment by MarvelMoe** [comment]
<img width="311" alt="Screen Shot 2021-02-06 at 9 25 45 AM" src="https://user-images.githubusercontent.com/16159545/107125208-54ddc780-685d-11eb-9bee-6a878d8aea72.png">
@TylerBarnes Hi, yes I did...unless you're saying I should add that extra v4.0.1 supports >=0.9.0 <2.0.0 as well?

**Comment by MarvelMoe** [comment]
ok, so I installed gatsby-source-wordpress@4.0.0 and the error doesnt show anymore, but...this one does now:
  Error: Cannot find module 'gatsby-transformer-sharp/supported-extensions'
I deleted the node_modules and reinstalled them and installed some other packages mentioned here: https://github.com/gatsbyjs/gatsby/issues/4507

Any idea @TylerBarnes why its throwing this? Appreciate the help

**Comment by MarvelMoe** [comment]
I got it working...ended up doing the following:
npm install --save gatsby-transformer-sharp
npm install react  --save
npm uninstall react-dom 
npm install react-dom --save
