### ISSUE TITLE
vips_value_hash - core dump

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/gatsby-source-wordpress-experimental#348]
This error started happening after I updated to v5.0. @TylerBarnes Let me know if you need anything else. 

```
vips_value_hash: no case for NULL
        type 64, gchararray
        generic 53, GParamString
vips_value_hash: no case for 0.000000
        type 60, gdouble
        generic 109, GParamDouble
vips_value_hash: no case for FALSE
        type 20, gboolean
        generic 76, GParamBoolean
vips_value_hash: no case for ((VipsAccess) VIPS_ACCESS_RANDOM)
        type 114797264, VipsAccess
        generic 80, GParamEnum
vips_value_hash: no case for FALSE
        type 20, gboolean
        generic 76, GParamBoolean
Segmentation fault (core dumped)
```

 System:
    OS: Linux 4.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.1 - /tmp/yarn--1607304731540-0.1348554284489072/node
    Yarn: 1.22.10 - /tmp/yarn--1607304731540-0.1348554284489072/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  npmPackages:
    gatsby: ^2.27.4 => 2.27.4
    gatsby-image: ^2.6.0 => 2.6.0
    gatsby-plugin-feed: ^2.8.0 => 2.8.0
    gatsby-plugin-goatcounter: ^0.4.0 => 0.4.0
    gatsby-plugin-linaria: ^2.2.0 => 2.2.0
    gatsby-plugin-manifest: ^2.7.0 => 2.6.0-next.0
    gatsby-plugin-netlify: ^2.6.0 => 2.6.0
    gatsby-plugin-offline: ^3.5.0 => 3.5.0
    gatsby-plugin-postcss: ^3.2.0 => 3.2.0
    gatsby-plugin-preact: ^4.2.0 => 4.2.0
    gatsby-plugin-react-helmet: ^3.5.0 => 3.5.0
    gatsby-plugin-readingtime: ^1.0.1 => 1.0.1
    gatsby-plugin-robots-txt: ^1.5.3 => 1.5.3
    gatsby-plugin-sharp: ^2.9.1 => 2.9.1
    gatsby-plugin-sitemap: ^2.7.0 => 2.7.0
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-plugin-webpack-size: ^1.0.0 => 1.0.0
    gatsby-source-filesystem: ^2.6.1 => 2.6.1
    gatsby-source-wordpress-experimental: ^5.0.0 => 5.0.0
    gatsby-transformer-sharp: ^2.7.0 => 2.7.0

**Comment by KyleAMathews** [comment]
[vips](https://github.com/libvips/libvips) is the main library used by [sharp](https://www.npmjs.com/package/sharp) for image processing. So potentially not related to the wordpress plugin. We recently upgraded the version of sharp so that potentially surfaced some new bugs.

**Comment by moonmeister** [comment]
I believe I could build before upgrading only wp-experimental but I can do some more checks. Thank for the lead on vips.

**Comment by TylerBarnes** [comment]
Hey @moonmeister I saw this in my test site as well when installing an unrelated package. When I deleted node_modules and re-installed everything started working again. Are you still running into this?

**Comment by moonmeister** [comment]
confirmed.
