### ISSUE TITLE
WP url gets stripped from inline images

### ISSUE THREAD

**Issue by rasmuswoelk** [gatsbyjs/gatsby-source-wordpress-experimental#352]
I'm experiencing an issue where my inline images get stripped of the WP URL, leaving only the relative path to the image. E.g.:

![image](https://user-images.githubusercontent.com/640976/101649118-d1f5e780-3a3a-11eb-87f1-f718b0de4e37.png)

## Debug info
- I'm using the latest versions of all plugins
- Running a query directly on WordPress returns the content with the correct URLs
- Setting `useGatsbyImage` works (but it's not an option for me at the moment because of large build times)

## Reproduction
I created a repo that reproduces the error here:
https://github.com/rasmuswoelk/gatsby-source-wordpress-experimental-image-issue

Gatsby config:
https://github.com/rasmuswoelk/gatsby-source-wordpress-experimental-image-issue/blob/main/gatsby-config.js

Here is a live preview demonstrating the problem:
https://5fd0ed2e4b5a74000724899f--gallant-tereshkova-050a71.netlify.app/2020/12/09/hello-world

**Comment by TylerBarnes** [comment]
Hi @rasmuswoelk , sorry for the very delayed response - this was fixed in a later release. Please let me know if you're still running into this issue after upgrading.

Thanks!

**Comment by rasmuswoelk** [comment]
@TylerBarnes No worries. And thanks! I can confirm that this is fixed. Thank you for your great work!
