### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by rcapdepaula** [gatsbyjs/gatsby-source-wordpress-experimental#355]
A conceptual question, in relation to the previous version of the plugin, does the new version increase the final performance? (gatsty static files in production mode)?

**Comment by TylerBarnes** [comment]
Frontend performance is handled by Gatsby core so overall it should be similar except for one area which is Gatsby images in HTML fields. The old plugin didn't process those and this one does which should improve your frontend performance out of the box for any pages which use images in html fields (like post content, Gutenberg, or ACF wysiwyg fields).
