### ISSUE TITLE
Link to a Page not a Post

### ISSUE THREAD

**Issue by mawnir** [gatsbyjs/gatsby-source-wordpress-experimental#358]
I'm new to Gatsby.. i need to know How can i add a **Link to a Page not a Post.** 
from what i can see, the pages are not built in 'public/page-data' folder  
**should i do something to get the pages 'built'?**
Thank you

**Comment by rcapdepaula** [comment]
src/pages

**Comment by TylerBarnes** [comment]
@mawnir if you're using the current starter, it only builds pages for posts right now. If you want to build pages for any other types (like pages), you'll need to add some code to create those pages. See this guide for more info https://www.gatsbyjs.com/docs/programmatically-create-pages-from-data/#reach-skip-nav

**Comment by mawnir** [comment]
@TylerBarnes Please add this in future releases.. Thank you

**Comment by TylerBarnes** [comment]
We're planning on it :) thank you for your patience! Let me know if you get stuck too. Always happy to help
