### ISSUE TITLE
How can I use CDN for Media files.

### ISSUE THREAD

**Issue by dipankarmaikap** [gatsbyjs/gatsby-source-wordpress-experimental#363]
I've an AWS CDN set up for my sites media files, But when I do Gatsby develop or Gatsby build it still downloads files from the WordPress site not using the CDN. How can I use CDN for the media files.

**Comment by TylerBarnes** [comment]
Hi @dipankarmaikap , for MediaItem nodes you will need to make sure that WPGraphQL points to the CDN url for the `MediaItem.sourceUrl` field (or `MediaItem.mediaItemUrl` if sourceUrl isn't available). For images in html those will work as is but won't be transformed into optimized Gatsby images, if you want that feature please vote for it here https://portal.gatsbyjs.com/gatsby-cloud/p/gatsby-source-wordpress-allow-non-wp-hosted-images-in-html
