### ISSUE TITLE
Changes in Post meta data like Categories are not propagated to gatsby-graphql but appear in wp-graphql

### ISSUE THREAD

**Issue by insidesmart** [gatsbyjs/gatsby-source-wordpress-experimental#385]
When you update a category for a post, it reflects in wp-graphql but it is not reflecting in gatsby-graphql. When you create a new post with a category it works.

Naturally it is not picked up in gatsby-develop and gatsby-build steps.

If we do gatsby clean and try gatsby-build, it is picking up. This causes huge build time as we generate lot of images.

Gatsby-experimental Version - 6.0.0
Gatsby in latest version. Wordpress plugins are updated to the latest versions as well.

**Comment by TylerBarnes** [comment]
Hi @insidesmart how are you updating this post meta?

**Comment by TylerBarnes** [comment]
Since we haven't received a response in a while I'll close this issue - feel free to comment here or re-open if you're still running into this problem. There were a lot of fixes/changes in WPGatsby over the last few months that likely fixed this issue.

Thanks!
