### ISSUE TITLE
Setting "Image size" in "Elementor" to a size smaller than the original triggers 401 (Restricted)!

### ISSUE THREAD

**Issue by Nazeh** [gatsbyjs/gatsby-source-wordpress-experimental#39]
Hello @TylerBarnes , Thanks for offering to look into this, I finally found the root cause !Horray?!

I had this error in a production site, so I created a demo site to test it.

To replicate exactly what I did, or you can skip to step (11):

1. create a flywheel [demo site](https://getflywheel.com/wordpress-support/what-is-a-demo-site/) (14 days trial)
2. Enable pretty permalink to avoid this [issue](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/30) later
3. Install your own [starter](https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental) :) 
4. Install `WP Gatsby Version 0.4.8` and `WP GraphQL Version 0.10.2` and `Elementor Version 2.9.13`
5. Add the flywheel demo site's grqphql URL and htacess in the config.js (The demo site is private, which is good as my client's WP instance is too)
```
      options: {
        url:
          process.env.WPGRAPHQL_URL ||
          `https://dev-gatsby-source-wordpress-v4.pantheonsite.io/graphql`,
        verbose: true,
        develop: {
          hardCacheMediaFiles: true,
        },
        debug: {
          graphql: {
            writeQueriesToDisk: true,
          },
        },
        auth: {
          htaccess: {
            username: process.env.HTTPBASICAUTH_USERNAME,
            password: process.env.HTTPBASICAUTH_PASSWORD,
          },
        },
...
```
5. Run `yarn` then `yarn clean-develop`, it will work fine!
6. Add a small image (1) to any of your posts, doesn't even need to be published, as long as it is in your media, and run `yarn clean-develop` again and you will get this error:
```
failed to process http://gatsby-wp-demo.flywheelsites.com/wp-content/uploads/2020/07/single-stroke-ar-nazeh-5.png
HTTPError: Response code 401 (Restricted)
```
**Images will be attached below for replicating the test precisely** 
7. To solve this issue, you need to upgrade the plugin beyond 0.8.3 to solve this [issue](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/16)
```
// package.json
    "gatsby-source-wordpress-experimental": "^1.0.0",
```
8. Now run `yarn` and `yarn clean-develop` and it should work fine even if the image is published in a post.
9. Now upload a huge image (2), well look at that still works!

### Here comes Elementor

10. Now let's try Elementor! Add Image(1) which has dimensions of (831 x 973 pixels) by default image size is (Large 1024 x 1024) 
![brave_el5jIpJCsg](https://user-images.githubusercontent.com/40009100/86887139-cce5e280-c100-11ea-9fca-87041a5bc224.png)
update and Gatsby will crash with: 

```
 gatsby-source-wordpress  failed to process http://gatsby-wp-demo.flywheelsites.com/wp-content/uploads/2020/07/single-stroke-ar-nazeh-5.png
HTTPError: Response code 401 (Restricted)
```
However, If you change the "Image size" in Elementor to a little higher (1536 x 1536) it will work fine!

The same goes for image(2) , Add it to the post with the default size (1024 x 1024), gatsby will crash! change it to (full) and run again and every thing works fine!!

### Conclusion
I have no idea :D

(1)
![single-stroke-ar-nazeh (5)](https://user-images.githubusercontent.com/40009100/86884323-141da480-c0fc-11ea-9699-3b1e54fa73c6.png)

(2)
![rachel-lynette-french-U7HLzMO4SIY-unsplash](https://user-images.githubusercontent.com/40009100/86887340-0dddf700-c101-11ea-8f5c-899259f92726.jpg)

**Comment by TylerBarnes** [comment]
Hi @Nazeh just want to say I haven't forgotten about this!

It's on the top of my list for next week. Thanks for your patience :)

**Comment by Nazeh** [comment]
Thanks, @TylerBarnes I appreciate that.
I will make sure to add any s significant details as I continue to experiment.
Also, while I am still a new developer, I would love to contribute if there is some chore you would like me to help with!

**Comment by TylerBarnes** [comment]
Hi @Nazeh , this is fixed in `gatsby-source-wordpress-experimental@1.0.5`. Thanks again for reporting this bug!
There were actually 2 partially related bugs here. The first was that images fetched from within html weren't properly using previously cached images and weren't being properly cached. The second was that when fetching images in html (that weren't properly cached from before), they were being refetched without the htaccess auth headers. Those 2 problems are fixed now :)

As for contributions I'm planning on making a bunch of issues in this repo for work that needs to be done. I can ping you once I add those issues. The help would be very much appreciated!

**Comment by Nazeh** [comment]
Thanks @TylerBarnes , I just tested and it works just fine. Obviously I ran to other problems 😂  but I am not ready to report them yet until I do more experiments!

``` 
"I can ping you once I add those issues."
 ```
Yes please do!
