### ISSUE TITLE
Can't query Posts locally after upgrading to 0.8.1 + WPGraphQL v0.10

### ISSUE THREAD

**Issue by Kallirroi** [gatsbyjs/gatsby-source-wordpress-experimental#40]
Hi,
I'm getting a strange behavior after upgrading to WPGraphQL v1.0 and gatsby-source-wordpress-experimental to 0.8.1. Using GraphiQL on my Wordpress IDE all queries run fine, but on `http://localhost:8000/___graphql` the same query fails to fetch the `Posts` nodes. 
### localhost
![image](https://user-images.githubusercontent.com/10440556/86937110-db39fb80-c10c-11ea-8c1d-4f61c38c1f0d.png)

### GraphiQL on Wordpress
![image](https://user-images.githubusercontent.com/10440556/86937144-e42acd00-c10c-11ea-92a9-ee853debd289.png)

Here is an example error I'm getting in the console:
```
success Build manifest and related icons - 0.151s
success onPostBootstrap - 0.155s
info bootstrap finished - 21.654s
success run static queries - 0.021s - 4/4 191.70/s

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot read property 'id' of null

   1 | query getTag($slug: String!) {
   2 |   allWpTag(filter: {slug: {eq: $slug}}) {
   3 |     nodes {
   4 |       name
   5 |       slug
   6 |       posts {
>  7 |         nodes {
     |         ^
   8 |           title
   9 |           slug
  10 |           date
  11 |           nodeType
  12 |         }
  13 |       }
  14 |       pages {
  15 |         nodes {
  16 |           title
  17 |           slug

File path: /Users/Kallirroi/Documents/code/shannon/exploring/wordpress-tutorial-site/src/templates/tag.js
Url path: /publications
Plugin: none
```

### Versions
`gatsby-source-wordpress-experimental`: `0.8.1`
WP Gatsby: `0.4.8`
WP GraphQL: `0.10.2`
WP GraphiQL: `1.0.1`

**Comment by moonmeister** [comment]
Try updating WP experimental to 1.0+.

**Comment by TylerBarnes** [comment]
Additionally if you can share a reproduction repo + WPGraphQL `/graphql` endpoint that would help me debug and fix it fairly quickly.

**Comment by Kallirroi** [comment]
Updating `experimental` to 1.0.0 didn't help - here is the repo: https://github.com/Kallirroi/gatsby-wp-test and the endpoint you can use is `https://testingv.wordsinspace.net/graphql`.

**Comment by TylerBarnes** [comment]
Hi @Kallirroi , it looks like this is due to some internal server errors on your site.
If you run this query in Graphiql:
```graphql
query NODE_LIST_QUERY($first: Int!, $after: String) {
  tags(first: $first, after: $after, where: { parent: null }) {
    nodes {
      posts(first: 100) {
        nodes {
          id
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```

With these args:
```json
{
  "first": 100,
  "after": "YXJyYXljb25uZWN0aW9uOjEwOA=="
}
```

You'll see that some connected post nodes are returning `null`.
If you can enable WPGraphQL debug mode that might help uncover why these connections are returning `null`.

So this may be a problem with your WP instance or a problem with WPGraphQL but in any case I'll protect against `null` values here in the source plugin.

**Comment by jasonbahl** [comment]
@Kallirroi can you try WPGraphQL v0.10.2? There was a bug fixed here in relation to term->post connections:

https://github.com/wp-graphql/wp-graphql/releases/tag/v0.10.2

**Comment by TylerBarnes** [comment]
Upgrade to `gatsby-source-wordpress-experimental@1.0.2` for protection against `null` values here. But it would be super helpful if you could first try to upgrade WPGraphQL as @jasonbahl mentioned and see if it fixes the problem.

**Comment by Kallirroi** [comment]
@jasonbahl thats the version I have installed. Upgrading to `gatsby-source-wordpress-experimental@1.0.2` solved it!

**Comment by TylerBarnes** [comment]
Good to hear @Kallirroi ! Fwiw the underlying WPGraphQL bug is being tracked here https://github.com/wp-graphql/wp-graphql/issues/1374
