### ISSUE TITLE
Timeout when doing `gatsby develop`

### ISSUE THREAD

**Issue by martin-braun** [gatsbyjs/gatsby-source-wordpress-experimental#403]
Instead of restarting the timeout for each of the request, it will add up for each request. It will cause the fail the develop task if the requests take longer than 30 seconds in total, but instead it should throw an error if one request takes longer than 30 seconds. You can see in the log how each call adds up the timeout counter:

```
> gatsby develop

success open and validate gatsby-configs - 0.041s
success load plugins - 0.583s
success onPreInit - 0.028s
success initialize cache - 0.017s
success copy gatsby files - 0.042s
success onPreBootstrap - 0.015s


success  gatsby-source-wordpress  ensuring plugin requirements are met - 13.650s
⠀
info  gatsby-source-wordpress 

        This is either your first build or the cache was cleared.
        Please wait while your WordPress data is synced to your Gatsby cache.

        Maybe now's a good time to get up and stretch? :D

success  gatsby-source-wordpress  ingest WPGraphQL schema - 19.010s
success createSchemaCustomization - 32.689s
success  gatsby-source-wordpress  fetch root fields - 2.990s
success  gatsby-source-wordpress  Category - 6.193s - fetched 5
success  gatsby-source-wordpress  Comment - 6.200s - fetched 0
success  gatsby-source-wordpress  ContentType - 9.330s - fetched 3
success  gatsby-source-wordpress  Lesson - 13.258s - fetched 10
success  gatsby-source-wordpress  Course - 14.849s - fetched 15
success  gatsby-source-wordpress  MenuItem - 17.214s - fetched 4
success  gatsby-source-wordpress  Menu - 17.577s - fetched 1
success  gatsby-source-wordpress  PostFormat - 20.179s - fetched 0
success  gatsby-source-wordpress  Page - 21.808s - fetched 11
success  gatsby-source-wordpress  Tag - 25.091s - fetched 12
success  gatsby-source-wordpress  Post - 27.303s - fetched 8
success  gatsby-source-wordpress  Taxonomy - 27.799s - fetched 3
success  gatsby-source-wordpress  UserRole - 29.864s - fetched 0

 ERROR 

timeout of 30000ms exceeded


 ERROR #gatsby-source-wordpress-experimental_111006 

 gatsby-source-wordpress  It took too long for https://example.org/gql to respond (longer than 30 seconds).

Either your URL is wrong, you need to increase server resources, or you need to decrease the amount of resources each request
takes.

You can configure how much resources each request takes by lowering your `options.schema.perPage` value from the default of 100
nodes per request.
Alternatively you can increase the request timeout by setting a value in milliseconds to `options.schema.timeout`, the current
setting is 30000.
```

To bypass the issue, I increased the timeout to something ridiculously high in the gatsby-config.js: 

```js
      resolve: "gatsby-source-wordpress-experimental",
      options: {
        url: "https://example.org/gql",
        timeout: 3600000
      },
```

However, it does not work. How can I increase the timeout for now, until it's fixed?

My dependencies: 

```js
    "gatsby": "^2.30.1",
    "gatsby-image": "^2.9.0",
    "gatsby-plugin-react-helmet": "^3.8.0",
    "gatsby-plugin-sass": "^2.8.0",
    "gatsby-plugin-sharp": "^2.12.0",
    "gatsby-source-filesystem": "^2.9.0",
    "gatsby-source-wordpress-experimental": "^6.1.0",
    "gatsby-transformer-sharp": "^2.10.0",
    "node-sass": "^5.0.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-helmet": "^6.1.0"
```

**Comment by TylerBarnes** [comment]
Hi @martin-braun did you try the following from the error message?

```
You can configure how much resources each request takes by lowering your `options.schema.perPage` value from the default of 100
nodes per request.
```

**Comment by martin-braun** [comment]
> Hi @martin-braun did you try the following from the error message?
> 
> ```
> You can configure how much resources each request takes by lowering your `options.schema.perPage` value from the default of 100
> nodes per request.
> ```

@TylerBarnes Yes I tried that, but it did not work either, which makes sense. If you count up all those entries, they are not even 80 items in total and the `perPage` option is for each request.

Could you please tell me how I can increase the timeout properly to bypass this issue for now?

**Comment by TylerBarnes** [comment]
It's also in the error message :)

```
Alternatively you can increase the request timeout by setting a value in milliseconds to `options.schema.timeout`, the current
setting is 30000.
```

**Comment by TylerBarnes** [comment]
https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/plugin-options.md#schematimeout-int

**Comment by martin-braun** [comment]
> https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/plugin-options.md#schematimeout-int

Thank you, that link was helpful. I should've taking the message literally. I was assuming the timeout was for each request. If it's supposed to be for all requests then it's too low for my case. No wonder, my instance is small and has not much data, so it starts too many requests, because it won't hit the perPage limit even once.

I think it might make sense to increase the default value to at least 60 seconds to prevent this issue for new projects.

Anyway changing the timeout was successful.

**Comment by TylerBarnes** [comment]
Ahhh, makes sense :) that's a good suggestion, I'll put it in our backlog as a simple, non-breaking, enhancement. Thanks @martin-braun !
