### ISSUE TITLE
Error: listen EADDRINUSE: address already in use 127.0.0.1:52338

### ISSUE THREAD

**Issue by martin-braun** [gatsbyjs/gatsby-source-wordpress-experimental#404]
Since 6.1.0 I'm unable to run `gatsby develop`:

```
...
info  gatsby-source-wordpress  Watching for WordPress changes
⠹ Building development bundle
/....../node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:52338
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at GetAddrInfoReqWrap.doListen (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 52338
}
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! ........@1.0.0 start: `gatsby develop`
npm ERR! Exit status 7
```

Yes, there is another server running on 127.0.0.1 (Local by Flywheel), but it's using a different port.

```sh
sudo lsof -i :52338
```

returns nothing.

**Comment by acao** [comment]
you've probably already tried this but, did you try a gatsby clean in between upgrades?

also, have you tried restarting all running instances of the gatsby server on your machine? you said there is another server running on a different port, what kind of server? a gatsby server? try shutting down all gatsby servers first, then run clean, then try the upgrade

**Comment by babgyy** [comment]
Speaking for myself : 
No other running server on 127.0.0.1, and lsof is not retuning anything for the port supposedly in use.
Using v6 of this plugin.

It happens when doing `gatsby develop`, and it happens more frequently when content writers are updating the Wordpress server. 

I can't reproduce systematically the issue, but the port in use is not always the same. 
Quitting the terminal, or restarting my computer sometimes helps, but sometimes not. `gatsby clean` sometimes helps, but sometimes not. But it also takes 10-20 minutes for a fresh build so it is my last resort.

**Comment by acao** [comment]
@babgyy what version of gatsby core are you running? is it the latest?

**Comment by TylerBarnes** [comment]
I think this issue is related https://github.com/gatsbyjs/gatsby/issues/25859

I ran into this myself once and couldn't figure out what was causing it. Changing my node version made it stop 😬

**Comment by martin-braun** [comment]
@acao I can say it happens every time. Yes I tried `gatsby clean`. I also tried to restart my machine. 

Here are more details of my setup:

- macOS 11.1 (20C69)
- node v12.20.0

> you said there is another server running on a different port, what kind of server? a gatsby server? try shutting down all gatsby servers first, then try the upgrade after running gatsby clean

It's the Apache of Local by Flywheel, the program I host the Wordpress with. I cannot disable it, because then the GraphQL API is not accessible by `gratsby develop`. I can ensure that it worked with 6.0.0. I reverted my version and the build works, so it's something that was added in 6.1.0 or its dependencies.

Here is my downgrade patch of the package.json:

<img width="356" alt="Screen Shot 2021-01-09 at 01 51 58" src="https://user-images.githubusercontent.com/24259245/104078228-4d56de80-521d-11eb-8bfd-f39564d688ab.png">

Red entries caused this issue, green entries fixed this problem (downgraded versions).

@TylerBarnes Your linked issue looks suspicious, the major version of node matches with mine. I will try to switch to node v10 later, but whatsoever, it would not explain why the issue appeared on minor version steps, now, when it was reported back in July 2020.

**Comment by TylerBarnes** [comment]
Yeah, it's hard to say what's causing it. We will be investigating it further but in the meantime switching your node version should fix it 👍

**Comment by martin-braun** [comment]
I just want to report that I finally downgraded to node v10, updated all my packages so I'm @latest right now. Everything works fine, eventually. Maybe it should be part of the documentation to better use node v10, or is it, already? @TylerBarnes 

Anyway, I'm closing this now, it seems to be related to https://github.com/gatsbyjs/gatsby/issues/25859 as you said. If the base of Gatsby supports v12, we could re-investigate and make a new issue if problems come back. 

Thanks for your support!
