### ISSUE TITLE
Switch from node-sass to dart sass

### ISSUE THREAD

**Issue by martin-braun** [gatsbyjs/gatsby-source-wordpress-experimental#406]
_LibSass_, that is used by _node-sass_, [seems to be deprecated](https://sass-lang.com/blog/libsass-is-deprecated), so _node-sass_ won't support the nice new features like [_SASS Modules_](https://css-tricks.com/introducing-sass-modules/).

Using this starter (`npm init gatsby`, selecting Wordpress) will add `node-sass` instead of `sass` (_Dart Sass_) to its dependencies, in contrast to the [correct recommendation of the `gatsby-plugin-sass` plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sass#install) to install `sass`, instead.

**Comment by TylerBarnes** [comment]
Hi @martin-braun, thanks for the info! `npm init gatsby` isn't part of this project so I'd recommend opening this issue on the main GatsbyJS monorepo. Thanks!
