### ISSUE TITLE
Document why "WP Menus are not pulled into GraphQL"

### ISSUE THREAD

**Issue by robmarshall** [gatsbyjs/gatsby-source-wordpress-experimental#41]
I am converting a current WpGraphQL site over to using this package.

When viewing the query to fetch menus in the WordPress CMS panel using GraphiQL the data is visible. However when running 'gatsby develop' the data is not pulled into the Gatsby GraphQl. 

Returns count of 0, rather than 2 - with no other data attached.

This applies to both menu fields:

- allWpMenu
- allWpMenuItem

**Comment by TylerBarnes** [comment]
Hi @robmarshall this is most likely due to a change in WPGraphQL. Menus which have no assigned location are considered private by WP core, so WPGraphQL has been recently changed to work this way as well. When you debug using wp-graphiql, you're actually authenticated so you can see these private menus. Assign a location to them and they should show up in Gatsby 👍

**Comment by riddla** [comment]
Thanks @TylerBarnes, that did the trick for me!

**Comment by Kallirroi** [comment]
I had the same issue and assigning a location solved it - thanks @TylerBarnes!

**Comment by TylerBarnes** [comment]
Glad to hear it worked for you :) I'll keep this issue open and change the title to make it about documentation

**Comment by Kallirroi** [comment]
![image](https://user-images.githubusercontent.com/10440556/87984628-3e7e4300-caa8-11ea-99d7-a620b81ec4e3.png)
@oliverfeher You need to check one of the Menu boxes like above.

**Comment by oliverfeher** [comment]
> ![image](https://user-images.githubusercontent.com/10440556/87984628-3e7e4300-caa8-11ea-99d7-a620b81ec4e3.png)
> @oliverfeher You need to check one of the Menu boxes like above.

I did, however I'm still getting this error `Error    Cannot query field "menus" on type "Query" `

**Comment by TylerBarnes** [comment]
@oliverfeher can you share a reproduction repo that has this issue? It's hard to tell what could be happening from your description. Thanks!
