### ISSUE TITLE
Missing products on product categories 

### ISSUE THREAD

**Issue by mattdabell** [gatsbyjs/gatsby-source-wordpress-experimental#42]
Hi!
Firstly great work on the plugin. Initial testing with standard wordpress integration has been awesome. Can't thank you enough for tackling this.

Thought I'd try it out with WpGraphql Woocommerce. I'm aware this hasn't been tested yet so feel free to ignore this issue. However since I got this far thought I may as well raise it in case it's useful.

In woocommerce there's allWpProductCategory which has products, which you'd expect to query like this:

```
{
  allWpProductCategory {
    nodes {
      products {
        nodes {
          name
        }
      }
    }
  }
}
```

However the products returned are all null, so immediately throw a "Cannot read property 'type' of undefined" error.

Eg if there's 4 products in a category the response will be:

```
"products": {
  "nodes": [
    null,
    null,
    null,
    null
  ]
}
```

When I run this query in playground it returns data as expected:

```
{
  productCategories {
    nodes {
      products {
        nodes {
          name
        }
      }
    }
  }
}
```

I also ran the query in node-list-query.graphql and data was returned fine.

I wonder if it's related to the fact there are different types of products eg WpVariableProduct and WpSimpleProduct.

I'm guessing woocommerce integration isn't the priority right now but I'm happy to help with testing when the time comes.

**Comment by imranhsayed** [comment]
@mattdabell 
Are you able to fetch price for any product?

**Comment by mattdabell** [comment]
@imranhsayed also seeing price as null when querying directly on allWpProduct as per your issue

**Comment by TylerBarnes** [comment]
Just responded in https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/49

These are likely related 👍 I can check these both out. @mattdabell are you able to share a WPGraphQL api endpoint I can use to debug?

**Comment by mattdabell** [comment]
Thanks @TylerBarnes , can use this env for testing woocommerce: https://ssgatsby.wpengine.com/graphql

**Comment by mattdabell** [comment]
@TylerBarnes emailed the endpoint

**Comment by TylerBarnes** [comment]
Upgrade to `gatsby-source-wordpress-experimental@1.1.1` for a fix! :D

**Comment by mattdabell** [comment]
Thanks @TylerBarnes ! Looking good.
