### ISSUE TITLE
Endpoint gets rejected if hostname does not appear in certification alt-names

### ISSUE THREAD

**Issue by smetzdev** [gatsbyjs/gatsby-source-wordpress-experimental#425]
Iam running a wordpress on azure, with a free private-key certificate.
If i try starting my development server i get the following message:

```
 gatsby-source-wordpress  Hostname/IP does not match certificate's altnames: Host: MYHOST is not in the cert's altnames:
DNS:*.MYAZURE.net, DNS:*.scm.MYAZURE.net, DNS:*.azure-mobile.net, DNS:*.scm.azure-mobile.net, DNS:*.sso.MYAZURE.net
```

Is there any option i can set to avoid this check?

**Comment by TylerBarnes** [comment]
@smetzdev can you share the full terminal output of your build? I believe this is a deeper error either from NodeJS or from axios (most likely nodeJS though). The source plugin doesn't have any code that checks certificates.

**Comment by smetzdev** [comment]
Wow, thanks for the quick response!
Strange thing, it's actually working now (just checked for reproduction).
Maybe the certificate just needed some time here.

Would this be an interesting thing? If yes, i will setup a new domain and certificate and try to reproduce it.

**Comment by TylerBarnes** [comment]
Ah, it most likely needed more time then :) I think let's leave it as-is because I think the error probably doing the right thing here 👍

**Comment by smetzdev** [comment]
Sure thing! Thank you.
