### ISSUE TITLE
error on update: "expected iterable, but did not find one for Post.pinged"

### ISSUE THREAD

**Issue by agnescameron** [gatsbyjs/gatsby-source-wordpress-experimental#448]
Hi, I recently updated the version of `gatsby-source-wordpress-experimental` to 7.0.3 (from 4.0.0), which I believe is the most recent. The packages on the Wordpress end are all up-to-date.

When building the site from wordpress, we see the following error, which is thrown for all posts, and the build fails. My feeling is that there's an error with one or more posts, meaning that `posts.pinged` returns undefined, but there's nothing checking that before the package tries to use `posts.pinged` as an iterable... I haven't been able to find the section of the code where this is happening in order to verify this. Any help appreciated as this is a bit of a dead end right now! thankyou :)

<img width="600" alt="Screen Shot 2021-01-31 at 19 06 39" src="https://user-images.githubusercontent.com/16444898/106477654-49c31a00-64a0-11eb-9b33-502878750545.png">

**Comment by Kallirroi** [comment]
This was fixed by omitting `pinged` in `excludeFieldNames` field of `gatsby-config.js`.
