### ISSUE TITLE
Contact Form 7 ?

### ISSUE THREAD

**Issue by konrad-bak** [gatsbyjs/gatsby-source-wordpress-experimental#451]
I've set my gatsby integration with WP - i can now query WP Posts, list them and generate single post pages.

The Gatsby-WordPress plugin says I can use all WP Plugins with that, but... how do I use Contact Form 7 here?

**Comment by jackonawalk** [comment]
Hi there! Unfortunately most WordPress plugins are not compatible with Gatsby out of the box. That said, most WPGraphQL extensions do work with Gatsby. You can find those here: https://www.wpgraphql.com/extensions

If there's a WordPress plugin that doesn't have a WPGraphQL extension, you could reach out to the plugin author and request they build a WPGraphQL extension. Without that, there's no way for Gatsby to interact with the plugin.
