### ISSUE TITLE
Custom posts types aren't deleted when i switch them from 'publish' to 'trash'

### ISSUE THREAD

**Issue by PierreMouchan** [gatsbyjs/gatsby-source-wordpress-experimental#47]
Hello ! 
Today i encountered a serious problem mostly due to gatsby cache. 
I've created a custom post type in my wordpress, everything it's working fine until i delete a entry and send it to the wp 'trash'.
After re-running yarn dev (also occuring after pushing on netlify for example) my entry is still visible in the front. (despite that this entry is in the trash in the wordpress). I tried to filter my custom post type by `status: {eq: "publish"}` but it doesn't work as well.
My only way to correct this is to delete gatsby cache (yarn clean) and refetch all nodes from wp.
So it's really annoying for a CI/CD with netlify. 
Do you have any clues on this ? thx

**Comment by TylerBarnes** [comment]
Hi @PierreMouchan , sorry to hear you're running into an issue! Does this also happen for you on the build in post and page types? Or just for CPTs?

**Comment by PierreMouchan** [comment]
@TylerBarnes it seems to only appear on CPTs (if you need more infos tell me, i don't really know how to guide you for this one haha)

**Comment by PierreMouchan** [comment]
![image](https://user-images.githubusercontent.com/38973205/87508968-d4f9d100-c670-11ea-9201-8ec99fa5b2da.png)

**Comment by TylerBarnes** [comment]
That should be enough info for me to reproduce. Thanks @PierreMouchan !

**Comment by PierreMouchan** [comment]
> That should be enough info for me to reproduce. Thanks @PierreMouchan !

Also deployed on Netlify with build cache plugin ! (btw)

**Comment by TylerBarnes** [comment]
I'm moving this issue to the WPGatsby repo, see above for a link to the new issue ☝️
