### ISSUE TITLE
Preview not sending ACF custom fields

### ISSUE THREAD

**Issue by nunof07** [gatsbyjs/gatsby-source-wordpress-experimental#48]
I have a local WordPress site with the following plugins installed:

- Advanced Custom Fields PRO
- WP Gatsby
- WP GraphQL
- WPGraphQL for Advanced Custom Fields

I have a local Gatsby site running with `ENABLE_GATSBY_REFRESH_ENDPOINT=true gatsby develop`.

The WordPress instance settings are correctly pointing to the local preview server. I can see changes reflected in preview mode for the standard fields, such as the title.

However, the values in the custom fields are not being sent in the preview (they get null values despite having values in WordPress). Outside the preview mode, they work properly though.

Is ACF currently supported in preview mode?

**Comment by TylerBarnes** [comment]
This is actually a problem with the ACF extension. As far as I'm aware it's not yet fully supporting previews in the latest WPGQL. @jasonbahl mentioned it would only take a few LOC to make it work. @jasonbahl any updates? :)

**Comment by jasonbahl** [comment]
I’ll try and push a release tonight 🤞

**Comment by TylerBarnes** [comment]
You should go enjoy your weekend tho! I don't think anyone needs it on a friday night 😛

**Comment by TylerBarnes** [comment]
Hi @nunof07 , can you update to the latest `wp-graphql-acf` and let us know how it went? This should work now :)

**Comment by nunof07** [comment]
Hey @TylerBarnes , I can confirm this works now on my end 👍 .

Thank you @TylerBarnes @jasonbahl !
