### ISSUE TITLE
Price null on allWpProduct query with wp-graphql-woocommerce

### ISSUE THREAD

**Issue by imranhsayed** [gatsbyjs/gatsby-source-wordpress-experimental#49]
Hi @TylerBarnes 👋 
Thank you for the awesome work on this plugin 🙏
I am pretty excited to build a woocommerce theme with `gatsby-source-wordpress-experimental`

However on testing it,  I am getting price as `null` in the query.

![image](https://user-images.githubusercontent.com/11497423/87225083-efe5f000-c3a7-11ea-8944-6f7a1d256e17.png)

Here is the link for my [WIP repo](https://github.com/imranhsayed/gatsby-woocommerce-themes)

I saw some of the Github issues, where you have mentioned that `wp-graphql-woocommerce` currently not supported as its not tested.
Please let me know when we can use it with `wp-graphql-woocommerce`, when possible.

**Comment by TylerBarnes** [comment]
Hi @imranhsayed , glad to hear you're excited about this :)
If you can provide me with a live WPGraphQL api endpoint I can use to debug with I can get this fixed for you.

**Comment by imranhsayed** [comment]
Thank you will add soon

**Comment by imranhsayed** [comment]
@TylerBarnes 
I have installed and setup all the required WordPress plugins on `https://codeytek.com/wordpress_woo`, that can be used as SITE_URL in `.env`
And [this is my working repo](https://github.com/imranhsayed/gatsby-woocommerce-themes) where you can test and debug.
Would that help?

**Comment by TylerBarnes** [comment]
Upgrade to `gatsby-source-wordpress-experimental@1.1.1` for a fix :)

**Comment by imranhsayed** [comment]
Thank you so much @TylerBarnes 🙏
Works like a charm, after the update ❤️ . I really appreciate it 🤩

**Comment by TylerBarnes** [comment]
Glad to hear it :D let me know if you run into anything else :)

**Comment by imranhsayed** [comment]
Sure I will . Thank you!
