### ISSUE TITLE
Fix: make sure verbose mode is readable on various terminal themes

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/gatsby-source-wordpress-experimental#57]
I was pairing with Lennart a few months back and the terminal output had low contrast and was hard to read (for the blue gatsby-source-wordpress boxes). This is an easy fix that will improve ux 👍

**Comment by jacobarriola** [comment]
@TylerBarnes what did you have in mind? I'm happy to help out with this 🙂

I'm running the `GitHub Light` VS Code theme and it seems like the `white` font color declared [here](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/src/utils/format-log-message.js#L19) isn't getting recognized. 🤔

![image](https://user-images.githubusercontent.com/1371573/88345299-88f6fe00-ccfa-11ea-9f1d-c51958dd0441.png)

**Comment by TylerBarnes** [comment]
Hey @jacobarriola , I'd love help with this! I actually didn't have anything in mind, I was thinking of trying some things out until some combination worked well enough. I also don't know a ton about terminal themes, I wonder if there's a way to adapt based on what kind of theme it is or something 🤔 
But help would be very much appreciated 😄

**Comment by jacobarriola** [comment]
Sounds good. I'll test a few things out. 👍🏽

**Comment by jacobarriola** [comment]
@TylerBarnes I haven't forgot about this. Will take a stab at it this weekend.

**Comment by TylerBarnes** [comment]
A fix is published in `gatsby-source-wordpress-experimental@1.3.3`. Thanks @jacobarriola !
