### ISSUE TITLE
Build failed while fetching nodes

### ISSUE THREAD

**Issue by rodrigo-arias** [gatsbyjs/gatsby-source-wordpress-experimental#6]
Hi Tyler,

I am getting this error on build in both Gatbsy Cloud and Netlify, however local works fine.

![image](https://user-images.githubusercontent.com/11416255/82846493-73628500-9ebf-11ea-9544-fbfe23a50ecc.png)

I have noticed that this happens if I put a limit greater than 100 posts.

I am using WP Engine and I think this happened after some of the latest updates, I am using version 0.7.1

Do you have any idea where I can search?

Thank you

**Comment by rodrigo-arias** [comment]
I enabled all debugging and found several more messages

![image](https://user-images.githubusercontent.com/11416255/82846996-fb498e80-9ec1-11ea-8dea-f8faff0e7b09.png)

I don't know exactly what causes it, so any suggestion will be appreciated

**Comment by rodrigo-arias** [comment]
Hi, you can close this ticket. I can't find the specific problem with posts, but for now removed the types introduced in WPGraphQL 0.9 (they even failed with Twenty Twenty theme) and by adding from scratch my posts is working again.
If I show not only the critical errors some of those shown in the screenshot above are still showing, but the rest works fine.

```
ContentNodeToEnqueuedScriptConnection: {
  exclude: true,
},
ContentNodeToEnqueuedStylesheetConnection: {
  exclude: true,
},
TermNodeToEnqueuedScriptConnection: {
  exclude: true,
},
TermNodeToEnqueuedStylesheetConnection: {
  exclude: true,
},
```

Thank you

**Comment by TylerBarnes** [comment]
Ah, I think I actually need to exclude these by default. I have EnqueuedScript and EnqueuedStylesheet excluded by default as those types aren't yet working properly in the source plugin.
