### ISSUE TITLE
Make download manager smart

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/gatsby-source-wordpress-experimental#66]
Right now when media files are fetched and 1 fails, it's added to the end of the processing queue. This makes media file fetching pretty resilient when a server gets overloaded from too many requests. Since this is much more resilient we actually have a chance here to automatically manage how many concurrent requests we're making based on how well the server is handling it. Perhaps we could increase the concurrency by 1 every so often, and every time a download fails decrease it by 1? Or something like that. Need to play with it a bit to see what's possible, but the idea is there.

**Comment by julienp** [comment]
> Perhaps we could increase the concurrency by 1 every so often, and every time a download fails decrease it by 1? Or something like that. Need to play with it a bit to see what's possible, but the idea is there.

TCP uses AIMD (additive increase, multiplicative decrease) to manage the number of packets it keeps in flight: it increases transmission rate by 1 and decreases by half on packet loss. I think that's mostly helpful because it ensures multiple streams get a fair share of the bandwidth, which does not apply here, but it still might be prudent to back off a bit and decrease by more than the increase step.

**Comment by julienp** [comment]
It would also be good to ensure the downloader has good settings for keepalive, maxFreeSockets, maxSockets, dns caching etc.

**Comment by TylerBarnes** [comment]
💯 great points @julienp . For AIMD we'll probably have to play around with it but that seems like a good way to do it!

**Comment by smthomas** [comment]
We recently moved this plugin over to the gatsbyjs monorepo and are trying to clean out this issue queue. We documented this feature to look at for a future roadmap item and are going to close this issue out. If you want to add additional visibility to this feature, you can request it at [https://portal.gatsbyjs.com/](https://portal.gatsbyjs.com/)
