### ISSUE TITLE
Process author avatar via gatsby-image

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/gatsby-source-wordpress-experimental#67]
Since this type isn't a MediaItem, it has no local file.
This could easily be pulled in to be processed via Sharp

```
{
  wpPage {
    author {
      avatar {
        url
      }
    }
  }
}
```

**Comment by shawngrona** [comment]
👀

**Comment by shawngrona** [comment]
hi @TylerBarnes and future gatsby-source-wp devs, i found a solution

i forked my solution following [these gatsby instructions for processing remote images](https://www.gatsbyjs.com/docs/preprocessing-external-images/)  from the [using-gatsby-source-wordpress-experimental](https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental) repo:

https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental/compare/master...shawngrona:avatar-image

above works for me but curious - when you opened this pr were planning to include this functionality automatically in the source wp plugin?

**Comment by smthomas** [comment]
We recently moved this plugin over to the gatsbyjs monorepo and are trying to clean out this issue queue. We documented this feature to look at for a future roadmap item and are going to close this issue out. If you want to add additional visibility to this feature, you can request it at https://portal.gatsbyjs.com/
