### ISSUE TITLE
Gutenberg vs Classic

### ISSUE THREAD

**Issue by zeevosec** [gatsbyjs/gatsby-source-wordpress-experimental#69]
Gutenberg is commonly known as the "new Wordpress editor" that is "Block-based". It is _somewhat_ controversial in whether or not it is an upgrade from the classic editor.

Should we be using it over the classic editor? How does it interact with this plugin, or wpgraphql, in general? What features are lost or gained? Should we be using wp-graphql-gutenberg if we are using Gutenberg?

Thanks for all of your hard work on such a cool and innovative developer experience!

**Comment by TylerBarnes** [comment]
Hey @zeevosec ! Glad to hear you're enjoying it 😄 
You should be able to use either of them. Gutenberg does have issues though as it's still so new. The 2 biggest problems right now are:
- No way to preview post meta (can't preview acf) https://github.com/WordPress/gutenberg/issues/16006
- There's no server side registry of blocks so Gutenberg blocks can't be properly added to the WPGQL schema

There's no fix for problem 1, but @pristas-peter has developed a pretty cool plugin that works around some of those difficult limitations and adds all blocks to the schema https://github.com/pristas-peter/wp-graphql-gutenberg

**Comment by talldan** [comment]
> There's no server side registry of blocks so Gutenberg blocks can't be properly added to the WPGQL schema

There's a new REST endpoint merged in https://core.trac.wordpress.org/ticket/47620 that should expose server registered blocks and should be in WP 5.5.

**Comment by TylerBarnes** [comment]
That's awesome @talldan !

**Comment by TylerBarnes** [comment]
As of now I would say the biggest barrier to using Gutenberg is that meta is not previewable. For sites using entirely Gutenberg with no additional meta (probably a rare case, but hard to say), Gutenberg will work fine. If you need to be able to preview meta I would still avoid Gutenberg for now. Closing this issue for now but feel free to continue discussion here.

**Comment by pristas-peter** [comment]
Wouldnt a custom rest endpoint with metadata fired alongside a revision create be able handle this?

**Comment by TylerBarnes** [comment]
@pristas-peter something like that is probably needed. Might be good to suggest it in https://github.com/WordPress/gutenberg/issues/16006 :)
