### ISSUE TITLE
Images with Greek characters in title failing on build

### ISSUE THREAD

**Issue by kosvrouvas** [gatsbyjs/gatsby-source-wordpress-experimental#7]
Terminal says "Try lowering process.env.GATSBY_CONCURRENT_DOWNLOAD" but even lowering doesn't help. It seems it only does this if the media has a title writter in Greek.

`11:35:37 AM: success Downloading remote files - 3.577s - 62/62 17.34/s
11:36:51 AM: info pushing https://example.com/wp-content/uploads/2014/11/αρτε.jpg to the end of the request queue.
11:36:51 AM: info Previously retried 2 times already.
11:37:16 AM: info pushing https://example.com/wp-content/uploads/2014/11/αρτε.jpg to the end of the request queue.
11:37:16 AM: info Previously retried 3 times already.
11:37:41 AM: info pushing https://example.com/wp-content/uploads/2014/11/αρτε.jpg to the end of the request queue.
11:37:41 AM: info Previously retried 4 times already.
11:38:10 AM: info
11:38:10 AM: already re-queued https://example.com/wp-content/uploads/2014/11/αρτε.jpg 5 times :( sorry.
11:38:10 AM: Try lowering process.env.GATSBY_CONCURRENT_DOWNLOAD.
11:38:10 AM: It's currently set to 200
11:38:10 AM: error wrong url: https://example.com/wp-content/uploads/2014/11/αρτε.jpg
11:38:10 AM: not finished source and transform nodes - 260.167s
11:38:10 AM: not finished  gatsby-source-wordpress  fetching nodes - 260.088s - 1957 total
11:38:10 AM: not finished  gatsby-source-wordpress  creating nodes - 244.392s - awaiting async side effects - 8 additional nodes fetched
11:38:10 AM: not finished  gatsby-source-wordpress  MediaItem - 244.391s - fetched 523
11:38:10 AM: not finished Generating image thumbnails - 242.943s
11:38:11 AM: Skipping functions preparation step: no functions directory set
11:38:21 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1`

**Comment by TylerBarnes** [comment]
Thanks for the report @kosvrouvas !

This is fixed in `gatsby-source-wordpress-experimental@0.7.5`

**Comment by kosvrouvas** [comment]
Awesome Tyler! 🎉
