### ISSUE TITLE
OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by rodrigo-arias** [gatsbyjs/gatsby-source-wordpress-experimental#74]
Hi Tyler,

This really is not an important thing. I have started using the plugin from its first versions and I have always got this error

`(node:64995) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated`

Maybe it could be used instead `OutgoingMessage.prototype.getHeader()`, but I haven't found any reference in the code, maybe you could give me some hint.

Thanks

**Comment by TylerBarnes** [comment]
Hi @rodrigo-arias , thanks for pointing this out. I went searching for this myself a couple months ago and couldn't find it. I believe it's actually coming from within axios (which is being used to source nodes). https://github.com/axios/axios/issues/2469

**Comment by smthomas** [comment]
Thank you for opening this issue. We recently moved this plugin over to the gatsbyjs monorepo and are trying to clean out this issue queue. We documented this bug and will track this to see if we can get an upstream solution.
