### ISSUE TITLE
contentType field on pages and posts always returns null

### ISSUE THREAD

**Issue by renatoruk** [gatsbyjs/gatsby-source-wordpress-experimental#76]
Hello Gatsby team! This new WordPress plugin and whole dev experience around it is amazing even it's in beta. The improvements are huge. Thank you for making a great effort 🥇 

I think I found a bug in querying `contentType` on any WordPress entity that supports it. 

*This is a screenshot of a query inside WP.*
![wp-query](https://user-images.githubusercontent.com/12981417/88050931-10f0d280-cb58-11ea-976b-9051bae5ff33.png)

As you can see, `contentType` has the correct structure when queried through WP GraphiQL.

But, doing the same query (with name prefixes) results in `null` for `contentType` inside Gatsby.
![gatsby-query](https://user-images.githubusercontent.com/12981417/88050942-151cf000-cb58-11ea-9093-39e6b4002466.png)

Currently, I have a workaround for this by using `nodeType` in Gatsby, but would prefer using `contentType`.

I followed the steps mentioned in the [troubleshooting docs](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/debugging-and-troubleshooting.md#missing-data-in-gatsby) that led me on creating this issue. 

## Additional information
gatsby-source-wordpress-experimental - "^1.0.7"
WP Gatsby - Version 0.4.13

Please let me know if you need any other info. Do you have a suggestion about where to start for fixing this bug? Which files or directories should I look first?

**Comment by TylerBarnes** [comment]
Hi @renatoruk , thank you for this really well written issue! This looks like a bug indeed. I'll have a look 😄 
Thanks again!

**Comment by TylerBarnes** [comment]
This is appears to be a `woocommerce-wp-graphql` bug. When I make those same queries from Graphiql, I get null returned for `Product.contentType.id` along with an error. There may be certain conditions where this query does not return null, but null is being returned during node sourcing. I recommend not using wp-graphiql to debug because it's authenticated and Gatsby wont be authenticated when sourcing data, so the result is inconsistent for debugging. I just added a note to the debugging docs (thanks for using those btw!).

I've opened an issue on the `wp-graphql-woocommerce` repo to track this issue: https://github.com/wp-graphql/wp-graphql-woocommerce/issues/325

**Comment by renatoruk** [comment]
> This is appears to be a `woocommerce-wp-graphql` bug. When I make those same queries from Graphiql, I get null returned for `Product.contentType.id` along with an error. There may be certain conditions where this query does not return null, but null is being returned during node sourcing. I recommend not using wp-graphiql to debug because it's authenticated and Gatsby wont be authenticated when sourcing data, so the result is inconsistent for debugging. I just added a note to the debugging docs (thanks for using those btw!).
> 
> I've opened an issue on the `wp-graphql-woocommerce` repo to track this issue: [wp-graphql/wp-graphql-woocommerce#325](https://github.com/wp-graphql/wp-graphql-woocommerce/issues/325)

Hey Tyler, thank you for taking the time to take a look at it!

Can you explain how is `wp-graphql-woocommerce` related to `wp-source-wordpress-experimental`? I'm not seeing it in the [dependency graph](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/network/dependencies).

I forgot to mention that in the original issue description, but "Product" is a custom post type, woocommerce is not used in the WP project. 

Here's a snippet of the script that is responsible for registering that custom type.

```php
register_post_type( "products", [
				'labels'       => [
					'name'          => __( 'Products' ),
					'singular_name' => __( 'Product' ),
				],
				'supports'     => [ 'title', 'thumbnail', 'excerpt', 'revisions' ],
				'public'       => false,
				'show_ui'      => true,
				'has_archive'  => true,
				'acfe_admin_archive' => true,
				'hierarchical' => false,
				'show_in_rest' => true,
				'show_in_graphql'     => true,
				'graphql_single_name' => __( 'Product' ),
				'graphql_plural_name' => __( 'Products' ),
				'menu_icon'    => 'dashicons-portfolio',
				'rewrite'      => [
					'slug'       => "products",
					'with_front' => false,
				],
			] );
```

But, other than custom post type (Product), `contentType` can not be queried also on the `pages` (`allWpPage`) type. That's what led me into thinking that in might be something in the sourcing phase.

---
Also, nice addition to the docs. I did not know that difference!

**Comment by TylerBarnes** [comment]
Ahh, sorry about that, wp-graphql-woocommerce adds this `products` field as well so I assumed you were using it. And coincidentally that project errors on this exact same field 😆 

I will have another look at this, thanks for the clarification!

**Comment by renatoruk** [comment]
> Ahh, sorry about that, wp-graphql-woocommerce adds this `products` field as well so I assumed you were using it. And coincidentally that project errors on this exact same field 😆
> 

Yes, definitely a very similar scenario! 

> I will have another look at this, thanks for the clarification!
Awesome, looking forward to it 🥇

**Comment by TylerBarnes** [comment]
@renatoruk this is expected behaviour actually! You have your CPT set to private `"public" => false` so this CPT is not publically queryable. Which means Gatsby does not have it. When you debug queries it's best to not use `wp-graphiql` as it's queries are authed and Gatsby isn't. So when I register your CPT, I see this in wp-graphiql:

```json
{
  "data": {
    "products": {
      "nodes": [
        {
          "contentType": {
            "node": {
              "name": "products"
            }
          }
        }
      ]
    }
  }
}
```

And in GraphQLPlayground (unauthenticated):

```json
{
  "data": {
    "products": {
      "nodes": [
        {
          "contentType": null
        }
      ]
    }
  }
}
```

**Comment by renatoruk** [comment]
> @renatoruk this is expected behaviour actually! You have your CPT set to private `"public" => false` so this CPT is not publically queryable. Which means Gatsby does not have it. When you debug queries it's best to not use `wp-graphiql` as it's queries are authed and Gatsby isn't. So when I register your CPT, I see this in wp-graphiql:
> 
> ```json
> {
>   "data": {
>     "products": {
>       "nodes": [
>         {
>           "contentType": {
>             "node": {
>               "name": "products"
>             }
>           }
>         }
>       ]
>     }
>   }
> }
> ```
> 
> And in GraphQLPlayground (unauthenticated):
> 
> ```json
> {
>   "data": {
>     "products": {
>       "nodes": [
>         {
>           "contentType": null
>         }
>       ]
>     }
>   }
> }
> ```

Oh, I see! 🤯

Then, your update in the docs related to these authentication specifics explains it out pretty well! 
I'll use https://github.com/prisma-labs/graphql-playground from now on. Thanks a lot for your help, appreciate it!

**Comment by TylerBarnes** [comment]
Glad to hear it was helpful :) let me know if you run into anything else. BTW @jasonbahl and I have been talking about improving wp-graphiql to make this less problematic. Maybe by adding something like a toggle switch for authed vs not authed.

**Comment by renatoruk** [comment]
> Glad to hear it was helpful :) let me know if you run into anything else. BTW @jasonbahl and I have been talking about improving wp-graphiql to make this less problematic. Maybe by adding something like a toggle switch for authed vs not authed.

That sounds awesome! I think it would make a big difference if the user has the ability to toggle the authentication from there, especially for the users getting familiar with the whole Gatsby + WP stack.

It would also remove the need to use of alternative graphql client. :)
