### ISSUE TITLE
Email field missing from GraphQL User schema

### ISSUE THREAD

**Issue by woodwoerk** [gatsbyjs/gatsby-source-wordpress-experimental#77]
Hey there,

I'm not able to query `email` on a user and the email field isn't shown in the WpUser schema under `localhost:8000/___graphql`. The user email field is available within the WordPress GraphiQL plugin. Is this left out by design or missing?

gatsby-source-wordpress-experimental - ^1.0.7
WP Gatsby - 0.4.12 
WpGraphQL - 0.10.3

Reproduction (query under `src/pages/index.js`): https://github.com/woodwoerk/wordpress-gatsby-email-query-repro

Example query:
```
query Users {
  allWpUser {
    nodes {
      name
      email
    }
  }
}
```

Error:

```
 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "email" on type "WpUser".

If you don't expect "email" to exist on the type "WpUser" it is most likely a typo.
However, if you expect "email" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "email" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "WpUser":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src\pages\index.js:12:11
```

**Comment by TylerBarnes** [comment]
Hi @woodwoerk , this was an intentional choice to exclude some fields if they always return null when not authenticated. I chatted with Jason about it and realized people can easily filter these fields to make them public, so there's no reason to exclude these by default. Upgrade to `gatsby-source-wordpress-experimental@1.0.14` and the field should show up!

Thanks for raising this issue

**Comment by woodwoerk** [comment]
No errors when querying now, but I'm only getting `null` for the `email` field for all users (running 1.0.14)

@TylerBarnes should this be reopened?

**Comment by TylerBarnes** [comment]
@woodwoerk , email is a private field in WPGraphQL, are you filtering it to be public? You can test this using a GraphQL client besides wp-graphiql (which is authenticated) like GraphQL playground or Graphiql. When you use one of those to query do you see an email returned?

**Comment by woodwoerk** [comment]
Oops, my bad! I definitely wasn't making this public. Working as expected after adding a filter, thanks!

**Comment by kurtobando** [comment]
> Oops, my bad! I definitely wasn't making this public. Working as expected after adding a filter, thanks!

@woodwoerk cap, could I ask for the filter that works on your end?

**Comment by woodwoerk** [comment]
Hey @kurtobando, unfortunately I no longer have access, but I followed the example here: [Filter to add restricted field on Model](https://www.wpgraphql.com/recipes/filter-to-add-restricted-field-on-model/#gatsby-focus-wrapper)

Try this out (but please note, I haven't tested it):

```php
add_filter( 'graphql_allowed_fields_on_restricted_type', function( $fields, $model_name, $data, $visibility, $owner, $current_user ) {
	if ( 'UserObject' === $model_name ) {
		$fields[] = 'email';
	}
	return $fields;
}, 10, 6 );
```
