### ISSUE TITLE
Cannot query nested fields

### ISSUE THREAD

**Issue by pristas-peter** [gatsbyjs/gatsby-source-wordpress-experimental#79]
For more info, see:

https://github.com/GatsbyWPGutenberg/gatsby-wordpress-gutenberg/issues/44

**Comment by TylerBarnes** [comment]
Thanks @pristas-peter ! I followed up in that issue.

**Comment by TylerBarnes** [comment]
This is fixed in `gatsby-source-wordpress-experimental@1.3.1`
