### ISSUE TITLE
Docs: "Configuring WPGatsby - Setting Up Builds" doesn't mention which http method is used

### ISSUE THREAD

**Issue by vscncls** [gatsbyjs/gatsby-source-wordpress-experimental#80]
It would be really helpful if the docs explicitly mentioned that the webhook makes a **POST** request to the given url.

**Comment by TylerBarnes** [comment]
Hi @vscncls , thanks for the suggestion! I'm not opposed to this but I'm also wondering what knowing this will be helpful for. I believe this is an implementation detail that developers will never need to worry about, but I might be missing some use-case where this would be good to know.

**Comment by vscncls** [comment]
In my particular use-case, I have an endpoint that re-builds the website every time it receives a request and this endpoint happened to only accept GET requests, so my endpoint never recieved any requests when data was added/updated. it took me quite a while to understand why wp-graphql wasn't making a request my endpoint, I had to go peek in the source code to find out it was a POST request.

If someone decides to build their own solution for re-building their Gatsby website, they are probably gonna need this information, because lots of web frameworks (e.g., express) require you to explicitly mention which HTTP method is going to be used.

**Comment by TylerBarnes** [comment]
That's a great point! Let's add it

**Comment by TylerBarnes** [comment]
@vscncls just realized I didn't ask: are you interested in making a PR for this? :)

**Comment by vscncls** [comment]
Yes! I'll open a PR later today :+1:

**Comment by TylerBarnes** [comment]
Awesome 😄 thanks so much!
