### ISSUE TITLE
Docs don't mention that the "Builds webhook" field is a csv list

### ISSUE THREAD

**Issue by vscncls** [gatsbyjs/gatsby-source-wordpress-experimental#81]
[https://github.com/gatsbyjs/wp-gatsby/blob/master/src/ActionMonitor/ActionMonitor.php#L1008](https://github.com/gatsbyjs/wp-gatsby/blob/master/src/ActionMonitor/ActionMonitor.php#L1008)
It would be nice if the docs mentioned this behaviour.

**Comment by TylerBarnes** [comment]
Hi @vscncls , the reason it accepts a CSV list is only for us to be able to test various benchmarking services. It's not recommended to have your site hit multiple build webhooks usually. Do you have a use-case for doing so? For now it's an intentionally undocumented API which may be removed in the future.

Thanks for raising this point 👍

**Comment by vscncls** [comment]
Oh, that makes sense. I don't have a particular use-case for this, I was just taking a peek at the code and thought this was a cool feature.

Thanks for all the work you all have been putting in this update, is coming along pretty nicely!
