### ISSUE TITLE
GraphQL date formatString functionality not applied to modified

### ISSUE THREAD

**Issue by robmarshall** [gatsbyjs/gatsby-source-wordpress-experimental#83]
When running GraphQL queries it is currently possible to run formatString on a post/page date field. This lets you use a Moment format string to change the date output. Example:

```
query MyQuery {
  allWpPost {
    nodes {
      customDate: date(formatString: "YYYY-MM-DD, HH:mm:ss")
    }
  }
}
```

This does not work with modified. Example:

```
query MyQuery {
  allWpPost {
    nodes {
      customModified: modified(formatString: "YYYY-MM-DD, HH:mm:ss")
    }
  }
}
```

It would be helpful for this functionality to be mirrored, as date and modified tend to be used in the same way.

Helpful link: https://www.gatsbyjs.org/docs/graphql-concepts/#formatting-dates

**Comment by TylerBarnes** [comment]
Hi @robmarshall , thanks for raising this issue. Currently WPGraphQL doesn't have a built in Date scalar, making it hard to programatically determine what's a date when consuming and recreating the WPGQL schema in Gatsby.
I originally had thought of adding a type option so you could flag different fields as being a Date, but @jasonbahl mentioned WPGQL will be getting a Date scalar at some point. Less config is better IMO so we're currently waiting on that feature to be able to support Date fields across all fields. Currently fields that are top-level on a node named `date` are type as `Date` in Gatsby.

**Comment by robmarshall** [comment]
I believe (I may be mistaken) that there are only 4 date nodes on standard WordPress installs. date, dateGMT, modified, and modifiedGMT. Would it be possible to add date to these?

**Comment by TylerBarnes** [comment]
Absolutely! I'll put this on my list cause that's very reasonable and easy to do. Thanks for the suggestion

**Comment by TylerBarnes** [comment]
Upgrade to `gatsby-source-wordpress-experimental@1.2.0` for more Date fields :)

**Comment by robmarshall** [comment]
Nice one for sorting this!
