### ISSUE TITLE
WordPress Plugin - Preview button not working when settings complete

### ISSUE THREAD

**Issue by robmarshall** [gatsbyjs/gatsby-source-wordpress-experimental#84]
I have installed the most recent wp-gatsby WordPress plugin. 0.4.13.

On entering all settings details provided by Gatsby Cloud, the preview button does not load a Gatsby Cloud preview page.

**Comment by TylerBarnes** [comment]
Hi @robmarshall , thanks for opening an issue!
It's hard to tell what it could be from the description. Are you able to make me an admin on the site temporarily or take some screenshots of your settings? My email is tyler@gatsbyjs.com in either case. One thing to note is that previews currently require you to build your Gatsby pages using the WordPress uri field, so if you have a custom page path like `/blog/${node.slug}`, Preview wont work. This is something I'm working on fixing but for now uri's as page paths are required.
Additionally a reproduction repo where you're having this issue would be helpful if possible. 

Thanks Rob!

**Comment by robmarshall** [comment]
I have sent you an email. Thanks!

However, this strikes me as a WordPress plugin issue, as the URL within the WordPress preview button is not changing.

**Comment by TylerBarnes** [comment]
Thanks for the email @robmarshall , that's helpful. The url there shouldn't need to change as the preview url logic happens within the WP preview template. There is another issue open about preview as well so I will do some manual testing of Preview today to see what I come up with.

Thanks again

**Comment by robmarshall** [comment]
Hmm, maybe that is the problem.

Is the preview pane the Gutenburg panel? I am using the Classic Editor
plugin as Gutenburg is too much bloat for what we need.

I'll try removing that and see what happens.

**Comment by TylerBarnes** [comment]
Nope, classic editor actually works better :) Gutenberg works but is buggy in that it sometimes sends twice as many save_post hooks. I'm thinking this is probably a bug in WPGatsby or the source plugin. I'll keep you updated as I learn more.

Thanks

**Comment by TylerBarnes** [comment]
@robmarshall which versions of WPGraphQL and gatsby-source-wordpress-experimental are you on?

**Comment by robmarshall** [comment]
Hi Tyler, it is strange as it doesn't work on my staging site branch, but does work on master. Each one of these is a Gatsby Cloud site.

WPGraphQl WordPress plugin is 0.10.3
WP Gatsby WordPress plugin is 0.4.14

**Comment by TylerBarnes** [comment]
Thanks for the update @robmarshall ! When it doesn't work what do you see? If it's a 404 page can you try hitting refresh once the preview template loads and see if the preview appears?

**Comment by robmarshall** [comment]
I get either:
directed to the CMS homepage
directed to /wp-admin/post.php that then redirects to the correct URL, and then timeout or a white screen with ECCONNREFUSED
OR: it works.

**Comment by TylerBarnes** [comment]
Hi @robmarshall I just ran into some preview troubles as well. Can you check this comment and see if it solves it for you? https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/78#issuecomment-664702498

I'm currently working on surfacing this to the admin preview template with steps on fixing this if revisions are disabled.

**Comment by robmarshall** [comment]
Sorry about not coming back to this. I missed the reply. This is no longer an issue for me. Not sure the fix, but can no longer replicate.

**Comment by TylerBarnes** [comment]
🤔 that's odd but glad to hear it's no longer an issue for you! There is currently a re-work of preview happening which will make it a lot more stable and straight forward. I'm closing this issue for now, you can follow along on progress here https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/97 if you're interested
