### ISSUE TITLE
WooCommerce: unexpected high number of fetched nodes for Product type

### ISSUE THREAD

**Issue by jacobarriola** [gatsbyjs/gatsby-source-wordpress-experimental#87]
## Repro steps
* run `gatsby develop`

## Expected behavior
* ~ 1,200 `Product` type nodes should be fetched 

## Actual behavior
* ~20,000 (and counting) `Product` type nodes were fetched
* the fetch process ran for 2 hours and halted because my machine when to sleep

## Notes
* endpoint: https://therudis-staging.ppjs4w65-liquidwebsites.com/graphql
* there are currently ~1,200 `product` posts
* there are currently ~9,000 `product_variation` posts (not sure how variations impact)
* there are currently ~80,000 `order` posts (not sure how orders impact)

## Dependency versions
* wp-graphql: `0.10.3`
* wp-gatsby: `0.4.13`
* wp-graphql-woocommerce: `0.5.1`
* gatsby-source-wordpress-experimental: `1.0.12`

**Comment by jacobarriola** [comment]
@TylerBarnes I think this may be related to ElasticPress. I'm running issues with pagination where despite passing in the correct endCursor, I get back the first N products (all other post types work as expected).

When I disable the WooCommerce featured of ElasticPress (or disable the plugin), pagination works as expected.

That's why I think the `gatsby develop` hangs, because it's caught in an infinite loop. I'll need to debug locally to see what EP is doing to WooCommerce queries, especially because we're in a non-search transaction for `gatsby develop`.

Unfortunately, I'm running into new issue where `gatsby develop` is returning a 500 error.

What's the best way to debug this?

```bash
 gatsby-source-wordpress  Request failed with status code 500

Error occured while fetching nodes of the "Product" type.

GraphQL request to https://therudis-staging.ppjs4w65-liquidwebsites.com/graphql failed.

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests
  - WPGraphQL and WPGatsby are installed in your WordPress backend
```

**Comment by jacobarriola** [comment]
Whoops, forgot to read the docs on debugging 🤦🏽‍♂️.

I'll follow the documented steps and will report back.

https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/debugging-and-troubleshooting.md#wordpress-50-errors

**Comment by jacobarriola** [comment]
@TylerBarnes I fixed the WP 500 issues. For my case, it was a few things:

1. Lowered down the `schema.perPage` to `1`. The `Product` type kept getting hogged 🐖 down
2. Raised `schema.timeout` to `50000`
3. Excluded `metaData` and `contentType` fields. Looks like the WP instance I'm hitting was returning objects instead of strings in some of these fields. These were caused by two WooCommerce add-ons: `WooCommerce Waitlist` and `WooCommerce Google Product Feed`
4. Excluded `PostFormat` Type - it was taking a long time to get all the data

I still need to look at why ElasticPress is causing an infinite loop when fetching products, but I at least wanted to document my findings should it help you or someone else that views this thread.

**Comment by TylerBarnes** [comment]
Hey @jacobarriola , thanks for digging into all these issues. We've decided that for stable release we're just going to cover the most common scenarios for using core data (and acf) when building sites. After that we do want to look at making sure Woo is properly supported but for now it will be scoped outside of the first stable release. Thanks again!

**Comment by jacobarriola** [comment]
All good, @TylerBarnes. I'll post any additional findings that are related to this task, should they come up so that stuff is documented.

**Comment by TylerBarnes** [comment]
Sweet, thanks so much :)

**Comment by jacobarriola** [comment]
@TylerBarnes I think I found the issue with ElasticPress. By design, it integrates itself for all WooCommerce queries, not just search. 

For pagination, I've noticed that cursor-based pagination breaks when ElasticPress is part of the query. I ran a  typical WordPress search on paged elements (ie page 2 an on), and noticed that the query ElasticPress uses contains a `paged` `query_var`, which is then translated over to Elasticsearch via an offset.

Therefore, when running queries via GraphQL, we are not passing any `paged` `query_var`, so the same posts return regardless of the `endCursor` value that's added to the `after` argument.

For now, I'm disabling ElasticPress on everything except for search.  Here's the snippet should anyone run into this issue.

```php
/**
 * Only use EP for GraphQL search or in the WP admin.
 *
 * By default all WooCommerce queries run through ElasticPress. This was causing issues with
 * pagination and infinite graphql requests for products during a build. For simplicity,
 * let's only use EP for searching and not for WP_Query.
 */
add_filter( 'ep_skip_query_integration', function ( bool $skip, \WP_Query $query ): bool {
	// Allow admin queries to go through
	if ( true === $query->is_admin ) {
		return $skip;
	}

	if ( false === function_exists( 'is_graphql_http_request' ) ) {
		return $skip;
	}

	if ( false === is_graphql_http_request() ) {
		return $skip;
	}

	if ( true === $query->is_search ) {
		return $skip;
	}

	// Skip EP Query integration
	return true;
}, 10, 2 );
```
