### ISSUE TITLE
Some inline images aren't processed to gatsby-image

### ISSUE THREAD

**Issue by woodwoerk** [gatsbyjs/gatsby-source-wordpress-experimental#89]
Heya!

Some inline images are no longer being processed to `gatsby-image`s, I rolled back to 1.0.7 and all images work as expected there. I can't spot a pattern here, all are bog standard jpegs hosted on WordPress without anything custom, some of the same images on a single page become `gatsby-image`s and others don't.

- Private reproduction (@TylerBarnes has access): https://github.com/woodwoerk/nuori-fi-2020
- [Example page](https://nuori-fi-2020.azureedge.net/2020/07/krista-kosonen-aliquam-lorem-ante-dapibus-in-viverra-quis-feugiat-a-tellus/) with a mix of normal images and gatsby images

Relevant gatsby-config:

```
...
        develop: {
          nodeUpdateInterval: 10000,
          hardCacheMediaFiles: true,
        },
        html: {
          useGatsbyImage: true,
          imageQuality: 80,
          imageMaxWidth: 1400,
        },
...
```

Running `gatsby start`, the logs show less `MediaItem`s are fetched in 1.0.14 than in 1.0.7

- 1.0.7:
```
success  gatsby-source-wordpress  MediaItem - 117.249s - fetched 129
```

- 1.0.14:
```
success  gatsby-source-wordpress  MediaItem - 88.116s - fetched 98
```

**Comment by TylerBarnes** [comment]
🤔 oo, thanks for reporting this. And thanks for continuing to point out these issues. I have it on my todo list to write some exhaustive integration tests for images in html, I think I'll need to bump that up my list and do that as I fix this issue. Thanks again for your patience @woodwoerk !!

**Comment by woodwoerk** [comment]
Thank _you_ for the work on the plugin! 😄 Even in these early days it's already proving to make WordPress life way easier. Cheers!

**Comment by TylerBarnes** [comment]
That's awesome to hear 😄 glad it's useful!!

**Comment by TylerBarnes** [comment]
I think this might be fixed, I'll double check and follow up, thanks for your patience here!

**Comment by TylerBarnes** [comment]
Sweet :) I think it's fixed! I've also added static asset processing tests to ensure it doesn't regress. It's checking for the content of transforms as well as the total count of MediaItem nodes on a cold build and a delta update. So I think we're good!
