### ISSUE TITLE
Woocommerce product categories: only top level is returned with no children

### ISSUE THREAD

**Issue by mattdabell** [gatsbyjs/gatsby-source-wordpress-experimental#96]
Hi,

There's a problem with product categories which seems to be on the gatsby side, related to taxonomy hierarchy. Essentially only the top level product categories are pulled through, and when you try to query their children, you get an empty array.

When I do the following query in playground:

```
{
  productCategories (first: 100) {
    nodes {
      name
      children {
        nodes {
          name
        }
      }
    }
  }
}
```

I get all of the categories, regardless of where they sit in the category hierarchy. Also, children is correctly populated.

However when I make the equivalent query in graphiql:

```
{
  allWpProductCategory(limit: 100) {
    nodes {
      name
      wpChildren {
        nodes {
          name
        }
      }
    }
  }
}
```
Then I only get the top level categories, and they all return an empty array for the children.

This seems to be a woocommerce-specific problem as I checked post categories which works as expected: you get all categories as well as their children.

Feel free to use the same endpoint I emailed you before to reproduce.

I'm on plugin version 1.1.1

Thanks!

**Comment by mattdabell** [comment]
Just to add to this: I tried to generate the categories by downloading the products and checking what categories they have, but it still only shows the top level categories. 

Eg if I try this in Graphiql I only get the top level categories:

```
{
  allWpProduct {
    nodes {
      name
      productCategories {
        nodes {
          name
        }
      }
    }
  }
}
```

whereas this query in playground returns all categories no problem:

```
{
  products {
    nodes {
      name
      productCategories {
        nodes {
          name
        }
      }
    }
  }
}
```

**Comment by TylerBarnes** [comment]
Ah, yeah this is a general problem which has a specific fix for built in categories. I have a general fix in planning but it's not implemented yet. Follow along in https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/145 for updates
